// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package platformstore

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestAuditHash = `-- name: GetLatestAuditHash :one
SELECT COALESCE(
    (SELECT hash FROM platform.audit_log WHERE tenant_id = $1 ORDER BY occurred_at DESC, id DESC LIMIT 1),
    ''
)::text AS hash
`

// The hash of the most recent audit_log row for this tenant, or "" if this is the first entry.
// The caller must hold this within the same transaction that inserts the next row (append-only
// chain, CLAUDE.md rule 4): concurrent writers for one tenant would otherwise race on prev_hash.
func (q *Queries) GetLatestAuditHash(ctx context.Context, tenantID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLatestAuditHash, tenantID)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO platform.audit_log (
    tenant_id, actor_type, actor_id, action, entity_type, entity_id, before, after, ip, user_agent, prev_hash, hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NULLIF($11, ''), $12
)
RETURNING id, occurred_at
`

type InsertAuditLogParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ActorType  string      `db:"actor_type" json:"actor_type"`
	ActorID    pgtype.UUID `db:"actor_id" json:"actor_id"`
	Action     string      `db:"action" json:"action"`
	EntityType *string     `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	Before     []byte      `db:"before" json:"before"`
	After      []byte      `db:"after" json:"after"`
	Ip         *netip.Addr `db:"ip" json:"ip"`
	UserAgent  *string     `db:"user_agent" json:"user_agent"`
	Column11   interface{} `db:"column_11" json:"column_11"`
	Hash       string      `db:"hash" json:"hash"`
}

type InsertAuditLogRow struct {
	ID         int64              `db:"id" json:"id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.UserAgent,
		arg.Column11,
		arg.Hash,
	)
	var i InsertAuditLogRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}
