// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package filesstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachFile = `-- name: AttachFile :execrows
UPDATE platform.files SET entity_type = $1, entity_id = $2, retention_until = NULL,
       row_version = row_version + 1, updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $3 AND entity_type IS NULL
`

type AttachFileParams struct {
	EntityType *string     `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	ID         uuid.UUID   `db:"id" json:"id"`
}

// Only an unattached file can be attached, so a file id can't be re-pointed at another record.
func (q *Queries) AttachFile(ctx context.Context, arg AttachFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachFile, arg.EntityType, arg.EntityID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM platform.files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, tenant_id, bucket, object_key, file_name, mime_type, size_bytes, sha256, av_status,
       entity_type, entity_id, retention_until, created_at, created_by
FROM platform.files WHERE id = $1
`

type GetFileRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	TenantID       uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Bucket         string             `db:"bucket" json:"bucket"`
	ObjectKey      string             `db:"object_key" json:"object_key"`
	FileName       string             `db:"file_name" json:"file_name"`
	MimeType       string             `db:"mime_type" json:"mime_type"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	Sha256         string             `db:"sha256" json:"sha256"`
	AvStatus       string             `db:"av_status" json:"av_status"`
	EntityType     *string            `db:"entity_type" json:"entity_type"`
	EntityID       pgtype.UUID        `db:"entity_id" json:"entity_id"`
	RetentionUntil pgtype.Timestamptz `db:"retention_until" json:"retention_until"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy      pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (GetFileRow, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i GetFileRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Bucket,
		&i.ObjectKey,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.AvStatus,
		&i.EntityType,
		&i.EntityID,
		&i.RetentionUntil,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO platform.files (id, tenant_id, bucket, object_key, file_name, mime_type, size_bytes, sha256,
                            encryption_key_id, av_status, retention_until, created_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, $5, $6, $7,
        $8, 'pending', $9, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING created_at
`

type InsertFileParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Bucket          string             `db:"bucket" json:"bucket"`
	ObjectKey       string             `db:"object_key" json:"object_key"`
	FileName        string             `db:"file_name" json:"file_name"`
	MimeType        string             `db:"mime_type" json:"mime_type"`
	SizeBytes       int64              `db:"size_bytes" json:"size_bytes"`
	Sha256          string             `db:"sha256" json:"sha256"`
	EncryptionKeyID *string            `db:"encryption_key_id" json:"encryption_key_id"`
	RetentionUntil  pgtype.Timestamptz `db:"retention_until" json:"retention_until"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.ID,
		arg.Bucket,
		arg.ObjectKey,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.EncryptionKeyID,
		arg.RetentionUntil,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const lockFileForScan = `-- name: LockFileForScan :one
SELECT id, bucket, object_key, av_status FROM platform.files WHERE id = $1 FOR UPDATE
`

type LockFileForScanRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Bucket    string    `db:"bucket" json:"bucket"`
	ObjectKey string    `db:"object_key" json:"object_key"`
	AvStatus  string    `db:"av_status" json:"av_status"`
}

func (q *Queries) LockFileForScan(ctx context.Context, id uuid.UUID) (LockFileForScanRow, error) {
	row := q.db.QueryRow(ctx, lockFileForScan, id)
	var i LockFileForScanRow
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.AvStatus,
	)
	return i, err
}

const lockOrphanFile = `-- name: LockOrphanFile :one
SELECT id, bucket, object_key FROM platform.files
WHERE id = $1 AND entity_type IS NULL AND retention_until <= now()
FOR UPDATE
`

type LockOrphanFileRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Bucket    string    `db:"bucket" json:"bucket"`
	ObjectKey string    `db:"object_key" json:"object_key"`
}

// An upload still unattached when its orphan deadline passes; nothing references it, so it can go.
func (q *Queries) LockOrphanFile(ctx context.Context, id uuid.UUID) (LockOrphanFileRow, error) {
	row := q.db.QueryRow(ctx, lockOrphanFile, id)
	var i LockOrphanFileRow
	err := row.Scan(&i.ID, &i.Bucket, &i.ObjectKey)
	return i, err
}

const setFileAVStatus = `-- name: SetFileAVStatus :exec
UPDATE platform.files SET av_status = $1, row_version = row_version + 1,
       updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $2
`

type SetFileAVStatusParams struct {
	AvStatus string    `db:"av_status" json:"av_status"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) SetFileAVStatus(ctx context.Context, arg SetFileAVStatusParams) error {
	_, err := q.db.Exec(ctx, setFileAVStatus, arg.AvStatus, arg.ID)
	return err
}
