// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment_risks.sql

package dpiastore

import (
	"context"

	"github.com/google/uuid"
)

const linkAssessmentRisk = `-- name: LinkAssessmentRisk :exec

INSERT INTO assess.assessment_risks (assessment_id, risk_id, tenant_id)
VALUES ($1, $2, NULLIF(current_setting('app.tenant_id', true), '')::uuid)
ON CONFLICT (assessment_id, risk_id) DO NOTHING
`

type LinkAssessmentRiskParams struct {
	AssessmentID uuid.UUID `db:"assessment_id" json:"assessment_id"`
	RiskID       uuid.UUID `db:"risk_id" json:"risk_id"`
}

// DPIA-06: the link between one DPIA round (assess.assessments) and a risk.risks row the risk engine owns
// (rule 9 — dpia never writes risk.risks itself, only this link in its own schema).
func (q *Queries) LinkAssessmentRisk(ctx context.Context, arg LinkAssessmentRiskParams) error {
	_, err := q.db.Exec(ctx, linkAssessmentRisk, arg.AssessmentID, arg.RiskID)
	return err
}

const listAssessmentRiskIDs = `-- name: ListAssessmentRiskIDs :many
SELECT risk_id FROM assess.assessment_risks WHERE assessment_id = $1
`

func (q *Queries) ListAssessmentRiskIDs(ctx context.Context, assessmentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAssessmentRiskIDs, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var risk_id uuid.UUID
		if err := rows.Scan(&risk_id); err != nil {
			return nil, err
		}
		items = append(items, risk_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAssessmentRisk = `-- name: UnlinkAssessmentRisk :execrows
DELETE FROM assess.assessment_risks WHERE assessment_id = $1 AND risk_id = $2
`

type UnlinkAssessmentRiskParams struct {
	AssessmentID uuid.UUID `db:"assessment_id" json:"assessment_id"`
	RiskID       uuid.UUID `db:"risk_id" json:"risk_id"`
}

func (q *Queries) UnlinkAssessmentRisk(ctx context.Context, arg UnlinkAssessmentRiskParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkAssessmentRisk, arg.AssessmentID, arg.RiskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
