// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dpia.sql

package dpiastore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateScreeningRules = `-- name: DeactivateScreeningRules :exec
UPDATE assess.screening_rules SET is_active = false, updated_at = now() WHERE is_active = true
`

func (q *Queries) DeactivateScreeningRules(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateScreeningRules)
	return err
}

const getActiveScreeningRule = `-- name: GetActiveScreeningRule :one
SELECT id, tenant_id, criteria, min_factors, min_score, is_active, created_at, created_by, updated_at, updated_by, row_version FROM assess.screening_rules
WHERE is_active = true
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveScreeningRule(ctx context.Context) (AssessScreeningRule, error) {
	row := q.db.QueryRow(ctx, getActiveScreeningRule)
	var i AssessScreeningRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Criteria,
		&i.MinFactors,
		&i.MinScore,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, tenant_id, assessment_type, template_id, form_version_id, title, subject_type, subject_id, activity_id, round_no, previous_id, status, screening_result, screening_reason, score, risk_level, owner_user_id, due_at, approved_at, next_review_at, created_at, created_by, updated_at, updated_by, row_version FROM assess.assessments WHERE id = $1 AND assessment_type = 'dpia'
`

func (q *Queries) GetAssessment(ctx context.Context, id uuid.UUID) (AssessAssessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, id)
	var i AssessAssessment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentType,
		&i.TemplateID,
		&i.FormVersionID,
		&i.Title,
		&i.SubjectType,
		&i.SubjectID,
		&i.ActivityID,
		&i.RoundNo,
		&i.PreviousID,
		&i.Status,
		&i.ScreeningResult,
		&i.ScreeningReason,
		&i.Score,
		&i.RiskLevel,
		&i.OwnerUserID,
		&i.DueAt,
		&i.ApprovedAt,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const getLatestAssessmentForActivity = `-- name: GetLatestAssessmentForActivity :one
SELECT id, tenant_id, assessment_type, template_id, form_version_id, title, subject_type, subject_id, activity_id, round_no, previous_id, status, screening_result, screening_reason, score, risk_level, owner_user_id, due_at, approved_at, next_review_at, created_at, created_by, updated_at, updated_by, row_version FROM assess.assessments
WHERE assessment_type = 'dpia' AND activity_id = $1
ORDER BY round_no DESC
LIMIT 1
`

func (q *Queries) GetLatestAssessmentForActivity(ctx context.Context, activityID pgtype.UUID) (AssessAssessment, error) {
	row := q.db.QueryRow(ctx, getLatestAssessmentForActivity, activityID)
	var i AssessAssessment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentType,
		&i.TemplateID,
		&i.FormVersionID,
		&i.Title,
		&i.SubjectType,
		&i.SubjectID,
		&i.ActivityID,
		&i.RoundNo,
		&i.PreviousID,
		&i.Status,
		&i.ScreeningResult,
		&i.ScreeningReason,
		&i.Score,
		&i.RiskLevel,
		&i.OwnerUserID,
		&i.DueAt,
		&i.ApprovedAt,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const getScreeningTemplate = `-- name: GetScreeningTemplate :one
SELECT id, tenant_id, assessment_type, code, name, form_id, version_no, legal_refs, status, created_at, created_by, updated_at, updated_by, row_version FROM assess.templates
WHERE assessment_type = 'dpia' AND code = $1 AND status = 'published'
ORDER BY tenant_id NULLS LAST
LIMIT 1
`

// The tenant's own override of a screening template (same code) wins over the global default (ORG-07/PNG-03
// override pattern) — RLS already limits visible rows to NULL (global) or the caller's own tenant.
func (q *Queries) GetScreeningTemplate(ctx context.Context, code string) (AssessTemplate, error) {
	row := q.db.QueryRow(ctx, getScreeningTemplate, code)
	var i AssessTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentType,
		&i.Code,
		&i.Name,
		&i.FormID,
		&i.VersionNo,
		&i.LegalRefs,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const insertAnswer = `-- name: InsertAnswer :one
INSERT INTO assess.answers (id, tenant_id, assessment_id, question_code, answer, answered_by, created_by, updated_by)
VALUES ($1, NULLIF(current_setting('app.tenant_id', true), '')::uuid, $2, $3, $4,
        NULLIF(current_setting('app.user_id', true), '')::uuid,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, tenant_id, assessment_id, section_id, question_code, answer, evidence_file_ids, answered_by, ai_suggested, confirmed_by, created_at, created_by, updated_at, updated_by, row_version
`

type InsertAnswerParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	AssessmentID uuid.UUID `db:"assessment_id" json:"assessment_id"`
	QuestionCode string    `db:"question_code" json:"question_code"`
	Answer       []byte    `db:"answer" json:"answer"`
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) (AssessAnswer, error) {
	row := q.db.QueryRow(ctx, insertAnswer,
		arg.ID,
		arg.AssessmentID,
		arg.QuestionCode,
		arg.Answer,
	)
	var i AssessAnswer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentID,
		&i.SectionID,
		&i.QuestionCode,
		&i.Answer,
		&i.EvidenceFileIds,
		&i.AnsweredBy,
		&i.AiSuggested,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const insertAssessment = `-- name: InsertAssessment :one
INSERT INTO assess.assessments (id, tenant_id, assessment_type, template_id, form_version_id, title, subject_type,
    subject_id, activity_id, round_no, previous_id, status, screening_result, screening_reason, score,
    created_by, updated_by)
VALUES ($1, NULLIF(current_setting('app.tenant_id', true), '')::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, tenant_id, assessment_type, template_id, form_version_id, title, subject_type, subject_id, activity_id, round_no, previous_id, status, screening_result, screening_reason, score, risk_level, owner_user_id, due_at, approved_at, next_review_at, created_at, created_by, updated_at, updated_by, row_version
`

type InsertAssessmentParams struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	AssessmentType  string         `db:"assessment_type" json:"assessment_type"`
	TemplateID      uuid.UUID      `db:"template_id" json:"template_id"`
	FormVersionID   uuid.UUID      `db:"form_version_id" json:"form_version_id"`
	Title           string         `db:"title" json:"title"`
	SubjectType     string         `db:"subject_type" json:"subject_type"`
	SubjectID       pgtype.UUID    `db:"subject_id" json:"subject_id"`
	ActivityID      pgtype.UUID    `db:"activity_id" json:"activity_id"`
	RoundNo         int16          `db:"round_no" json:"round_no"`
	PreviousID      pgtype.UUID    `db:"previous_id" json:"previous_id"`
	Status          string         `db:"status" json:"status"`
	ScreeningResult *string        `db:"screening_result" json:"screening_result"`
	ScreeningReason *string        `db:"screening_reason" json:"screening_reason"`
	Score           pgtype.Numeric `db:"score" json:"score"`
}

func (q *Queries) InsertAssessment(ctx context.Context, arg InsertAssessmentParams) (AssessAssessment, error) {
	row := q.db.QueryRow(ctx, insertAssessment,
		arg.ID,
		arg.AssessmentType,
		arg.TemplateID,
		arg.FormVersionID,
		arg.Title,
		arg.SubjectType,
		arg.SubjectID,
		arg.ActivityID,
		arg.RoundNo,
		arg.PreviousID,
		arg.Status,
		arg.ScreeningResult,
		arg.ScreeningReason,
		arg.Score,
	)
	var i AssessAssessment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentType,
		&i.TemplateID,
		&i.FormVersionID,
		&i.Title,
		&i.SubjectType,
		&i.SubjectID,
		&i.ActivityID,
		&i.RoundNo,
		&i.PreviousID,
		&i.Status,
		&i.ScreeningResult,
		&i.ScreeningReason,
		&i.Score,
		&i.RiskLevel,
		&i.OwnerUserID,
		&i.DueAt,
		&i.ApprovedAt,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const insertScreeningRule = `-- name: InsertScreeningRule :one
INSERT INTO assess.screening_rules (id, tenant_id, criteria, min_factors, min_score, is_active, created_by, updated_by)
VALUES ($1, NULLIF(current_setting('app.tenant_id', true), '')::uuid, $2, $3, $4, true,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, tenant_id, criteria, min_factors, min_score, is_active, created_at, created_by, updated_at, updated_by, row_version
`

type InsertScreeningRuleParams struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	Criteria   []byte         `db:"criteria" json:"criteria"`
	MinFactors int16          `db:"min_factors" json:"min_factors"`
	MinScore   pgtype.Numeric `db:"min_score" json:"min_score"`
}

func (q *Queries) InsertScreeningRule(ctx context.Context, arg InsertScreeningRuleParams) (AssessScreeningRule, error) {
	row := q.db.QueryRow(ctx, insertScreeningRule,
		arg.ID,
		arg.Criteria,
		arg.MinFactors,
		arg.MinScore,
	)
	var i AssessScreeningRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Criteria,
		&i.MinFactors,
		&i.MinScore,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const listAnswersForAssessment = `-- name: ListAnswersForAssessment :many
SELECT id, tenant_id, assessment_id, section_id, question_code, answer, evidence_file_ids, answered_by, ai_suggested, confirmed_by, created_at, created_by, updated_at, updated_by, row_version FROM assess.answers WHERE assessment_id = $1 ORDER BY created_at
`

func (q *Queries) ListAnswersForAssessment(ctx context.Context, assessmentID uuid.UUID) ([]AssessAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswersForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessAnswer
	for rows.Next() {
		var i AssessAnswer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentID,
			&i.SectionID,
			&i.QuestionCode,
			&i.Answer,
			&i.EvidenceFileIds,
			&i.AnsweredBy,
			&i.AiSuggested,
			&i.ConfirmedBy,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessments = `-- name: ListAssessments :many
SELECT id, tenant_id, assessment_type, template_id, form_version_id, title, subject_type, subject_id, activity_id, round_no, previous_id, status, screening_result, screening_reason, score, risk_level, owner_user_id, due_at, approved_at, next_review_at, created_at, created_by, updated_at, updated_by, row_version FROM assess.assessments
WHERE assessment_type = 'dpia'
    AND ($1::uuid IS NULL OR activity_id = $1)
    AND ($2::timestamptz IS NULL OR (created_at, id) < ($2, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAssessmentsParams struct {
	ActivityID pgtype.UUID        `db:"activity_id" json:"activity_id"`
	CursorAt   pgtype.Timestamptz `db:"cursor_at" json:"cursor_at"`
	CursorID   pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	Lim        int32              `db:"lim" json:"lim"`
}

// Newest first; keyset cursor on (created_at, id).
func (q *Queries) ListAssessments(ctx context.Context, arg ListAssessmentsParams) ([]AssessAssessment, error) {
	rows, err := q.db.Query(ctx, listAssessments,
		arg.ActivityID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessAssessment
	for rows.Next() {
		var i AssessAssessment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentType,
			&i.TemplateID,
			&i.FormVersionID,
			&i.Title,
			&i.SubjectType,
			&i.SubjectID,
			&i.ActivityID,
			&i.RoundNo,
			&i.PreviousID,
			&i.Status,
			&i.ScreeningResult,
			&i.ScreeningReason,
			&i.Score,
			&i.RiskLevel,
			&i.OwnerUserID,
			&i.DueAt,
			&i.ApprovedAt,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
