// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: necessity.sql

package dpiastore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnswersForSection = `-- name: DeleteAnswersForSection :exec
DELETE FROM assess.answers WHERE section_id = $1
`

func (q *Queries) DeleteAnswersForSection(ctx context.Context, sectionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnswersForSection, sectionID)
	return err
}

const getSectionByCode = `-- name: GetSectionByCode :one
SELECT id, tenant_id, assessment_id, section_code, assignee_user_id, guest_token_id, status, submitted_at, created_at, created_by, updated_at, updated_by, row_version FROM assess.sections WHERE assessment_id = $1 AND section_code = $2 LIMIT 1
`

type GetSectionByCodeParams struct {
	AssessmentID uuid.UUID `db:"assessment_id" json:"assessment_id"`
	SectionCode  string    `db:"section_code" json:"section_code"`
}

func (q *Queries) GetSectionByCode(ctx context.Context, arg GetSectionByCodeParams) (AssessSection, error) {
	row := q.db.QueryRow(ctx, getSectionByCode, arg.AssessmentID, arg.SectionCode)
	var i AssessSection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentID,
		&i.SectionCode,
		&i.AssigneeUserID,
		&i.GuestTokenID,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const insertSection = `-- name: InsertSection :one
INSERT INTO assess.sections (id, tenant_id, assessment_id, section_code, status, submitted_at, created_by, updated_by)
VALUES ($1, NULLIF(current_setting('app.tenant_id', true), '')::uuid, $2, $3, 'submitted', now(),
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, tenant_id, assessment_id, section_code, assignee_user_id, guest_token_id, status, submitted_at, created_at, created_by, updated_at, updated_by, row_version
`

type InsertSectionParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	AssessmentID uuid.UUID `db:"assessment_id" json:"assessment_id"`
	SectionCode  string    `db:"section_code" json:"section_code"`
}

func (q *Queries) InsertSection(ctx context.Context, arg InsertSectionParams) (AssessSection, error) {
	row := q.db.QueryRow(ctx, insertSection, arg.ID, arg.AssessmentID, arg.SectionCode)
	var i AssessSection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentID,
		&i.SectionCode,
		&i.AssigneeUserID,
		&i.GuestTokenID,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const insertSectionAnswer = `-- name: InsertSectionAnswer :one
INSERT INTO assess.answers (id, tenant_id, assessment_id, section_id, question_code, answer, answered_by, created_by, updated_by)
VALUES ($1, NULLIF(current_setting('app.tenant_id', true), '')::uuid, $2, $3, $4, $5,
        NULLIF(current_setting('app.user_id', true), '')::uuid,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, tenant_id, assessment_id, section_id, question_code, answer, evidence_file_ids, answered_by, ai_suggested, confirmed_by, created_at, created_by, updated_at, updated_by, row_version
`

type InsertSectionAnswerParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	AssessmentID uuid.UUID   `db:"assessment_id" json:"assessment_id"`
	SectionID    pgtype.UUID `db:"section_id" json:"section_id"`
	QuestionCode string      `db:"question_code" json:"question_code"`
	Answer       []byte      `db:"answer" json:"answer"`
}

func (q *Queries) InsertSectionAnswer(ctx context.Context, arg InsertSectionAnswerParams) (AssessAnswer, error) {
	row := q.db.QueryRow(ctx, insertSectionAnswer,
		arg.ID,
		arg.AssessmentID,
		arg.SectionID,
		arg.QuestionCode,
		arg.Answer,
	)
	var i AssessAnswer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentID,
		&i.SectionID,
		&i.QuestionCode,
		&i.Answer,
		&i.EvidenceFileIds,
		&i.AnsweredBy,
		&i.AiSuggested,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const listAnswersForSection = `-- name: ListAnswersForSection :many
SELECT id, tenant_id, assessment_id, section_id, question_code, answer, evidence_file_ids, answered_by, ai_suggested, confirmed_by, created_at, created_by, updated_at, updated_by, row_version FROM assess.answers WHERE section_id = $1 ORDER BY created_at
`

func (q *Queries) ListAnswersForSection(ctx context.Context, sectionID pgtype.UUID) ([]AssessAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswersForSection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessAnswer
	for rows.Next() {
		var i AssessAnswer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentID,
			&i.SectionID,
			&i.QuestionCode,
			&i.Answer,
			&i.EvidenceFileIds,
			&i.AnsweredBy,
			&i.AiSuggested,
			&i.ConfirmedBy,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resubmitSection = `-- name: ResubmitSection :one
UPDATE assess.sections SET status = 'submitted', submitted_at = now(), updated_at = now(),
    updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $1
RETURNING id, tenant_id, assessment_id, section_code, assignee_user_id, guest_token_id, status, submitted_at, created_at, created_by, updated_at, updated_by, row_version
`

// A redo of the same section (DPIA-05 answered again): keep the row, refresh submitted_at.
func (q *Queries) ResubmitSection(ctx context.Context, id uuid.UUID) (AssessSection, error) {
	row := q.db.QueryRow(ctx, resubmitSection, id)
	var i AssessSection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentID,
		&i.SectionCode,
		&i.AssigneeUserID,
		&i.GuestTokenID,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}
