// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clauses.sql

package agreementstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAgreementClauses = `-- name: CountAgreementClauses :one
SELECT count(*)::int FROM agreement.clauses WHERE agreement_id = $1
`

func (q *Queries) CountAgreementClauses(ctx context.Context, agreementID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAgreementClauses, agreementID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAgreementClause = `-- name: DeleteAgreementClause :execrows
DELETE FROM agreement.clauses WHERE id = $1 AND agreement_id = $2
`

type DeleteAgreementClauseParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	AgreementID uuid.UUID `db:"agreement_id" json:"agreement_id"`
}

func (q *Queries) DeleteAgreementClause(ctx context.Context, arg DeleteAgreementClauseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgreementClause, arg.ID, arg.AgreementID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAgreementClause = `-- name: InsertAgreementClause :one

INSERT INTO agreement.clauses (id, tenant_id, agreement_id, clause_id, clause_version_no, position, is_mandatory, created_by, updated_by)
VALUES ($1, NULLIF(current_setting('app.tenant_id', true), '')::uuid, $2, $3, $4, $5,
    $6, NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, tenant_id, agreement_id, clause_id, clause_version_no, position, is_mandatory, customized_body, created_at, created_by, updated_at, updated_by, row_version
`

type InsertAgreementClauseParams struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	AgreementID     uuid.UUID   `db:"agreement_id" json:"agreement_id"`
	ClauseID        pgtype.UUID `db:"clause_id" json:"clause_id"`
	ClauseVersionNo *int32      `db:"clause_version_no" json:"clause_version_no"`
	Position        int16       `db:"position" json:"position"`
	IsMandatory     bool        `db:"is_mandatory" json:"is_mandatory"`
}

// DPA-03 (ข้อกำหนดที่ต้องมี): attach platform.clause_library entries to an agreement and check them against
// agreement.mandatory_rules before the document can be submitted for approval.
func (q *Queries) InsertAgreementClause(ctx context.Context, arg InsertAgreementClauseParams) (AgreementClause, error) {
	row := q.db.QueryRow(ctx, insertAgreementClause,
		arg.ID,
		arg.AgreementID,
		arg.ClauseID,
		arg.ClauseVersionNo,
		arg.Position,
		arg.IsMandatory,
	)
	var i AgreementClause
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementID,
		&i.ClauseID,
		&i.ClauseVersionNo,
		&i.Position,
		&i.IsMandatory,
		&i.CustomizedBody,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RowVersion,
	)
	return i, err
}

const listAgreementClauseCodes = `-- name: ListAgreementClauseCodes :many
SELECT DISTINCT cl.code
FROM agreement.clauses c
JOIN platform.clause_library cl ON cl.id = c.clause_id
WHERE c.agreement_id = $1
`

// Every clause_library code already attached to this agreement — used to compare against the tenant's own
// mandatory_rules codes.
func (q *Queries) ListAgreementClauseCodes(ctx context.Context, agreementID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAgreementClauseCodes, agreementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgreementClauses = `-- name: ListAgreementClauses :many
SELECT c.id, c.agreement_id, c.clause_id, c.clause_version_no, c.position, c.is_mandatory, c.row_version, c.created_at,
    cl.code AS clause_code, cl.title AS clause_title, cl.legal_ref AS clause_legal_ref
FROM agreement.clauses c
LEFT JOIN platform.clause_library cl ON cl.id = c.clause_id
WHERE c.agreement_id = $1
ORDER BY c.position, c.created_at
`

type ListAgreementClausesRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	AgreementID     uuid.UUID          `db:"agreement_id" json:"agreement_id"`
	ClauseID        pgtype.UUID        `db:"clause_id" json:"clause_id"`
	ClauseVersionNo *int32             `db:"clause_version_no" json:"clause_version_no"`
	Position        int16              `db:"position" json:"position"`
	IsMandatory     bool               `db:"is_mandatory" json:"is_mandatory"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ClauseCode      *string            `db:"clause_code" json:"clause_code"`
	ClauseTitle     *string            `db:"clause_title" json:"clause_title"`
	ClauseLegalRef  *string            `db:"clause_legal_ref" json:"clause_legal_ref"`
}

func (q *Queries) ListAgreementClauses(ctx context.Context, agreementID uuid.UUID) ([]ListAgreementClausesRow, error) {
	rows, err := q.db.Query(ctx, listAgreementClauses, agreementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgreementClausesRow
	for rows.Next() {
		var i ListAgreementClausesRow
		if err := rows.Scan(
			&i.ID,
			&i.AgreementID,
			&i.ClauseID,
			&i.ClauseVersionNo,
			&i.Position,
			&i.IsMandatory,
			&i.RowVersion,
			&i.CreatedAt,
			&i.ClauseCode,
			&i.ClauseTitle,
			&i.ClauseLegalRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMandatoryRules = `-- name: ListMandatoryRules :many
SELECT id, agreement_type, clause_code, legal_ref, condition, created_at, created_by, updated_at, updated_by, row_version FROM agreement.mandatory_rules WHERE agreement_type = $1 ORDER BY clause_code
`

func (q *Queries) ListMandatoryRules(ctx context.Context, agreementType string) ([]AgreementMandatoryRule, error) {
	rows, err := q.db.Query(ctx, listMandatoryRules, agreementType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgreementMandatoryRule
	for rows.Next() {
		var i AgreementMandatoryRule
		if err := rows.Scan(
			&i.ID,
			&i.AgreementType,
			&i.ClauseCode,
			&i.LegalRef,
			&i.Condition,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
