// Package iamhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package iamhttp

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DataScopeScopeType.
const (
	LegalEntity DataScopeScopeType = "legal_entity"
	OrgUnit     DataScopeScopeType = "org_unit"
	Self        DataScopeScopeType = "self"
	Tenant      DataScopeScopeType = "tenant"
)

// Valid indicates whether the value is a known member of the DataScopeScopeType enum.
func (e DataScopeScopeType) Valid() bool {
	switch e {
	case LegalEntity:
		return true
	case OrgUnit:
		return true
	case Self:
		return true
	case Tenant:
		return true
	default:
		return false
	}
}

// Defines values for MeLocale.
const (
	MeLocaleEn MeLocale = "en"
	MeLocaleTh MeLocale = "th"
)

// Valid indicates whether the value is a known member of the MeLocale enum.
func (e MeLocale) Valid() bool {
	switch e {
	case MeLocaleEn:
		return true
	case MeLocaleTh:
		return true
	default:
		return false
	}
}

// Defines values for AcceptLanguage.
const (
	AcceptLanguageEn AcceptLanguage = "en"
	AcceptLanguageTh AcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the AcceptLanguage enum.
func (e AcceptLanguage) Valid() bool {
	switch e {
	case AcceptLanguageEn:
		return true
	case AcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for IamGetMeParamsAcceptLanguage.
const (
	IamGetMeParamsAcceptLanguageEn IamGetMeParamsAcceptLanguage = "en"
	IamGetMeParamsAcceptLanguageTh IamGetMeParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the IamGetMeParamsAcceptLanguage enum.
func (e IamGetMeParamsAcceptLanguage) Valid() bool {
	switch e {
	case IamGetMeParamsAcceptLanguageEn:
		return true
	case IamGetMeParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// DataScope defines model for DataScope.
type DataScope struct {
	IncludeDescendants *bool              `json:"include_descendants,omitempty"`
	LegalEntityId      *Uuid              `json:"legal_entity_id,omitempty"`
	OrgUnitId          *Uuid              `json:"org_unit_id,omitempty"`
	ScopeType          DataScopeScopeType `json:"scope_type"`
}

// DataScopeScopeType defines model for DataScope.ScopeType.
type DataScopeScopeType string

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string  `json:"code"`
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
}

// Me defines model for Me.
type Me struct {
	DisplayName string  `json:"display_name"`
	EmailMasked *string `json:"email_masked,omitempty"`

	// Id UUIDv7 generated by the API
	Id          Uuid     `json:"id"`
	Locale      MeLocale `json:"locale"`
	MfaEnrolled bool     `json:"mfa_enrolled"`

	// Permissions Effective permission codes (x-permission values)
	Permissions []string    `json:"permissions"`
	Roles       []string    `json:"roles"`
	Scopes      []DataScope `json:"scopes"`
	Tenant      struct {
		Code string `json:"code"`

		// Id UUIDv7 generated by the API
		Id   Uuid   `json:"id"`
		Name string `json:"name"`
	} `json:"tenant"`
}

// MeLocale defines model for Me.Locale.
type MeLocale string

// Problem RFC 9457 problem details with a stable machine-readable `code`
type Problem struct {
	Code      string        `json:"code"`
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// Uuid UUIDv7 generated by the API
type Uuid = openapi_types.UUID

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage string

// Unauthorized RFC 9457 problem details with a stable machine-readable `code`
type Unauthorized = Problem

// IamGetMeParams defines parameters for IamGetMe.
type IamGetMeParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *IamGetMeParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// IamGetMeParamsAcceptLanguage defines parameters for IamGetMe.
type IamGetMeParamsAcceptLanguage string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// IamGetMe Current user, effective permissions and data scopes
	// (GET /admin/v1/me)
	IamGetMe(w http.ResponseWriter, r *http.Request, params IamGetMeParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// IamGetMe Current user, effective permissions and data scopes
// (GET /admin/v1/me)
func (_ Unimplemented) IamGetMe(w http.ResponseWriter, r *http.Request, params IamGetMeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// IamGetMe operation middleware
func (siw *ServerInterfaceWrapper) IamGetMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params IamGetMeParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage IamGetMeParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IamGetMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/me", wrapper.IamGetMe)
	})

	return r
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type IamGetMeRequestObject struct {
	Params IamGetMeParams
}

type IamGetMeResponseObject interface {
	VisitIamGetMeResponse(w http.ResponseWriter) error
}

type IamGetMe200JSONResponse Me

func (response IamGetMe200JSONResponse) VisitIamGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type IamGetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response IamGetMe401ApplicationProblemPlusJSONResponse) VisitIamGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// IamGetMe Current user, effective permissions and data scopes
	// (GET /admin/v1/me)
	IamGetMe(ctx context.Context, request IamGetMeRequestObject) (IamGetMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// IamGetMe operation middleware
func (sh *strictHandler) IamGetMe(w http.ResponseWriter, r *http.Request, params IamGetMeParams) {
	var request IamGetMeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IamGetMe(ctx, request.(IamGetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IamGetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IamGetMeResponseObject); ok {
		if err := validResponse.VisitIamGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
