// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package ropastore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActivityTemplate = `-- name: GetActivityTemplate :one
SELECT id, tenant_id, template_set_id, code, name_th, name_en, job_category, role, defaults, rationale, legal_refs, version_no, row_version
FROM ropa.activity_templates
WHERE id = $1
`

type GetActivityTemplateRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	TenantID      pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	TemplateSetID uuid.UUID   `db:"template_set_id" json:"template_set_id"`
	Code          string      `db:"code" json:"code"`
	NameTh        string      `db:"name_th" json:"name_th"`
	NameEn        *string     `db:"name_en" json:"name_en"`
	JobCategory   string      `db:"job_category" json:"job_category"`
	Role          string      `db:"role" json:"role"`
	Defaults      []byte      `db:"defaults" json:"defaults"`
	Rationale     []byte      `db:"rationale" json:"rationale"`
	LegalRefs     []string    `db:"legal_refs" json:"legal_refs"`
	VersionNo     int32       `db:"version_no" json:"version_no"`
	RowVersion    int32       `db:"row_version" json:"row_version"`
}

func (q *Queries) GetActivityTemplate(ctx context.Context, id uuid.UUID) (GetActivityTemplateRow, error) {
	row := q.db.QueryRow(ctx, getActivityTemplate, id)
	var i GetActivityTemplateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateSetID,
		&i.Code,
		&i.NameTh,
		&i.NameEn,
		&i.JobCategory,
		&i.Role,
		&i.Defaults,
		&i.Rationale,
		&i.LegalRefs,
		&i.VersionNo,
		&i.RowVersion,
	)
	return i, err
}

const listActivityTemplates = `-- name: ListActivityTemplates :many
SELECT id, tenant_id, template_set_id, code, name_th, name_en, job_category, role, defaults, rationale, legal_refs, version_no, row_version
FROM ropa.activity_templates
WHERE template_set_id = $1
  AND ($2::varchar IS NULL OR job_category = $2)
ORDER BY job_category, name_th
`

type ListActivityTemplatesParams struct {
	TemplateSetID uuid.UUID `db:"template_set_id" json:"template_set_id"`
	JobCategory   *string   `db:"job_category" json:"job_category"`
}

type ListActivityTemplatesRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	TenantID      pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	TemplateSetID uuid.UUID   `db:"template_set_id" json:"template_set_id"`
	Code          string      `db:"code" json:"code"`
	NameTh        string      `db:"name_th" json:"name_th"`
	NameEn        *string     `db:"name_en" json:"name_en"`
	JobCategory   string      `db:"job_category" json:"job_category"`
	Role          string      `db:"role" json:"role"`
	Defaults      []byte      `db:"defaults" json:"defaults"`
	Rationale     []byte      `db:"rationale" json:"rationale"`
	LegalRefs     []string    `db:"legal_refs" json:"legal_refs"`
	VersionNo     int32       `db:"version_no" json:"version_no"`
	RowVersion    int32       `db:"row_version" json:"row_version"`
}

func (q *Queries) ListActivityTemplates(ctx context.Context, arg ListActivityTemplatesParams) ([]ListActivityTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listActivityTemplates, arg.TemplateSetID, arg.JobCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityTemplatesRow
	for rows.Next() {
		var i ListActivityTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TemplateSetID,
			&i.Code,
			&i.NameTh,
			&i.NameEn,
			&i.JobCategory,
			&i.Role,
			&i.Defaults,
			&i.Rationale,
			&i.LegalRefs,
			&i.VersionNo,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateSets = `-- name: ListTemplateSets :many
SELECT id, tenant_id, name, set_type, industry, version_no, status, published_at, row_version
FROM ropa.template_sets
WHERE status = 'published'
ORDER BY name
`

type ListTemplateSetsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Name        string             `db:"name" json:"name"`
	SetType     string             `db:"set_type" json:"set_type"`
	Industry    *string            `db:"industry" json:"industry"`
	VersionNo   int32              `db:"version_no" json:"version_no"`
	Status      string             `db:"status" json:"status"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	RowVersion  int32              `db:"row_version" json:"row_version"`
}

// RTG-01: published template sets (global or this tenant's own) — RLS's tenant_read policy already scopes
// this to tenant_id IS NULL OR tenant_id = the caller's tenant, the same ORG-07 master-data pattern.
func (q *Queries) ListTemplateSets(ctx context.Context) ([]ListTemplateSetsRow, error) {
	rows, err := q.db.Query(ctx, listTemplateSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplateSetsRow
	for rows.Next() {
		var i ListTemplateSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.SetType,
			&i.Industry,
			&i.VersionNo,
			&i.Status,
			&i.PublishedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
