// Package versioninghttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package versioninghttp

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApprovalInboxItemDecision.
const (
	ApprovalInboxItemDecisionApproved ApprovalInboxItemDecision = "approved"
	ApprovalInboxItemDecisionPending  ApprovalInboxItemDecision = "pending"
	ApprovalInboxItemDecisionRejected ApprovalInboxItemDecision = "rejected"
	ApprovalInboxItemDecisionReturned ApprovalInboxItemDecision = "returned"
)

// Valid indicates whether the value is a known member of the ApprovalInboxItemDecision enum.
func (e ApprovalInboxItemDecision) Valid() bool {
	switch e {
	case ApprovalInboxItemDecisionApproved:
		return true
	case ApprovalInboxItemDecisionPending:
		return true
	case ApprovalInboxItemDecisionRejected:
		return true
	case ApprovalInboxItemDecisionReturned:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStepDecision.
const (
	ApprovalStepDecisionApproved ApprovalStepDecision = "approved"
	ApprovalStepDecisionPending  ApprovalStepDecision = "pending"
	ApprovalStepDecisionRejected ApprovalStepDecision = "rejected"
	ApprovalStepDecisionReturned ApprovalStepDecision = "returned"
)

// Valid indicates whether the value is a known member of the ApprovalStepDecision enum.
func (e ApprovalStepDecision) Valid() bool {
	switch e {
	case ApprovalStepDecisionApproved:
		return true
	case ApprovalStepDecisionPending:
		return true
	case ApprovalStepDecisionRejected:
		return true
	case ApprovalStepDecisionReturned:
		return true
	default:
		return false
	}
}

// Defines values for FormConditionOp.
const (
	Answered    FormConditionOp = "answered"
	Eq          FormConditionOp = "eq"
	Gt          FormConditionOp = "gt"
	Gte         FormConditionOp = "gte"
	In          FormConditionOp = "in"
	Lt          FormConditionOp = "lt"
	Lte         FormConditionOp = "lte"
	Neq         FormConditionOp = "neq"
	NotAnswered FormConditionOp = "not_answered"
	NotIn       FormConditionOp = "not_in"
)

// Valid indicates whether the value is a known member of the FormConditionOp enum.
func (e FormConditionOp) Valid() bool {
	switch e {
	case Answered:
		return true
	case Eq:
		return true
	case Gt:
		return true
	case Gte:
		return true
	case In:
		return true
	case Lt:
		return true
	case Lte:
		return true
	case Neq:
		return true
	case NotAnswered:
		return true
	case NotIn:
		return true
	default:
		return false
	}
}

// Defines values for RecordVersionStatus.
const (
	RecordVersionStatusApproved   RecordVersionStatus = "approved"
	RecordVersionStatusDraft      RecordVersionStatus = "draft"
	RecordVersionStatusInReview   RecordVersionStatus = "in_review"
	RecordVersionStatusPublished  RecordVersionStatus = "published"
	RecordVersionStatusSuperseded RecordVersionStatus = "superseded"
)

// Valid indicates whether the value is a known member of the RecordVersionStatus enum.
func (e RecordVersionStatus) Valid() bool {
	switch e {
	case RecordVersionStatusApproved:
		return true
	case RecordVersionStatusDraft:
		return true
	case RecordVersionStatusInReview:
		return true
	case RecordVersionStatusPublished:
		return true
	case RecordVersionStatusSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for AcceptLanguage.
const (
	AcceptLanguageEn AcceptLanguage = "en"
	AcceptLanguageTh AcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the AcceptLanguage enum.
func (e AcceptLanguage) Valid() bool {
	switch e {
	case AcceptLanguageEn:
		return true
	case AcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformDecideApprovalParamsAcceptLanguage.
const (
	PlatformDecideApprovalParamsAcceptLanguageEn PlatformDecideApprovalParamsAcceptLanguage = "en"
	PlatformDecideApprovalParamsAcceptLanguageTh PlatformDecideApprovalParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformDecideApprovalParamsAcceptLanguage enum.
func (e PlatformDecideApprovalParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformDecideApprovalParamsAcceptLanguageEn:
		return true
	case PlatformDecideApprovalParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformDecideApprovalJSONBodyDecision.
const (
	PlatformDecideApprovalJSONBodyDecisionApproved PlatformDecideApprovalJSONBodyDecision = "approved"
	PlatformDecideApprovalJSONBodyDecisionRejected PlatformDecideApprovalJSONBodyDecision = "rejected"
	PlatformDecideApprovalJSONBodyDecisionReturned PlatformDecideApprovalJSONBodyDecision = "returned"
)

// Valid indicates whether the value is a known member of the PlatformDecideApprovalJSONBodyDecision enum.
func (e PlatformDecideApprovalJSONBodyDecision) Valid() bool {
	switch e {
	case PlatformDecideApprovalJSONBodyDecisionApproved:
		return true
	case PlatformDecideApprovalJSONBodyDecisionRejected:
		return true
	case PlatformDecideApprovalJSONBodyDecisionReturned:
		return true
	default:
		return false
	}
}

// Defines values for PlatformListMyApprovalsParamsAcceptLanguage.
const (
	PlatformListMyApprovalsParamsAcceptLanguageEn PlatformListMyApprovalsParamsAcceptLanguage = "en"
	PlatformListMyApprovalsParamsAcceptLanguageTh PlatformListMyApprovalsParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformListMyApprovalsParamsAcceptLanguage enum.
func (e PlatformListMyApprovalsParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformListMyApprovalsParamsAcceptLanguageEn:
		return true
	case PlatformListMyApprovalsParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformGetRecordVersionParamsAcceptLanguage.
const (
	PlatformGetRecordVersionParamsAcceptLanguageEn PlatformGetRecordVersionParamsAcceptLanguage = "en"
	PlatformGetRecordVersionParamsAcceptLanguageTh PlatformGetRecordVersionParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformGetRecordVersionParamsAcceptLanguage enum.
func (e PlatformGetRecordVersionParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformGetRecordVersionParamsAcceptLanguageEn:
		return true
	case PlatformGetRecordVersionParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformCompareRecordVersionsParamsAcceptLanguage.
const (
	PlatformCompareRecordVersionsParamsAcceptLanguageEn PlatformCompareRecordVersionsParamsAcceptLanguage = "en"
	PlatformCompareRecordVersionsParamsAcceptLanguageTh PlatformCompareRecordVersionsParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformCompareRecordVersionsParamsAcceptLanguage enum.
func (e PlatformCompareRecordVersionsParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformCompareRecordVersionsParamsAcceptLanguageEn:
		return true
	case PlatformCompareRecordVersionsParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformPublishRecordVersionParamsAcceptLanguage.
const (
	PlatformPublishRecordVersionParamsAcceptLanguageEn PlatformPublishRecordVersionParamsAcceptLanguage = "en"
	PlatformPublishRecordVersionParamsAcceptLanguageTh PlatformPublishRecordVersionParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformPublishRecordVersionParamsAcceptLanguage enum.
func (e PlatformPublishRecordVersionParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformPublishRecordVersionParamsAcceptLanguageEn:
		return true
	case PlatformPublishRecordVersionParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformSubmitRecordVersionParamsAcceptLanguage.
const (
	PlatformSubmitRecordVersionParamsAcceptLanguageEn PlatformSubmitRecordVersionParamsAcceptLanguage = "en"
	PlatformSubmitRecordVersionParamsAcceptLanguageTh PlatformSubmitRecordVersionParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformSubmitRecordVersionParamsAcceptLanguage enum.
func (e PlatformSubmitRecordVersionParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformSubmitRecordVersionParamsAcceptLanguageEn:
		return true
	case PlatformSubmitRecordVersionParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformListRecordVersionsParamsAcceptLanguage.
const (
	PlatformListRecordVersionsParamsAcceptLanguageEn PlatformListRecordVersionsParamsAcceptLanguage = "en"
	PlatformListRecordVersionsParamsAcceptLanguageTh PlatformListRecordVersionsParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformListRecordVersionsParamsAcceptLanguage enum.
func (e PlatformListRecordVersionsParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformListRecordVersionsParamsAcceptLanguageEn:
		return true
	case PlatformListRecordVersionsParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// ApprovalInboxItem defines model for ApprovalInboxItem.
type ApprovalInboxItem struct {
	// ApproverId UUIDv7 generated by the API
	ApproverId   *Uuid   `json:"approver_id,omitempty"`
	ApproverName *string `json:"approver_name,omitempty"`
	AuthorName   *string `json:"author_name,omitempty"`

	// DecidedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	DecidedAt *Timestamp                `json:"decided_at,omitempty"`
	Decision  ApprovalInboxItemDecision `json:"decision"`

	// EntityId UUIDv7 generated by the API
	EntityId   Uuid   `json:"entity_id"`
	EntityType string `json:"entity_type"`

	// Id UUIDv7 generated by the API
	Id     Uuid    `json:"id"`
	Reason *string `json:"reason,omitempty"`

	// RequestedBy UUIDv7 generated by the API
	RequestedBy   Uuid    `json:"requested_by"`
	RequesterName *string `json:"requester_name,omitempty"`
	Role          string  `json:"role"`
	RowVersion    int     `json:"row_version"`
	Step          int     `json:"step"`
	Title         *string `json:"title,omitempty"`
	Version       int     `json:"version"`

	// VersionId UUIDv7 generated by the API
	VersionId Uuid `json:"version_id"`
}

// ApprovalInboxItemDecision defines model for ApprovalInboxItem.Decision.
type ApprovalInboxItemDecision string

// ApprovalStep defines model for ApprovalStep.
type ApprovalStep struct {
	// ApproverId UUIDv7 generated by the API
	ApproverId   *Uuid   `json:"approver_id,omitempty"`
	ApproverName *string `json:"approver_name,omitempty"`

	// DecidedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	DecidedAt *Timestamp           `json:"decided_at,omitempty"`
	Decision  ApprovalStepDecision `json:"decision"`

	// Id UUIDv7 generated by the API
	Id     Uuid    `json:"id"`
	Reason *string `json:"reason,omitempty"`

	// RequestedBy UUIDv7 generated by the API
	RequestedBy   Uuid    `json:"requested_by"`
	RequesterName *string `json:"requester_name,omitempty"`
	Role          string  `json:"role"`
	RowVersion    int     `json:"row_version"`
	Step          int     `json:"step"`
}

// ApprovalStepDecision defines model for ApprovalStep.Decision.
type ApprovalStepDecision string

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string  `json:"code"`
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
}

// FormCondition Show when an earlier question's answer compares true (question + op + value), or all/any of nested conditions
type FormCondition struct {
	All      *[]FormCondition `json:"all,omitempty"`
	Any      *[]FormCondition `json:"any,omitempty"`
	Op       *FormConditionOp `json:"op,omitempty"`
	Question *string          `json:"question,omitempty"`
	Value    interface{}      `json:"value,omitempty"`
}

// FormConditionOp defines model for FormCondition.Op.
type FormConditionOp string

// Problem RFC 9457 problem details with a stable machine-readable `code`
type Problem struct {
	Code      string        `json:"code"`
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// RecordVersion defines model for RecordVersion.
type RecordVersion struct {
	Approvals []ApprovalStep `json:"approvals"`

	// AuthorId UUIDv7 generated by the API
	AuthorId   *Uuid   `json:"author_id,omitempty"`
	AuthorName *string `json:"author_name,omitempty"`

	// CreatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	CreatedAt Timestamp `json:"created_at"`

	// Diff Changes against the version published when this one was submitted
	Diff []VersionChange `json:"diff"`

	// EntityId UUIDv7 generated by the API
	EntityId   Uuid   `json:"entity_id"`
	EntityType string `json:"entity_type"`

	// Id UUIDv7 generated by the API
	Id         Uuid                `json:"id"`
	RowVersion int                 `json:"row_version"`
	Snapshot   interface{}         `json:"snapshot"`
	Status     RecordVersionStatus `json:"status"`

	// UpdatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	UpdatedAt Timestamp `json:"updated_at"`
	Version   int       `json:"version"`
}

// RecordVersionStatus defines model for RecordVersion.Status.
type RecordVersionStatus string

// Timestamp RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
type Timestamp = time.Time

// Uuid UUIDv7 generated by the API
type Uuid = openapi_types.UUID

// VersionChange defines model for VersionChange.
type VersionChange struct {
	After  interface{} `json:"after,omitempty"`
	Before interface{} `json:"before,omitempty"`

	// Path JSON path, e.g. `purposes[1]` or `contact.email`; `$` for the whole document
	Path string `json:"path"`
}

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage string

// EntityId UUIDv7 generated by the API
type EntityId = Uuid

// EntityType defines model for EntityType.
type EntityType = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// BadRequest RFC 9457 problem details with a stable machine-readable `code`
type BadRequest = Problem

// Conflict RFC 9457 problem details with a stable machine-readable `code`
type Conflict = Problem

// Forbidden RFC 9457 problem details with a stable machine-readable `code`
type Forbidden = Problem

// NotFound RFC 9457 problem details with a stable machine-readable `code`
type NotFound = Problem

// PreconditionFailed RFC 9457 problem details with a stable machine-readable `code`
type PreconditionFailed = Problem

// PreconditionRequired RFC 9457 problem details with a stable machine-readable `code`
type PreconditionRequired = Problem

// Unauthorized RFC 9457 problem details with a stable machine-readable `code`
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 problem details with a stable machine-readable `code`
type UnprocessableEntity = Problem

// PlatformDecideApprovalJSONBody defines parameters for PlatformDecideApproval.
type PlatformDecideApprovalJSONBody struct {
	Decision PlatformDecideApprovalJSONBodyDecision `json:"decision"`

	// Reason Required to return or reject
	Reason *string `json:"reason,omitempty"`
}

// PlatformDecideApprovalParams defines parameters for PlatformDecideApproval.
type PlatformDecideApprovalParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformDecideApprovalParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// PlatformDecideApprovalParamsAcceptLanguage defines parameters for PlatformDecideApproval.
type PlatformDecideApprovalParamsAcceptLanguage string

// PlatformDecideApprovalJSONBodyDecision defines parameters for PlatformDecideApproval.
type PlatformDecideApprovalJSONBodyDecision string

// PlatformListMyApprovalsParams defines parameters for PlatformListMyApprovals.
type PlatformListMyApprovalsParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformListMyApprovalsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformListMyApprovalsParamsAcceptLanguage defines parameters for PlatformListMyApprovals.
type PlatformListMyApprovalsParamsAcceptLanguage string

// PlatformGetRecordVersionParams defines parameters for PlatformGetRecordVersion.
type PlatformGetRecordVersionParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformGetRecordVersionParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformGetRecordVersionParamsAcceptLanguage defines parameters for PlatformGetRecordVersion.
type PlatformGetRecordVersionParamsAcceptLanguage string

// PlatformCompareRecordVersionsParams defines parameters for PlatformCompareRecordVersions.
type PlatformCompareRecordVersionsParams struct {
	With Uuid `form:"with" json:"with"`

	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformCompareRecordVersionsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformCompareRecordVersionsParamsAcceptLanguage defines parameters for PlatformCompareRecordVersions.
type PlatformCompareRecordVersionsParamsAcceptLanguage string

// PlatformPublishRecordVersionParams defines parameters for PlatformPublishRecordVersion.
type PlatformPublishRecordVersionParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformPublishRecordVersionParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// PlatformPublishRecordVersionParamsAcceptLanguage defines parameters for PlatformPublishRecordVersion.
type PlatformPublishRecordVersionParamsAcceptLanguage string

// PlatformSubmitRecordVersionParams defines parameters for PlatformSubmitRecordVersion.
type PlatformSubmitRecordVersionParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformSubmitRecordVersionParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// PlatformSubmitRecordVersionParamsAcceptLanguage defines parameters for PlatformSubmitRecordVersion.
type PlatformSubmitRecordVersionParamsAcceptLanguage string

// PlatformListRecordVersionsParams defines parameters for PlatformListRecordVersions.
type PlatformListRecordVersionsParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformListRecordVersionsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformListRecordVersionsParamsAcceptLanguage defines parameters for PlatformListRecordVersions.
type PlatformListRecordVersionsParamsAcceptLanguage string

// PlatformDecideApprovalJSONRequestBody defines body for PlatformDecideApproval for application/json ContentType.
type PlatformDecideApprovalJSONRequestBody PlatformDecideApprovalJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PlatformDecideApproval Approve, return or reject the current approval step (maker-checker enforced)
	// (POST /admin/v1/platform/approvals/{id}/decision)
	PlatformDecideApproval(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformDecideApprovalParams)
	// PlatformListMyApprovals Approvals waiting on the caller (their roles, the current level, not their own work)
	// (GET /admin/v1/platform/my-approvals)
	PlatformListMyApprovals(w http.ResponseWriter, r *http.Request, params PlatformListMyApprovalsParams)
	// PlatformGetRecordVersion One version with its snapshot, diff and approval steps
	// (GET /admin/v1/platform/record-versions/{id})
	PlatformGetRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetRecordVersionParams)
	// PlatformCompareRecordVersions Field-by-field changes from this version to another version of the same record
	// (GET /admin/v1/platform/record-versions/{id}/compare)
	PlatformCompareRecordVersions(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformCompareRecordVersionsParams)
	// PlatformPublishRecordVersion Publish an approved version (the previous published version is superseded)
	// (POST /admin/v1/platform/record-versions/{id}/publish)
	PlatformPublishRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformPublishRecordVersionParams)
	// PlatformSubmitRecordVersion Send a draft for approval (opens one step per approval level)
	// (POST /admin/v1/platform/record-versions/{id}/submit)
	PlatformSubmitRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformSubmitRecordVersionParams)
	// PlatformListRecordVersions A record's versions, newest first (PLT-08)
	// (GET /admin/v1/platform/records/{entityType}/{entityId}/versions)
	PlatformListRecordVersions(w http.ResponseWriter, r *http.Request, entityType EntityType, entityId EntityId, params PlatformListRecordVersionsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// PlatformDecideApproval Approve, return or reject the current approval step (maker-checker enforced)
// (POST /admin/v1/platform/approvals/{id}/decision)
func (_ Unimplemented) PlatformDecideApproval(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformDecideApprovalParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformListMyApprovals Approvals waiting on the caller (their roles, the current level, not their own work)
// (GET /admin/v1/platform/my-approvals)
func (_ Unimplemented) PlatformListMyApprovals(w http.ResponseWriter, r *http.Request, params PlatformListMyApprovalsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformGetRecordVersion One version with its snapshot, diff and approval steps
// (GET /admin/v1/platform/record-versions/{id})
func (_ Unimplemented) PlatformGetRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetRecordVersionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformCompareRecordVersions Field-by-field changes from this version to another version of the same record
// (GET /admin/v1/platform/record-versions/{id}/compare)
func (_ Unimplemented) PlatformCompareRecordVersions(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformCompareRecordVersionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformPublishRecordVersion Publish an approved version (the previous published version is superseded)
// (POST /admin/v1/platform/record-versions/{id}/publish)
func (_ Unimplemented) PlatformPublishRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformPublishRecordVersionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformSubmitRecordVersion Send a draft for approval (opens one step per approval level)
// (POST /admin/v1/platform/record-versions/{id}/submit)
func (_ Unimplemented) PlatformSubmitRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformSubmitRecordVersionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformListRecordVersions A record's versions, newest first (PLT-08)
// (GET /admin/v1/platform/records/{entityType}/{entityId}/versions)
func (_ Unimplemented) PlatformListRecordVersions(w http.ResponseWriter, r *http.Request, entityType EntityType, entityId EntityId, params PlatformListRecordVersionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PlatformDecideApproval operation middleware
func (siw *ServerInterfaceWrapper) PlatformDecideApproval(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformDecideApprovalParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformDecideApprovalParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformDecideApproval(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformListMyApprovals operation middleware
func (siw *ServerInterfaceWrapper) PlatformListMyApprovals(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformListMyApprovalsParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformListMyApprovalsParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformListMyApprovals(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformGetRecordVersion operation middleware
func (siw *ServerInterfaceWrapper) PlatformGetRecordVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformGetRecordVersionParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformGetRecordVersionParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformGetRecordVersion(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformCompareRecordVersions operation middleware
func (siw *ServerInterfaceWrapper) PlatformCompareRecordVersions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformCompareRecordVersionsParams

	// ------------- Required query parameter "with" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "with", r.URL.Query(), &params.With, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "with"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "with", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformCompareRecordVersionsParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformCompareRecordVersions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformPublishRecordVersion operation middleware
func (siw *ServerInterfaceWrapper) PlatformPublishRecordVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformPublishRecordVersionParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformPublishRecordVersionParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformPublishRecordVersion(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformSubmitRecordVersion operation middleware
func (siw *ServerInterfaceWrapper) PlatformSubmitRecordVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformSubmitRecordVersionParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformSubmitRecordVersionParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformSubmitRecordVersion(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformListRecordVersions operation middleware
func (siw *ServerInterfaceWrapper) PlatformListRecordVersions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entityType" -------------
	var entityType EntityType

	err = runtime.BindStyledParameterWithOptions("simple", "entityType", chi.URLParam(r, "entityType"), &entityType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityType", Err: err})
		return
	}

	// ------------- Path parameter "entityId" -------------
	var entityId EntityId

	err = runtime.BindStyledParameterWithOptions("simple", "entityId", chi.URLParam(r, "entityId"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformListRecordVersionsParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformListRecordVersionsParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformListRecordVersions(w, r, entityType, entityId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/records/{entityType}/{entityId}/versions", wrapper.PlatformListRecordVersions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/record-versions/{id}", wrapper.PlatformGetRecordVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/record-versions/{id}/compare", wrapper.PlatformCompareRecordVersions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/platform/record-versions/{id}/submit", wrapper.PlatformSubmitRecordVersion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/platform/record-versions/{id}/publish", wrapper.PlatformPublishRecordVersion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/platform/approvals/{id}/decision", wrapper.PlatformDecideApproval)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/my-approvals", wrapper.PlatformListMyApprovals)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type PreconditionFailedApplicationProblemPlusJSONResponse Problem

type PreconditionRequiredApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type PlatformDecideApprovalRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformDecideApprovalParams
	Body   *PlatformDecideApprovalJSONRequestBody
}

type PlatformDecideApprovalResponseObject interface {
	VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error
}

type PlatformDecideApproval200ResponseHeaders struct {
	ETag *string
}

type PlatformDecideApproval200JSONResponse struct {
	Body    RecordVersion
	Headers PlatformDecideApproval200ResponseHeaders
}

func (response PlatformDecideApproval200JSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval400ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval401ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval403ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval404ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval409ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval412ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval422ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDecideApproval428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response PlatformDecideApproval428ApplicationProblemPlusJSONResponse) VisitPlatformDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListMyApprovalsRequestObject struct {
	Params PlatformListMyApprovalsParams
}

type PlatformListMyApprovalsResponseObject interface {
	VisitPlatformListMyApprovalsResponse(w http.ResponseWriter) error
}

type PlatformListMyApprovals200JSONResponse struct {
	Data []ApprovalInboxItem `json:"data"`
}

func (response PlatformListMyApprovals200JSONResponse) VisitPlatformListMyApprovalsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListMyApprovals401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformListMyApprovals401ApplicationProblemPlusJSONResponse) VisitPlatformListMyApprovalsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetRecordVersionRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformGetRecordVersionParams
}

type PlatformGetRecordVersionResponseObject interface {
	VisitPlatformGetRecordVersionResponse(w http.ResponseWriter) error
}

type PlatformGetRecordVersion200ResponseHeaders struct {
	ETag *string
}

type PlatformGetRecordVersion200JSONResponse struct {
	Body    RecordVersion
	Headers PlatformGetRecordVersion200ResponseHeaders
}

func (response PlatformGetRecordVersion200JSONResponse) VisitPlatformGetRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetRecordVersion401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformGetRecordVersion401ApplicationProblemPlusJSONResponse) VisitPlatformGetRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetRecordVersion404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformGetRecordVersion404ApplicationProblemPlusJSONResponse) VisitPlatformGetRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCompareRecordVersionsRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformCompareRecordVersionsParams
}

type PlatformCompareRecordVersionsResponseObject interface {
	VisitPlatformCompareRecordVersionsResponse(w http.ResponseWriter) error
}

type PlatformCompareRecordVersions200JSONResponse struct {
	Changes []VersionChange `json:"changes"`
}

func (response PlatformCompareRecordVersions200JSONResponse) VisitPlatformCompareRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCompareRecordVersions400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PlatformCompareRecordVersions400ApplicationProblemPlusJSONResponse) VisitPlatformCompareRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCompareRecordVersions401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformCompareRecordVersions401ApplicationProblemPlusJSONResponse) VisitPlatformCompareRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCompareRecordVersions404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformCompareRecordVersions404ApplicationProblemPlusJSONResponse) VisitPlatformCompareRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCompareRecordVersions422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response PlatformCompareRecordVersions422ApplicationProblemPlusJSONResponse) VisitPlatformCompareRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPublishRecordVersionRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformPublishRecordVersionParams
}

type PlatformPublishRecordVersionResponseObject interface {
	VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error
}

type PlatformPublishRecordVersion200ResponseHeaders struct {
	ETag *string
}

type PlatformPublishRecordVersion200JSONResponse struct {
	Body    RecordVersion
	Headers PlatformPublishRecordVersion200ResponseHeaders
}

func (response PlatformPublishRecordVersion200JSONResponse) VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPublishRecordVersion401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformPublishRecordVersion401ApplicationProblemPlusJSONResponse) VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPublishRecordVersion403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformPublishRecordVersion403ApplicationProblemPlusJSONResponse) VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPublishRecordVersion404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformPublishRecordVersion404ApplicationProblemPlusJSONResponse) VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPublishRecordVersion409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response PlatformPublishRecordVersion409ApplicationProblemPlusJSONResponse) VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPublishRecordVersion412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response PlatformPublishRecordVersion412ApplicationProblemPlusJSONResponse) VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPublishRecordVersion428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response PlatformPublishRecordVersion428ApplicationProblemPlusJSONResponse) VisitPlatformPublishRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformSubmitRecordVersionRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformSubmitRecordVersionParams
}

type PlatformSubmitRecordVersionResponseObject interface {
	VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error
}

type PlatformSubmitRecordVersion200ResponseHeaders struct {
	ETag *string
}

type PlatformSubmitRecordVersion200JSONResponse struct {
	Body    RecordVersion
	Headers PlatformSubmitRecordVersion200ResponseHeaders
}

func (response PlatformSubmitRecordVersion200JSONResponse) VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformSubmitRecordVersion401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformSubmitRecordVersion401ApplicationProblemPlusJSONResponse) VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformSubmitRecordVersion403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformSubmitRecordVersion403ApplicationProblemPlusJSONResponse) VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformSubmitRecordVersion404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformSubmitRecordVersion404ApplicationProblemPlusJSONResponse) VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformSubmitRecordVersion409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response PlatformSubmitRecordVersion409ApplicationProblemPlusJSONResponse) VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformSubmitRecordVersion412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response PlatformSubmitRecordVersion412ApplicationProblemPlusJSONResponse) VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformSubmitRecordVersion428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response PlatformSubmitRecordVersion428ApplicationProblemPlusJSONResponse) VisitPlatformSubmitRecordVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListRecordVersionsRequestObject struct {
	EntityType EntityType `json:"entityType"`
	EntityId   EntityId   `json:"entityId"`
	Params     PlatformListRecordVersionsParams
}

type PlatformListRecordVersionsResponseObject interface {
	VisitPlatformListRecordVersionsResponse(w http.ResponseWriter) error
}

type PlatformListRecordVersions200JSONResponse struct {
	Data []RecordVersion `json:"data"`
}

func (response PlatformListRecordVersions200JSONResponse) VisitPlatformListRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListRecordVersions400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PlatformListRecordVersions400ApplicationProblemPlusJSONResponse) VisitPlatformListRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListRecordVersions401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformListRecordVersions401ApplicationProblemPlusJSONResponse) VisitPlatformListRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListRecordVersions404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformListRecordVersions404ApplicationProblemPlusJSONResponse) VisitPlatformListRecordVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// PlatformDecideApproval Approve, return or reject the current approval step (maker-checker enforced)
	// (POST /admin/v1/platform/approvals/{id}/decision)
	PlatformDecideApproval(ctx context.Context, request PlatformDecideApprovalRequestObject) (PlatformDecideApprovalResponseObject, error)
	// PlatformListMyApprovals Approvals waiting on the caller (their roles, the current level, not their own work)
	// (GET /admin/v1/platform/my-approvals)
	PlatformListMyApprovals(ctx context.Context, request PlatformListMyApprovalsRequestObject) (PlatformListMyApprovalsResponseObject, error)
	// PlatformGetRecordVersion One version with its snapshot, diff and approval steps
	// (GET /admin/v1/platform/record-versions/{id})
	PlatformGetRecordVersion(ctx context.Context, request PlatformGetRecordVersionRequestObject) (PlatformGetRecordVersionResponseObject, error)
	// PlatformCompareRecordVersions Field-by-field changes from this version to another version of the same record
	// (GET /admin/v1/platform/record-versions/{id}/compare)
	PlatformCompareRecordVersions(ctx context.Context, request PlatformCompareRecordVersionsRequestObject) (PlatformCompareRecordVersionsResponseObject, error)
	// PlatformPublishRecordVersion Publish an approved version (the previous published version is superseded)
	// (POST /admin/v1/platform/record-versions/{id}/publish)
	PlatformPublishRecordVersion(ctx context.Context, request PlatformPublishRecordVersionRequestObject) (PlatformPublishRecordVersionResponseObject, error)
	// PlatformSubmitRecordVersion Send a draft for approval (opens one step per approval level)
	// (POST /admin/v1/platform/record-versions/{id}/submit)
	PlatformSubmitRecordVersion(ctx context.Context, request PlatformSubmitRecordVersionRequestObject) (PlatformSubmitRecordVersionResponseObject, error)
	// PlatformListRecordVersions A record's versions, newest first (PLT-08)
	// (GET /admin/v1/platform/records/{entityType}/{entityId}/versions)
	PlatformListRecordVersions(ctx context.Context, request PlatformListRecordVersionsRequestObject) (PlatformListRecordVersionsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PlatformDecideApproval operation middleware
func (sh *strictHandler) PlatformDecideApproval(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformDecideApprovalParams) {
	var request PlatformDecideApprovalRequestObject

	request.Id = id
	request.Params = params

	var body PlatformDecideApprovalJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformDecideApproval(ctx, request.(PlatformDecideApprovalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformDecideApproval")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformDecideApprovalResponseObject); ok {
		if err := validResponse.VisitPlatformDecideApprovalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformListMyApprovals operation middleware
func (sh *strictHandler) PlatformListMyApprovals(w http.ResponseWriter, r *http.Request, params PlatformListMyApprovalsParams) {
	var request PlatformListMyApprovalsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformListMyApprovals(ctx, request.(PlatformListMyApprovalsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformListMyApprovals")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformListMyApprovalsResponseObject); ok {
		if err := validResponse.VisitPlatformListMyApprovalsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformGetRecordVersion operation middleware
func (sh *strictHandler) PlatformGetRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetRecordVersionParams) {
	var request PlatformGetRecordVersionRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformGetRecordVersion(ctx, request.(PlatformGetRecordVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformGetRecordVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformGetRecordVersionResponseObject); ok {
		if err := validResponse.VisitPlatformGetRecordVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformCompareRecordVersions operation middleware
func (sh *strictHandler) PlatformCompareRecordVersions(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformCompareRecordVersionsParams) {
	var request PlatformCompareRecordVersionsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformCompareRecordVersions(ctx, request.(PlatformCompareRecordVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformCompareRecordVersions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformCompareRecordVersionsResponseObject); ok {
		if err := validResponse.VisitPlatformCompareRecordVersionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformPublishRecordVersion operation middleware
func (sh *strictHandler) PlatformPublishRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformPublishRecordVersionParams) {
	var request PlatformPublishRecordVersionRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformPublishRecordVersion(ctx, request.(PlatformPublishRecordVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformPublishRecordVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformPublishRecordVersionResponseObject); ok {
		if err := validResponse.VisitPlatformPublishRecordVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformSubmitRecordVersion operation middleware
func (sh *strictHandler) PlatformSubmitRecordVersion(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformSubmitRecordVersionParams) {
	var request PlatformSubmitRecordVersionRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformSubmitRecordVersion(ctx, request.(PlatformSubmitRecordVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformSubmitRecordVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformSubmitRecordVersionResponseObject); ok {
		if err := validResponse.VisitPlatformSubmitRecordVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformListRecordVersions operation middleware
func (sh *strictHandler) PlatformListRecordVersions(w http.ResponseWriter, r *http.Request, entityType EntityType, entityId EntityId, params PlatformListRecordVersionsParams) {
	var request PlatformListRecordVersionsRequestObject

	request.EntityType = entityType
	request.EntityId = entityId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformListRecordVersions(ctx, request.(PlatformListRecordVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformListRecordVersions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformListRecordVersionsResponseObject); ok {
		if err := validResponse.VisitPlatformListRecordVersionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
