// Package riskhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package riskhttp

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FormConditionOp.
const (
	Answered    FormConditionOp = "answered"
	Eq          FormConditionOp = "eq"
	Gt          FormConditionOp = "gt"
	Gte         FormConditionOp = "gte"
	In          FormConditionOp = "in"
	Lt          FormConditionOp = "lt"
	Lte         FormConditionOp = "lte"
	Neq         FormConditionOp = "neq"
	NotAnswered FormConditionOp = "not_answered"
	NotIn       FormConditionOp = "not_in"
)

// Valid indicates whether the value is a known member of the FormConditionOp enum.
func (e FormConditionOp) Valid() bool {
	switch e {
	case Answered:
		return true
	case Eq:
		return true
	case Gt:
		return true
	case Gte:
		return true
	case In:
		return true
	case Lt:
		return true
	case Lte:
		return true
	case Neq:
		return true
	case NotAnswered:
		return true
	case NotIn:
		return true
	default:
		return false
	}
}

// Defines values for RiskLevel.
const (
	High     RiskLevel = "high"
	Low      RiskLevel = "low"
	Medium   RiskLevel = "medium"
	VeryHigh RiskLevel = "very_high"
)

// Valid indicates whether the value is a known member of the RiskLevel enum.
func (e RiskLevel) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case VeryHigh:
		return true
	default:
		return false
	}
}

// Defines values for AcceptLanguage.
const (
	AcceptLanguageEn AcceptLanguage = "en"
	AcceptLanguageTh AcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the AcceptLanguage enum.
func (e AcceptLanguage) Valid() bool {
	switch e {
	case AcceptLanguageEn:
		return true
	case AcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for RiskListMatricesParamsAcceptLanguage.
const (
	RiskListMatricesParamsAcceptLanguageEn RiskListMatricesParamsAcceptLanguage = "en"
	RiskListMatricesParamsAcceptLanguageTh RiskListMatricesParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the RiskListMatricesParamsAcceptLanguage enum.
func (e RiskListMatricesParamsAcceptLanguage) Valid() bool {
	switch e {
	case RiskListMatricesParamsAcceptLanguageEn:
		return true
	case RiskListMatricesParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for RiskCreateMatrixParamsAcceptLanguage.
const (
	RiskCreateMatrixParamsAcceptLanguageEn RiskCreateMatrixParamsAcceptLanguage = "en"
	RiskCreateMatrixParamsAcceptLanguageTh RiskCreateMatrixParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the RiskCreateMatrixParamsAcceptLanguage enum.
func (e RiskCreateMatrixParamsAcceptLanguage) Valid() bool {
	switch e {
	case RiskCreateMatrixParamsAcceptLanguageEn:
		return true
	case RiskCreateMatrixParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for RiskDeleteMatrixParamsAcceptLanguage.
const (
	RiskDeleteMatrixParamsAcceptLanguageEn RiskDeleteMatrixParamsAcceptLanguage = "en"
	RiskDeleteMatrixParamsAcceptLanguageTh RiskDeleteMatrixParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the RiskDeleteMatrixParamsAcceptLanguage enum.
func (e RiskDeleteMatrixParamsAcceptLanguage) Valid() bool {
	switch e {
	case RiskDeleteMatrixParamsAcceptLanguageEn:
		return true
	case RiskDeleteMatrixParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for RiskGetMatrixParamsAcceptLanguage.
const (
	RiskGetMatrixParamsAcceptLanguageEn RiskGetMatrixParamsAcceptLanguage = "en"
	RiskGetMatrixParamsAcceptLanguageTh RiskGetMatrixParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the RiskGetMatrixParamsAcceptLanguage enum.
func (e RiskGetMatrixParamsAcceptLanguage) Valid() bool {
	switch e {
	case RiskGetMatrixParamsAcceptLanguageEn:
		return true
	case RiskGetMatrixParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for RiskUpdateMatrixParamsAcceptLanguage.
const (
	RiskUpdateMatrixParamsAcceptLanguageEn RiskUpdateMatrixParamsAcceptLanguage = "en"
	RiskUpdateMatrixParamsAcceptLanguageTh RiskUpdateMatrixParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the RiskUpdateMatrixParamsAcceptLanguage enum.
func (e RiskUpdateMatrixParamsAcceptLanguage) Valid() bool {
	switch e {
	case RiskUpdateMatrixParamsAcceptLanguageEn:
		return true
	case RiskUpdateMatrixParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string  `json:"code"`
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
}

// FormCondition Show when an earlier question's answer compares true (question + op + value), or all/any of nested conditions
type FormCondition struct {
	All      *[]FormCondition `json:"all,omitempty"`
	Any      *[]FormCondition `json:"any,omitempty"`
	Op       *FormConditionOp `json:"op,omitempty"`
	Question *string          `json:"question,omitempty"`
	Value    interface{}      `json:"value,omitempty"`
}

// FormConditionOp defines model for FormCondition.Op.
type FormConditionOp string

// Problem RFC 9457 problem details with a stable machine-readable `code`
type Problem struct {
	Code      string        `json:"code"`
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// RiskLevel risk.activity_scores.level's own CHECK constraint — the only four values any matrix may ever classify a score into
type RiskLevel string

// RiskMatrix defines model for RiskMatrix.
type RiskMatrix struct {
	// Id UUIDv7 generated by the API
	Id               Uuid            `json:"id"`
	ImpactLevels     []string        `json:"impact_levels"`
	IsDefault        bool            `json:"is_default"`
	LikelihoodLevels []string        `json:"likelihood_levels"`
	Name             string          `json:"name"`
	RowVersion       int             `json:"row_version"`
	Thresholds       []RiskThreshold `json:"thresholds"`
}

// RiskMatrixInput defines model for RiskMatrixInput.
type RiskMatrixInput struct {
	ImpactLevels []string `json:"impact_levels"`

	// IsDefault At most one matrix per tenant may be the default — setting this clears the flag on every other one in the same request
	IsDefault *bool `json:"is_default,omitempty"`

	// LikelihoodLevels Labels from lowest to highest likelihood, e.g. 5 entries for a 5x5 matrix
	LikelihoodLevels []string        `json:"likelihood_levels"`
	Name             string          `json:"name"`
	Thresholds       []RiskThreshold `json:"thresholds"`
}

// RiskThreshold defines model for RiskThreshold.
type RiskThreshold struct {
	// Level risk.activity_scores.level's own CHECK constraint — the only four values any matrix may ever classify a score into
	Level RiskLevel `json:"level"`

	// MinScore The score (likelihood x impact) at and above which this level applies
	MinScore float32 `json:"min_score"`
}

// Uuid UUIDv7 generated by the API
type Uuid = openapi_types.UUID

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage string

// IfMatch defines model for IfMatch.
type IfMatch = string

// BadRequest RFC 9457 problem details with a stable machine-readable `code`
type BadRequest = Problem

// Forbidden RFC 9457 problem details with a stable machine-readable `code`
type Forbidden = Problem

// NotFound RFC 9457 problem details with a stable machine-readable `code`
type NotFound = Problem

// PreconditionFailed RFC 9457 problem details with a stable machine-readable `code`
type PreconditionFailed = Problem

// PreconditionRequired RFC 9457 problem details with a stable machine-readable `code`
type PreconditionRequired = Problem

// Unauthorized RFC 9457 problem details with a stable machine-readable `code`
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 problem details with a stable machine-readable `code`
type UnprocessableEntity = Problem

// RiskListMatricesParams defines parameters for RiskListMatrices.
type RiskListMatricesParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *RiskListMatricesParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// RiskListMatricesParamsAcceptLanguage defines parameters for RiskListMatrices.
type RiskListMatricesParamsAcceptLanguage string

// RiskCreateMatrixParams defines parameters for RiskCreateMatrix.
type RiskCreateMatrixParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *RiskCreateMatrixParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// RiskCreateMatrixParamsAcceptLanguage defines parameters for RiskCreateMatrix.
type RiskCreateMatrixParamsAcceptLanguage string

// RiskDeleteMatrixParams defines parameters for RiskDeleteMatrix.
type RiskDeleteMatrixParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *RiskDeleteMatrixParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// RiskDeleteMatrixParamsAcceptLanguage defines parameters for RiskDeleteMatrix.
type RiskDeleteMatrixParamsAcceptLanguage string

// RiskGetMatrixParams defines parameters for RiskGetMatrix.
type RiskGetMatrixParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *RiskGetMatrixParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// RiskGetMatrixParamsAcceptLanguage defines parameters for RiskGetMatrix.
type RiskGetMatrixParamsAcceptLanguage string

// RiskUpdateMatrixParams defines parameters for RiskUpdateMatrix.
type RiskUpdateMatrixParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *RiskUpdateMatrixParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// RiskUpdateMatrixParamsAcceptLanguage defines parameters for RiskUpdateMatrix.
type RiskUpdateMatrixParamsAcceptLanguage string

// RiskCreateMatrixJSONRequestBody defines body for RiskCreateMatrix for application/json ContentType.
type RiskCreateMatrixJSONRequestBody = RiskMatrixInput

// RiskUpdateMatrixJSONRequestBody defines body for RiskUpdateMatrix for application/json ContentType.
type RiskUpdateMatrixJSONRequestBody = RiskMatrixInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// RiskListMatrices The tenant's own likelihood x impact risk matrices, default first (RRA-02)
	// (GET /admin/v1/risk/matrices)
	RiskListMatrices(w http.ResponseWriter, r *http.Request, params RiskListMatricesParams)
	// RiskCreateMatrix Create a risk matrix
	// (POST /admin/v1/risk/matrices)
	RiskCreateMatrix(w http.ResponseWriter, r *http.Request, params RiskCreateMatrixParams)
	// RiskDeleteMatrix Remove a risk matrix (If-Match = its own ETag)
	// (DELETE /admin/v1/risk/matrices/{id})
	RiskDeleteMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskDeleteMatrixParams)
	// RiskGetMatrix One risk matrix
	// (GET /admin/v1/risk/matrices/{id})
	RiskGetMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskGetMatrixParams)
	// RiskUpdateMatrix Change a risk matrix's own levels, thresholds or default flag — the acceptance criterion itself (RRA-02), since Classify always reads the current row live, never a cached score
	// (PUT /admin/v1/risk/matrices/{id})
	RiskUpdateMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskUpdateMatrixParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// RiskListMatrices The tenant's own likelihood x impact risk matrices, default first (RRA-02)
// (GET /admin/v1/risk/matrices)
func (_ Unimplemented) RiskListMatrices(w http.ResponseWriter, r *http.Request, params RiskListMatricesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RiskCreateMatrix Create a risk matrix
// (POST /admin/v1/risk/matrices)
func (_ Unimplemented) RiskCreateMatrix(w http.ResponseWriter, r *http.Request, params RiskCreateMatrixParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RiskDeleteMatrix Remove a risk matrix (If-Match = its own ETag)
// (DELETE /admin/v1/risk/matrices/{id})
func (_ Unimplemented) RiskDeleteMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskDeleteMatrixParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RiskGetMatrix One risk matrix
// (GET /admin/v1/risk/matrices/{id})
func (_ Unimplemented) RiskGetMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskGetMatrixParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RiskUpdateMatrix Change a risk matrix's own levels, thresholds or default flag — the acceptance criterion itself (RRA-02), since Classify always reads the current row live, never a cached score
// (PUT /admin/v1/risk/matrices/{id})
func (_ Unimplemented) RiskUpdateMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskUpdateMatrixParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RiskListMatrices operation middleware
func (siw *ServerInterfaceWrapper) RiskListMatrices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RiskListMatricesParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage RiskListMatricesParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RiskListMatrices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RiskCreateMatrix operation middleware
func (siw *ServerInterfaceWrapper) RiskCreateMatrix(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RiskCreateMatrixParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage RiskCreateMatrixParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RiskCreateMatrix(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RiskDeleteMatrix operation middleware
func (siw *ServerInterfaceWrapper) RiskDeleteMatrix(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RiskDeleteMatrixParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage RiskDeleteMatrixParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RiskDeleteMatrix(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RiskGetMatrix operation middleware
func (siw *ServerInterfaceWrapper) RiskGetMatrix(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RiskGetMatrixParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage RiskGetMatrixParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RiskGetMatrix(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RiskUpdateMatrix operation middleware
func (siw *ServerInterfaceWrapper) RiskUpdateMatrix(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RiskUpdateMatrixParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage RiskUpdateMatrixParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RiskUpdateMatrix(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/risk/matrices", wrapper.RiskListMatrices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/risk/matrices", wrapper.RiskCreateMatrix)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/v1/risk/matrices/{id}", wrapper.RiskDeleteMatrix)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/risk/matrices/{id}", wrapper.RiskGetMatrix)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/v1/risk/matrices/{id}", wrapper.RiskUpdateMatrix)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type PreconditionFailedApplicationProblemPlusJSONResponse Problem

type PreconditionRequiredApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type RiskListMatricesRequestObject struct {
	Params RiskListMatricesParams
}

type RiskListMatricesResponseObject interface {
	VisitRiskListMatricesResponse(w http.ResponseWriter) error
}

type RiskListMatrices200JSONResponse struct {
	Data []RiskMatrix `json:"data"`
}

func (response RiskListMatrices200JSONResponse) VisitRiskListMatricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RiskListMatrices401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RiskListMatrices401ApplicationProblemPlusJSONResponse) VisitRiskListMatricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RiskListMatrices403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RiskListMatrices403ApplicationProblemPlusJSONResponse) VisitRiskListMatricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RiskCreateMatrixRequestObject struct {
	Params RiskCreateMatrixParams
	Body   *RiskCreateMatrixJSONRequestBody
}

type RiskCreateMatrixResponseObject interface {
	VisitRiskCreateMatrixResponse(w http.ResponseWriter) error
}

type RiskCreateMatrix201ResponseHeaders struct {
	ETag *string
}

type RiskCreateMatrix201JSONResponse struct {
	Body    RiskMatrix
	Headers RiskCreateMatrix201ResponseHeaders
}

func (response RiskCreateMatrix201JSONResponse) VisitRiskCreateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RiskCreateMatrix400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response RiskCreateMatrix400ApplicationProblemPlusJSONResponse) VisitRiskCreateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RiskCreateMatrix401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RiskCreateMatrix401ApplicationProblemPlusJSONResponse) VisitRiskCreateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RiskCreateMatrix403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RiskCreateMatrix403ApplicationProblemPlusJSONResponse) VisitRiskCreateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RiskCreateMatrix422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response RiskCreateMatrix422ApplicationProblemPlusJSONResponse) VisitRiskCreateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RiskDeleteMatrixRequestObject struct {
	Id     Uuid `json:"id"`
	Params RiskDeleteMatrixParams
}

type RiskDeleteMatrixResponseObject interface {
	VisitRiskDeleteMatrixResponse(w http.ResponseWriter) error
}

type RiskDeleteMatrix204Response struct {
}

func (response RiskDeleteMatrix204Response) VisitRiskDeleteMatrixResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RiskDeleteMatrix401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RiskDeleteMatrix401ApplicationProblemPlusJSONResponse) VisitRiskDeleteMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RiskDeleteMatrix403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RiskDeleteMatrix403ApplicationProblemPlusJSONResponse) VisitRiskDeleteMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RiskDeleteMatrix404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response RiskDeleteMatrix404ApplicationProblemPlusJSONResponse) VisitRiskDeleteMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RiskDeleteMatrix412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response RiskDeleteMatrix412ApplicationProblemPlusJSONResponse) VisitRiskDeleteMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type RiskDeleteMatrix428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response RiskDeleteMatrix428ApplicationProblemPlusJSONResponse) VisitRiskDeleteMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type RiskGetMatrixRequestObject struct {
	Id     Uuid `json:"id"`
	Params RiskGetMatrixParams
}

type RiskGetMatrixResponseObject interface {
	VisitRiskGetMatrixResponse(w http.ResponseWriter) error
}

type RiskGetMatrix200ResponseHeaders struct {
	ETag *string
}

type RiskGetMatrix200JSONResponse struct {
	Body    RiskMatrix
	Headers RiskGetMatrix200ResponseHeaders
}

func (response RiskGetMatrix200JSONResponse) VisitRiskGetMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RiskGetMatrix401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RiskGetMatrix401ApplicationProblemPlusJSONResponse) VisitRiskGetMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RiskGetMatrix403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RiskGetMatrix403ApplicationProblemPlusJSONResponse) VisitRiskGetMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RiskGetMatrix404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response RiskGetMatrix404ApplicationProblemPlusJSONResponse) VisitRiskGetMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrixRequestObject struct {
	Id     Uuid `json:"id"`
	Params RiskUpdateMatrixParams
	Body   *RiskUpdateMatrixJSONRequestBody
}

type RiskUpdateMatrixResponseObject interface {
	VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error
}

type RiskUpdateMatrix200ResponseHeaders struct {
	ETag *string
}

type RiskUpdateMatrix200JSONResponse struct {
	Body    RiskMatrix
	Headers RiskUpdateMatrix200ResponseHeaders
}

func (response RiskUpdateMatrix200JSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrix400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response RiskUpdateMatrix400ApplicationProblemPlusJSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrix401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RiskUpdateMatrix401ApplicationProblemPlusJSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrix403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RiskUpdateMatrix403ApplicationProblemPlusJSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrix404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response RiskUpdateMatrix404ApplicationProblemPlusJSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrix412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response RiskUpdateMatrix412ApplicationProblemPlusJSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrix422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response RiskUpdateMatrix422ApplicationProblemPlusJSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RiskUpdateMatrix428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response RiskUpdateMatrix428ApplicationProblemPlusJSONResponse) VisitRiskUpdateMatrixResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// RiskListMatrices The tenant's own likelihood x impact risk matrices, default first (RRA-02)
	// (GET /admin/v1/risk/matrices)
	RiskListMatrices(ctx context.Context, request RiskListMatricesRequestObject) (RiskListMatricesResponseObject, error)
	// RiskCreateMatrix Create a risk matrix
	// (POST /admin/v1/risk/matrices)
	RiskCreateMatrix(ctx context.Context, request RiskCreateMatrixRequestObject) (RiskCreateMatrixResponseObject, error)
	// RiskDeleteMatrix Remove a risk matrix (If-Match = its own ETag)
	// (DELETE /admin/v1/risk/matrices/{id})
	RiskDeleteMatrix(ctx context.Context, request RiskDeleteMatrixRequestObject) (RiskDeleteMatrixResponseObject, error)
	// RiskGetMatrix One risk matrix
	// (GET /admin/v1/risk/matrices/{id})
	RiskGetMatrix(ctx context.Context, request RiskGetMatrixRequestObject) (RiskGetMatrixResponseObject, error)
	// RiskUpdateMatrix Change a risk matrix's own levels, thresholds or default flag — the acceptance criterion itself (RRA-02), since Classify always reads the current row live, never a cached score
	// (PUT /admin/v1/risk/matrices/{id})
	RiskUpdateMatrix(ctx context.Context, request RiskUpdateMatrixRequestObject) (RiskUpdateMatrixResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RiskListMatrices operation middleware
func (sh *strictHandler) RiskListMatrices(w http.ResponseWriter, r *http.Request, params RiskListMatricesParams) {
	var request RiskListMatricesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RiskListMatrices(ctx, request.(RiskListMatricesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RiskListMatrices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RiskListMatricesResponseObject); ok {
		if err := validResponse.VisitRiskListMatricesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RiskCreateMatrix operation middleware
func (sh *strictHandler) RiskCreateMatrix(w http.ResponseWriter, r *http.Request, params RiskCreateMatrixParams) {
	var request RiskCreateMatrixRequestObject

	request.Params = params

	var body RiskCreateMatrixJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RiskCreateMatrix(ctx, request.(RiskCreateMatrixRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RiskCreateMatrix")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RiskCreateMatrixResponseObject); ok {
		if err := validResponse.VisitRiskCreateMatrixResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RiskDeleteMatrix operation middleware
func (sh *strictHandler) RiskDeleteMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskDeleteMatrixParams) {
	var request RiskDeleteMatrixRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RiskDeleteMatrix(ctx, request.(RiskDeleteMatrixRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RiskDeleteMatrix")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RiskDeleteMatrixResponseObject); ok {
		if err := validResponse.VisitRiskDeleteMatrixResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RiskGetMatrix operation middleware
func (sh *strictHandler) RiskGetMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskGetMatrixParams) {
	var request RiskGetMatrixRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RiskGetMatrix(ctx, request.(RiskGetMatrixRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RiskGetMatrix")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RiskGetMatrixResponseObject); ok {
		if err := validResponse.VisitRiskGetMatrixResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RiskUpdateMatrix operation middleware
func (sh *strictHandler) RiskUpdateMatrix(w http.ResponseWriter, r *http.Request, id Uuid, params RiskUpdateMatrixParams) {
	var request RiskUpdateMatrixRequestObject

	request.Id = id
	request.Params = params

	var body RiskUpdateMatrixJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RiskUpdateMatrix(ctx, request.(RiskUpdateMatrixRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RiskUpdateMatrix")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RiskUpdateMatrixResponseObject); ok {
		if err := validResponse.VisitRiskUpdateMatrixResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
