// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package formsstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeAssignment = `-- name: CompleteAssignment :execrows
UPDATE platform.form_section_assignments
SET status = 'done', completed_at = now(), row_version = row_version + 1, updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE submission_id = $1 AND section_key = $2 AND assignee_user_id = $3 AND status = 'open'
`

type CompleteAssignmentParams struct {
	SubmissionID   uuid.UUID `db:"submission_id" json:"submission_id"`
	SectionKey     string    `db:"section_key" json:"section_key"`
	AssigneeUserID uuid.UUID `db:"assignee_user_id" json:"assignee_user_id"`
}

func (q *Queries) CompleteAssignment(ctx context.Context, arg CompleteAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAssignment, arg.SubmissionID, arg.SectionKey, arg.AssigneeUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAssignment = `-- name: DeleteAssignment :execrows
DELETE FROM platform.form_section_assignments WHERE submission_id = $1 AND section_key = $2 AND status = 'open'
`

type DeleteAssignmentParams struct {
	SubmissionID uuid.UUID `db:"submission_id" json:"submission_id"`
	SectionKey   string    `db:"section_key" json:"section_key"`
}

func (q *Queries) DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignment, arg.SubmissionID, arg.SectionKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const draftFormVersion = `-- name: DraftFormVersion :one
SELECT id, form_id, version_no, schema, scoring, languages, published_at, published_by, row_version, updated_at
FROM platform.form_versions WHERE form_id = $1 AND published_at IS NULL FOR UPDATE
`

type DraftFormVersionRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	FormID      uuid.UUID          `db:"form_id" json:"form_id"`
	VersionNo   int32              `db:"version_no" json:"version_no"`
	Schema      []byte             `db:"schema" json:"schema"`
	Scoring     []byte             `db:"scoring" json:"scoring"`
	Languages   []string           `db:"languages" json:"languages"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	PublishedBy pgtype.UUID        `db:"published_by" json:"published_by"`
	RowVersion  int32              `db:"row_version" json:"row_version"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) DraftFormVersion(ctx context.Context, formID uuid.UUID) (DraftFormVersionRow, error) {
	row := q.db.QueryRow(ctx, draftFormVersion, formID)
	var i DraftFormVersionRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNo,
		&i.Schema,
		&i.Scoring,
		&i.Languages,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getForm = `-- name: GetForm :one
SELECT id, tenant_id, code, name, form_type, status, current_version_id, row_version, updated_at
FROM platform.form_definitions WHERE id = $1
`

type GetFormRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Code             string             `db:"code" json:"code"`
	Name             string             `db:"name" json:"name"`
	FormType         string             `db:"form_type" json:"form_type"`
	Status           string             `db:"status" json:"status"`
	CurrentVersionID pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	RowVersion       int32              `db:"row_version" json:"row_version"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetForm(ctx context.Context, id uuid.UUID) (GetFormRow, error) {
	row := q.db.QueryRow(ctx, getForm, id)
	var i GetFormRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FormType,
		&i.Status,
		&i.CurrentVersionID,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormVersion = `-- name: GetFormVersion :one
SELECT id, form_id, version_no, schema, scoring, languages, published_at, published_by, row_version, updated_at
FROM platform.form_versions WHERE id = $1
`

type GetFormVersionRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	FormID      uuid.UUID          `db:"form_id" json:"form_id"`
	VersionNo   int32              `db:"version_no" json:"version_no"`
	Schema      []byte             `db:"schema" json:"schema"`
	Scoring     []byte             `db:"scoring" json:"scoring"`
	Languages   []string           `db:"languages" json:"languages"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	PublishedBy pgtype.UUID        `db:"published_by" json:"published_by"`
	RowVersion  int32              `db:"row_version" json:"row_version"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetFormVersion(ctx context.Context, id uuid.UUID) (GetFormVersionRow, error) {
	row := q.db.QueryRow(ctx, getFormVersion, id)
	var i GetFormVersionRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNo,
		&i.Schema,
		&i.Scoring,
		&i.Languages,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, form_version_id, entity_type, entity_id, submitted_by_type, submitted_by, answers, status, score, result, submitted_at, row_version, created_at, updated_at
FROM platform.form_submissions WHERE id = $1
`

type GetSubmissionRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	FormVersionID   uuid.UUID          `db:"form_version_id" json:"form_version_id"`
	EntityType      *string            `db:"entity_type" json:"entity_type"`
	EntityID        pgtype.UUID        `db:"entity_id" json:"entity_id"`
	SubmittedByType string             `db:"submitted_by_type" json:"submitted_by_type"`
	SubmittedBy     pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	Answers         []byte             `db:"answers" json:"answers"`
	Status          string             `db:"status" json:"status"`
	Score           pgtype.Numeric     `db:"score" json:"score"`
	Result          []byte             `db:"result" json:"result"`
	SubmittedAt     pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (GetSubmissionRow, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i GetSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.FormVersionID,
		&i.EntityType,
		&i.EntityID,
		&i.SubmittedByType,
		&i.SubmittedBy,
		&i.Answers,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.SubmittedAt,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertForm = `-- name: InsertForm :one
INSERT INTO platform.form_definitions (id, tenant_id, code, name, form_type, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, tenant_id, code, name, form_type, status, current_version_id, row_version, updated_at
`

type InsertFormParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Code     string    `db:"code" json:"code"`
	Name     string    `db:"name" json:"name"`
	FormType string    `db:"form_type" json:"form_type"`
}

type InsertFormRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Code             string             `db:"code" json:"code"`
	Name             string             `db:"name" json:"name"`
	FormType         string             `db:"form_type" json:"form_type"`
	Status           string             `db:"status" json:"status"`
	CurrentVersionID pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	RowVersion       int32              `db:"row_version" json:"row_version"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertForm(ctx context.Context, arg InsertFormParams) (InsertFormRow, error) {
	row := q.db.QueryRow(ctx, insertForm,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.FormType,
	)
	var i InsertFormRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FormType,
		&i.Status,
		&i.CurrentVersionID,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFormVersion = `-- name: InsertFormVersion :one
INSERT INTO platform.form_versions (id, tenant_id, form_id, version_no, schema, scoring, languages, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2,
        (SELECT COALESCE(max(version_no), 0) + 1 FROM platform.form_versions WHERE form_id = $2), $3, $4, $5,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, form_id, version_no, schema, scoring, languages, published_at, published_by, row_version, updated_at
`

type InsertFormVersionParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	FormID    uuid.UUID `db:"form_id" json:"form_id"`
	Schema    []byte    `db:"schema" json:"schema"`
	Scoring   []byte    `db:"scoring" json:"scoring"`
	Languages []string  `db:"languages" json:"languages"`
}

type InsertFormVersionRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	FormID      uuid.UUID          `db:"form_id" json:"form_id"`
	VersionNo   int32              `db:"version_no" json:"version_no"`
	Schema      []byte             `db:"schema" json:"schema"`
	Scoring     []byte             `db:"scoring" json:"scoring"`
	Languages   []string           `db:"languages" json:"languages"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	PublishedBy pgtype.UUID        `db:"published_by" json:"published_by"`
	RowVersion  int32              `db:"row_version" json:"row_version"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertFormVersion(ctx context.Context, arg InsertFormVersionParams) (InsertFormVersionRow, error) {
	row := q.db.QueryRow(ctx, insertFormVersion,
		arg.ID,
		arg.FormID,
		arg.Schema,
		arg.Scoring,
		arg.Languages,
	)
	var i InsertFormVersionRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNo,
		&i.Schema,
		&i.Scoring,
		&i.Languages,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSubmission = `-- name: InsertSubmission :one
INSERT INTO platform.form_submissions (id, tenant_id, form_version_id, entity_type, entity_id, submitted_by_type, submitted_by, answers, status, score, result, submitted_at, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, form_version_id, entity_type, entity_id, submitted_by_type, submitted_by, answers, status, score, result, submitted_at, row_version, created_at, updated_at
`

type InsertSubmissionParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	FormVersionID   uuid.UUID          `db:"form_version_id" json:"form_version_id"`
	EntityType      *string            `db:"entity_type" json:"entity_type"`
	EntityID        pgtype.UUID        `db:"entity_id" json:"entity_id"`
	SubmittedByType string             `db:"submitted_by_type" json:"submitted_by_type"`
	SubmittedBy     pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	Answers         []byte             `db:"answers" json:"answers"`
	Status          string             `db:"status" json:"status"`
	Score           pgtype.Numeric     `db:"score" json:"score"`
	Result          []byte             `db:"result" json:"result"`
	SubmittedAt     pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
}

type InsertSubmissionRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	FormVersionID   uuid.UUID          `db:"form_version_id" json:"form_version_id"`
	EntityType      *string            `db:"entity_type" json:"entity_type"`
	EntityID        pgtype.UUID        `db:"entity_id" json:"entity_id"`
	SubmittedByType string             `db:"submitted_by_type" json:"submitted_by_type"`
	SubmittedBy     pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	Answers         []byte             `db:"answers" json:"answers"`
	Status          string             `db:"status" json:"status"`
	Score           pgtype.Numeric     `db:"score" json:"score"`
	Result          []byte             `db:"result" json:"result"`
	SubmittedAt     pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertSubmission(ctx context.Context, arg InsertSubmissionParams) (InsertSubmissionRow, error) {
	row := q.db.QueryRow(ctx, insertSubmission,
		arg.ID,
		arg.FormVersionID,
		arg.EntityType,
		arg.EntityID,
		arg.SubmittedByType,
		arg.SubmittedBy,
		arg.Answers,
		arg.Status,
		arg.Score,
		arg.Result,
		arg.SubmittedAt,
	)
	var i InsertSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.FormVersionID,
		&i.EntityType,
		&i.EntityID,
		&i.SubmittedByType,
		&i.SubmittedBy,
		&i.Answers,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.SubmittedAt,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignments = `-- name: ListAssignments :many
SELECT id, submission_id, section_key, assignee_user_id, status, completed_at, row_version
FROM platform.form_section_assignments WHERE submission_id = $1 ORDER BY created_at, section_key
`

type ListAssignmentsRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	SubmissionID   uuid.UUID          `db:"submission_id" json:"submission_id"`
	SectionKey     string             `db:"section_key" json:"section_key"`
	AssigneeUserID uuid.UUID          `db:"assignee_user_id" json:"assignee_user_id"`
	Status         string             `db:"status" json:"status"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	RowVersion     int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) ListAssignments(ctx context.Context, submissionID uuid.UUID) ([]ListAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAssignments, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsRow
	for rows.Next() {
		var i ListAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.SectionKey,
			&i.AssigneeUserID,
			&i.Status,
			&i.CompletedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormVersions = `-- name: ListFormVersions :many
SELECT id, form_id, version_no, schema, scoring, languages, published_at, published_by, row_version, updated_at
FROM platform.form_versions WHERE form_id = $1 ORDER BY version_no DESC
`

type ListFormVersionsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	FormID      uuid.UUID          `db:"form_id" json:"form_id"`
	VersionNo   int32              `db:"version_no" json:"version_no"`
	Schema      []byte             `db:"schema" json:"schema"`
	Scoring     []byte             `db:"scoring" json:"scoring"`
	Languages   []string           `db:"languages" json:"languages"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	PublishedBy pgtype.UUID        `db:"published_by" json:"published_by"`
	RowVersion  int32              `db:"row_version" json:"row_version"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListFormVersions(ctx context.Context, formID uuid.UUID) ([]ListFormVersionsRow, error) {
	rows, err := q.db.Query(ctx, listFormVersions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormVersionsRow
	for rows.Next() {
		var i ListFormVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.VersionNo,
			&i.Schema,
			&i.Scoring,
			&i.Languages,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.RowVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForms = `-- name: ListForms :many

SELECT d.id, d.tenant_id, d.code, d.name, d.form_type, d.status, d.current_version_id, d.row_version, d.updated_at,
       (SELECT max(v.version_no) FROM platform.form_versions v WHERE v.form_id = d.id)::int AS latest_version
FROM platform.form_definitions d
WHERE d.form_type = ANY ($1::text[])
ORDER BY d.form_type, d.name
`

type ListFormsRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Code             string             `db:"code" json:"code"`
	Name             string             `db:"name" json:"name"`
	FormType         string             `db:"form_type" json:"form_type"`
	Status           string             `db:"status" json:"status"`
	CurrentVersionID pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	RowVersion       int32              `db:"row_version" json:"row_version"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LatestVersion    int32              `db:"latest_version" json:"latest_version"`
}

// PLT-06 form & assessment engine.
func (q *Queries) ListForms(ctx context.Context, types []string) ([]ListFormsRow, error) {
	rows, err := q.db.Query(ctx, listForms, types)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsRow
	for rows.Next() {
		var i ListFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.FormType,
			&i.Status,
			&i.CurrentVersionID,
			&i.RowVersion,
			&i.UpdatedAt,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponses = `-- name: ListResponses :many
SELECT s.id, s.form_version_id, s.entity_type, s.entity_id, s.submitted_by_type, s.submitted_by, s.answers, s.status, s.score, s.result, s.submitted_at, s.row_version, s.created_at, s.updated_at
FROM platform.form_submissions s JOIN platform.form_versions v ON v.id = s.form_version_id
WHERE v.form_id = $1
ORDER BY s.created_at DESC
LIMIT 200
`

type ListResponsesRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	FormVersionID   uuid.UUID          `db:"form_version_id" json:"form_version_id"`
	EntityType      *string            `db:"entity_type" json:"entity_type"`
	EntityID        pgtype.UUID        `db:"entity_id" json:"entity_id"`
	SubmittedByType string             `db:"submitted_by_type" json:"submitted_by_type"`
	SubmittedBy     pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	Answers         []byte             `db:"answers" json:"answers"`
	Status          string             `db:"status" json:"status"`
	Score           pgtype.Numeric     `db:"score" json:"score"`
	Result          []byte             `db:"result" json:"result"`
	SubmittedAt     pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Responses to a form's versions, newest first.
func (q *Queries) ListResponses(ctx context.Context, formID uuid.UUID) ([]ListResponsesRow, error) {
	rows, err := q.db.Query(ctx, listResponses, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResponsesRow
	for rows.Next() {
		var i ListResponsesRow
		if err := rows.Scan(
			&i.ID,
			&i.FormVersionID,
			&i.EntityType,
			&i.EntityID,
			&i.SubmittedByType,
			&i.SubmittedBy,
			&i.Answers,
			&i.Status,
			&i.Score,
			&i.Result,
			&i.SubmittedAt,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockForm = `-- name: LockForm :one
SELECT id, tenant_id, code, name, form_type, status, current_version_id, row_version, updated_at
FROM platform.form_definitions WHERE id = $1 FOR UPDATE
`

type LockFormRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Code             string             `db:"code" json:"code"`
	Name             string             `db:"name" json:"name"`
	FormType         string             `db:"form_type" json:"form_type"`
	Status           string             `db:"status" json:"status"`
	CurrentVersionID pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	RowVersion       int32              `db:"row_version" json:"row_version"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockForm(ctx context.Context, id uuid.UUID) (LockFormRow, error) {
	row := q.db.QueryRow(ctx, lockForm, id)
	var i LockFormRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FormType,
		&i.Status,
		&i.CurrentVersionID,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSubmission = `-- name: LockSubmission :one
SELECT id, form_version_id, entity_type, entity_id, submitted_by_type, submitted_by, answers, status, score, result, submitted_at, row_version, created_at, updated_at
FROM platform.form_submissions WHERE id = $1 FOR UPDATE
`

type LockSubmissionRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	FormVersionID   uuid.UUID          `db:"form_version_id" json:"form_version_id"`
	EntityType      *string            `db:"entity_type" json:"entity_type"`
	EntityID        pgtype.UUID        `db:"entity_id" json:"entity_id"`
	SubmittedByType string             `db:"submitted_by_type" json:"submitted_by_type"`
	SubmittedBy     pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	Answers         []byte             `db:"answers" json:"answers"`
	Status          string             `db:"status" json:"status"`
	Score           pgtype.Numeric     `db:"score" json:"score"`
	Result          []byte             `db:"result" json:"result"`
	SubmittedAt     pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockSubmission(ctx context.Context, id uuid.UUID) (LockSubmissionRow, error) {
	row := q.db.QueryRow(ctx, lockSubmission, id)
	var i LockSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.FormVersionID,
		&i.EntityType,
		&i.EntityID,
		&i.SubmittedByType,
		&i.SubmittedBy,
		&i.Answers,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.SubmittedAt,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const myFormAssignments = `-- name: MyFormAssignments :many
SELECT a.id, a.submission_id, a.section_key, a.status, a.row_version, a.created_at,
       d.id AS form_id, d.name AS form_name, d.form_type, v.schema
FROM platform.form_section_assignments a
JOIN platform.form_submissions s ON s.id = a.submission_id AND s.status = 'draft'
JOIN platform.form_versions v ON v.id = s.form_version_id
JOIN platform.form_definitions d ON d.id = v.form_id
WHERE a.assignee_user_id = $1 AND a.status = 'open'
ORDER BY a.created_at
LIMIT 200
`

type MyFormAssignmentsRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	SubmissionID uuid.UUID          `db:"submission_id" json:"submission_id"`
	SectionKey   string             `db:"section_key" json:"section_key"`
	Status       string             `db:"status" json:"status"`
	RowVersion   int32              `db:"row_version" json:"row_version"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FormID       uuid.UUID          `db:"form_id" json:"form_id"`
	FormName     string             `db:"form_name" json:"form_name"`
	FormType     string             `db:"form_type" json:"form_type"`
	Schema       []byte             `db:"schema" json:"schema"`
}

func (q *Queries) MyFormAssignments(ctx context.Context, userID uuid.UUID) ([]MyFormAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, myFormAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MyFormAssignmentsRow
	for rows.Next() {
		var i MyFormAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.SectionKey,
			&i.Status,
			&i.RowVersion,
			&i.CreatedAt,
			&i.FormID,
			&i.FormName,
			&i.FormType,
			&i.Schema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishVersion = `-- name: PublishVersion :one
UPDATE platform.form_versions
SET published_at = now(), published_by = NULLIF(current_setting('app.user_id', true), '')::uuid, row_version = row_version + 1
WHERE id = $1 AND row_version = $2 AND published_at IS NULL
RETURNING id, form_id, version_no, schema, scoring, languages, published_at, published_by, row_version, updated_at
`

type PublishVersionParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	RowVersion int32     `db:"row_version" json:"row_version"`
}

type PublishVersionRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	FormID      uuid.UUID          `db:"form_id" json:"form_id"`
	VersionNo   int32              `db:"version_no" json:"version_no"`
	Schema      []byte             `db:"schema" json:"schema"`
	Scoring     []byte             `db:"scoring" json:"scoring"`
	Languages   []string           `db:"languages" json:"languages"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	PublishedBy pgtype.UUID        `db:"published_by" json:"published_by"`
	RowVersion  int32              `db:"row_version" json:"row_version"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) PublishVersion(ctx context.Context, arg PublishVersionParams) (PublishVersionRow, error) {
	row := q.db.QueryRow(ctx, publishVersion, arg.ID, arg.RowVersion)
	var i PublishVersionRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNo,
		&i.Schema,
		&i.Scoring,
		&i.Languages,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDraftVersion = `-- name: UpdateDraftVersion :one
UPDATE platform.form_versions
SET schema = $3, scoring = $4, languages = $5, row_version = row_version + 1,
    updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $1 AND row_version = $2 AND published_at IS NULL
RETURNING id, form_id, version_no, schema, scoring, languages, published_at, published_by, row_version, updated_at
`

type UpdateDraftVersionParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	RowVersion int32     `db:"row_version" json:"row_version"`
	Schema     []byte    `db:"schema" json:"schema"`
	Scoring    []byte    `db:"scoring" json:"scoring"`
	Languages  []string  `db:"languages" json:"languages"`
}

type UpdateDraftVersionRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	FormID      uuid.UUID          `db:"form_id" json:"form_id"`
	VersionNo   int32              `db:"version_no" json:"version_no"`
	Schema      []byte             `db:"schema" json:"schema"`
	Scoring     []byte             `db:"scoring" json:"scoring"`
	Languages   []string           `db:"languages" json:"languages"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	PublishedBy pgtype.UUID        `db:"published_by" json:"published_by"`
	RowVersion  int32              `db:"row_version" json:"row_version"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateDraftVersion(ctx context.Context, arg UpdateDraftVersionParams) (UpdateDraftVersionRow, error) {
	row := q.db.QueryRow(ctx, updateDraftVersion,
		arg.ID,
		arg.RowVersion,
		arg.Schema,
		arg.Scoring,
		arg.Languages,
	)
	var i UpdateDraftVersionRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.VersionNo,
		&i.Schema,
		&i.Scoring,
		&i.Languages,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFormState = `-- name: UpdateFormState :exec
UPDATE platform.form_definitions
SET name = $2, status = $3, current_version_id = $4, row_version = row_version + 1,
    updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $1
`

type UpdateFormStateParams struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	Name             string      `db:"name" json:"name"`
	Status           string      `db:"status" json:"status"`
	CurrentVersionID pgtype.UUID `db:"current_version_id" json:"current_version_id"`
}

func (q *Queries) UpdateFormState(ctx context.Context, arg UpdateFormStateParams) error {
	_, err := q.db.Exec(ctx, updateFormState,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CurrentVersionID,
	)
	return err
}

const updateSubmission = `-- name: UpdateSubmission :one
UPDATE platform.form_submissions
SET answers = $2, status = $3, score = $4, result = $5, submitted_at = $6, row_version = row_version + 1,
    updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $1
RETURNING id, form_version_id, entity_type, entity_id, submitted_by_type, submitted_by, answers, status, score, result, submitted_at, row_version, created_at, updated_at
`

type UpdateSubmissionParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Answers     []byte             `db:"answers" json:"answers"`
	Status      string             `db:"status" json:"status"`
	Score       pgtype.Numeric     `db:"score" json:"score"`
	Result      []byte             `db:"result" json:"result"`
	SubmittedAt pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
}

type UpdateSubmissionRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	FormVersionID   uuid.UUID          `db:"form_version_id" json:"form_version_id"`
	EntityType      *string            `db:"entity_type" json:"entity_type"`
	EntityID        pgtype.UUID        `db:"entity_id" json:"entity_id"`
	SubmittedByType string             `db:"submitted_by_type" json:"submitted_by_type"`
	SubmittedBy     pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	Answers         []byte             `db:"answers" json:"answers"`
	Status          string             `db:"status" json:"status"`
	Score           pgtype.Numeric     `db:"score" json:"score"`
	Result          []byte             `db:"result" json:"result"`
	SubmittedAt     pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (UpdateSubmissionRow, error) {
	row := q.db.QueryRow(ctx, updateSubmission,
		arg.ID,
		arg.Answers,
		arg.Status,
		arg.Score,
		arg.Result,
		arg.SubmittedAt,
	)
	var i UpdateSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.FormVersionID,
		&i.EntityType,
		&i.EntityID,
		&i.SubmittedByType,
		&i.SubmittedBy,
		&i.Answers,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.SubmittedAt,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAssignment = `-- name: UpsertAssignment :one
INSERT INTO platform.form_section_assignments (id, tenant_id, submission_id, section_key, assignee_user_id, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
ON CONFLICT (tenant_id, submission_id, section_key) DO UPDATE
SET assignee_user_id = EXCLUDED.assignee_user_id, status = 'open', completed_at = NULL, row_version = platform.form_section_assignments.row_version + 1,
    updated_by = EXCLUDED.updated_by
RETURNING id, submission_id, section_key, assignee_user_id, status, completed_at, row_version
`

type UpsertAssignmentParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	SubmissionID   uuid.UUID `db:"submission_id" json:"submission_id"`
	SectionKey     string    `db:"section_key" json:"section_key"`
	AssigneeUserID uuid.UUID `db:"assignee_user_id" json:"assignee_user_id"`
}

type UpsertAssignmentRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	SubmissionID   uuid.UUID          `db:"submission_id" json:"submission_id"`
	SectionKey     string             `db:"section_key" json:"section_key"`
	AssigneeUserID uuid.UUID          `db:"assignee_user_id" json:"assignee_user_id"`
	Status         string             `db:"status" json:"status"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	RowVersion     int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (UpsertAssignmentRow, error) {
	row := q.db.QueryRow(ctx, upsertAssignment,
		arg.ID,
		arg.SubmissionID,
		arg.SectionKey,
		arg.AssigneeUserID,
	)
	var i UpsertAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.SectionKey,
		&i.AssigneeUserID,
		&i.Status,
		&i.CompletedAt,
		&i.RowVersion,
	)
	return i, err
}
