// Package jobshttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package jobshttp

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for JobState.
const (
	Available JobState = "available"
	Cancelled JobState = "cancelled"
	Completed JobState = "completed"
	Discarded JobState = "discarded"
	Pending   JobState = "pending"
	Retryable JobState = "retryable"
	Running   JobState = "running"
	Scheduled JobState = "scheduled"
)

// Valid indicates whether the value is a known member of the JobState enum.
func (e JobState) Valid() bool {
	switch e {
	case Available:
		return true
	case Cancelled:
		return true
	case Completed:
		return true
	case Discarded:
		return true
	case Pending:
		return true
	case Retryable:
		return true
	case Running:
		return true
	case Scheduled:
		return true
	default:
		return false
	}
}

// Defines values for AcceptLanguage.
const (
	AcceptLanguageEn AcceptLanguage = "en"
	AcceptLanguageTh AcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the AcceptLanguage enum.
func (e AcceptLanguage) Valid() bool {
	switch e {
	case AcceptLanguageEn:
		return true
	case AcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformListJobsParamsAcceptLanguage.
const (
	PlatformListJobsParamsAcceptLanguageEn PlatformListJobsParamsAcceptLanguage = "en"
	PlatformListJobsParamsAcceptLanguageTh PlatformListJobsParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformListJobsParamsAcceptLanguage enum.
func (e PlatformListJobsParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformListJobsParamsAcceptLanguageEn:
		return true
	case PlatformListJobsParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string  `json:"code"`
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
}

// Job One background job. Args are not exposed — they carry identifiers only.
type Job struct {
	// Attempt Attempts made so far
	Attempt     int        `json:"attempt"`
	AttemptedAt *Timestamp `json:"attempted_at,omitempty"`

	// CreatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	CreatedAt   Timestamp  `json:"created_at"`
	FinalizedAt *Timestamp `json:"finalized_at,omitempty"`
	Id          int64      `json:"id"`
	Kind        string     `json:"kind"`

	// LastError Message of the most recent failed attempt (truncated), null if none
	LastError   *string `json:"last_error,omitempty"`
	MaxAttempts int     `json:"max_attempts"`
	Queue       string  `json:"queue"`

	// ScheduledAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	ScheduledAt Timestamp `json:"scheduled_at"`

	// State River job state
	State JobState `json:"state"`
}

// JobList defines model for JobList.
type JobList struct {
	Data       []Job   `json:"data"`
	NextCursor *string `json:"next_cursor"`
}

// JobState River job state
type JobState string

// Problem RFC 9457 problem details with a stable machine-readable `code`
type Problem struct {
	Code      string        `json:"code"`
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// Timestamp RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
type Timestamp = time.Time

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// BadRequest RFC 9457 problem details with a stable machine-readable `code`
type BadRequest = Problem

// Forbidden RFC 9457 problem details with a stable machine-readable `code`
type Forbidden = Problem

// Unauthorized RFC 9457 problem details with a stable machine-readable `code`
type Unauthorized = Problem

// PlatformListJobsParams defines parameters for PlatformListJobs.
type PlatformListJobsParams struct {
	// Cursor Opaque cursor from `next_cursor` of the previous page
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// State Only jobs in these states
	State *[]JobState `form:"state,omitempty" json:"state,omitempty"`

	// Kind Only jobs of this kind (e.g. `outbox.dispatch`)
	Kind *string `form:"kind,omitempty" json:"kind,omitempty"`

	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformListJobsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformListJobsParamsAcceptLanguage defines parameters for PlatformListJobs.
type PlatformListJobsParamsAcceptLanguage string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PlatformListJobs Background jobs of the current tenant (PLT-10 job-status page)
	// (GET /admin/v1/platform/jobs)
	PlatformListJobs(w http.ResponseWriter, r *http.Request, params PlatformListJobsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// PlatformListJobs Background jobs of the current tenant (PLT-10 job-status page)
// (GET /admin/v1/platform/jobs)
func (_ Unimplemented) PlatformListJobs(w http.ResponseWriter, r *http.Request, params PlatformListJobsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PlatformListJobs operation middleware
func (siw *ServerInterfaceWrapper) PlatformListJobs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformListJobsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformListJobsParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformListJobs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/jobs", wrapper.PlatformListJobs)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type PlatformListJobsRequestObject struct {
	Params PlatformListJobsParams
}

type PlatformListJobsResponseObject interface {
	VisitPlatformListJobsResponse(w http.ResponseWriter) error
}

type PlatformListJobs200JSONResponse JobList

func (response PlatformListJobs200JSONResponse) VisitPlatformListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListJobs400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PlatformListJobs400ApplicationProblemPlusJSONResponse) VisitPlatformListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListJobs401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformListJobs401ApplicationProblemPlusJSONResponse) VisitPlatformListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListJobs403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformListJobs403ApplicationProblemPlusJSONResponse) VisitPlatformListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// PlatformListJobs Background jobs of the current tenant (PLT-10 job-status page)
	// (GET /admin/v1/platform/jobs)
	PlatformListJobs(ctx context.Context, request PlatformListJobsRequestObject) (PlatformListJobsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PlatformListJobs operation middleware
func (sh *strictHandler) PlatformListJobs(w http.ResponseWriter, r *http.Request, params PlatformListJobsParams) {
	var request PlatformListJobsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformListJobs(ctx, request.(PlatformListJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformListJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformListJobsResponseObject); ok {
		if err := validResponse.VisitPlatformListJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
