// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notices.sql

package noticestore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNotice = `-- name: GetNotice :one
SELECT id, legal_entity_id, subject_type_id, notice_type, title, slug, document_id, status, current_version_id,
    owner_user_id, review_cycle_months, row_version, updated_at
FROM notice.notices
WHERE id = $1
`

type GetNoticeRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	LegalEntityID     uuid.UUID          `db:"legal_entity_id" json:"legal_entity_id"`
	SubjectTypeID     pgtype.UUID        `db:"subject_type_id" json:"subject_type_id"`
	NoticeType        string             `db:"notice_type" json:"notice_type"`
	Title             string             `db:"title" json:"title"`
	Slug              string             `db:"slug" json:"slug"`
	DocumentID        uuid.UUID          `db:"document_id" json:"document_id"`
	Status            string             `db:"status" json:"status"`
	CurrentVersionID  pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	OwnerUserID       pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	ReviewCycleMonths int16              `db:"review_cycle_months" json:"review_cycle_months"`
	RowVersion        int32              `db:"row_version" json:"row_version"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetNotice(ctx context.Context, id uuid.UUID) (GetNoticeRow, error) {
	row := q.db.QueryRow(ctx, getNotice, id)
	var i GetNoticeRow
	err := row.Scan(
		&i.ID,
		&i.LegalEntityID,
		&i.SubjectTypeID,
		&i.NoticeType,
		&i.Title,
		&i.Slug,
		&i.DocumentID,
		&i.Status,
		&i.CurrentVersionID,
		&i.OwnerUserID,
		&i.ReviewCycleMonths,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotice = `-- name: InsertNotice :one
INSERT INTO notice.notices (id, tenant_id, legal_entity_id, subject_type_id, notice_type, title, slug, document_id,
    owner_user_id, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, $5, $6, $7, $8,
    NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, legal_entity_id, subject_type_id, notice_type, title, slug, document_id, status, current_version_id,
    owner_user_id, review_cycle_months, row_version, updated_at
`

type InsertNoticeParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	LegalEntityID uuid.UUID   `db:"legal_entity_id" json:"legal_entity_id"`
	SubjectTypeID pgtype.UUID `db:"subject_type_id" json:"subject_type_id"`
	NoticeType    string      `db:"notice_type" json:"notice_type"`
	Title         string      `db:"title" json:"title"`
	Slug          string      `db:"slug" json:"slug"`
	DocumentID    uuid.UUID   `db:"document_id" json:"document_id"`
	OwnerUserID   pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
}

type InsertNoticeRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	LegalEntityID     uuid.UUID          `db:"legal_entity_id" json:"legal_entity_id"`
	SubjectTypeID     pgtype.UUID        `db:"subject_type_id" json:"subject_type_id"`
	NoticeType        string             `db:"notice_type" json:"notice_type"`
	Title             string             `db:"title" json:"title"`
	Slug              string             `db:"slug" json:"slug"`
	DocumentID        uuid.UUID          `db:"document_id" json:"document_id"`
	Status            string             `db:"status" json:"status"`
	CurrentVersionID  pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	OwnerUserID       pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	ReviewCycleMonths int16              `db:"review_cycle_months" json:"review_cycle_months"`
	RowVersion        int32              `db:"row_version" json:"row_version"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertNotice(ctx context.Context, arg InsertNoticeParams) (InsertNoticeRow, error) {
	row := q.db.QueryRow(ctx, insertNotice,
		arg.ID,
		arg.LegalEntityID,
		arg.SubjectTypeID,
		arg.NoticeType,
		arg.Title,
		arg.Slug,
		arg.DocumentID,
		arg.OwnerUserID,
	)
	var i InsertNoticeRow
	err := row.Scan(
		&i.ID,
		&i.LegalEntityID,
		&i.SubjectTypeID,
		&i.NoticeType,
		&i.Title,
		&i.Slug,
		&i.DocumentID,
		&i.Status,
		&i.CurrentVersionID,
		&i.OwnerUserID,
		&i.ReviewCycleMonths,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNoticeActivityLink = `-- name: InsertNoticeActivityLink :exec
INSERT INTO notice.notice_activity_links (notice_id, activity_id, tenant_id)
VALUES ($1, $2, current_setting('app.tenant_id')::uuid)
ON CONFLICT DO NOTHING
`

type InsertNoticeActivityLinkParams struct {
	NoticeID   uuid.UUID `db:"notice_id" json:"notice_id"`
	ActivityID uuid.UUID `db:"activity_id" json:"activity_id"`
}

func (q *Queries) InsertNoticeActivityLink(ctx context.Context, arg InsertNoticeActivityLinkParams) error {
	_, err := q.db.Exec(ctx, insertNoticeActivityLink, arg.NoticeID, arg.ActivityID)
	return err
}

const listNoticeActivityLinks = `-- name: ListNoticeActivityLinks :many
SELECT activity_id FROM notice.notice_activity_links WHERE notice_id = $1 ORDER BY activity_id
`

func (q *Queries) ListNoticeActivityLinks(ctx context.Context, noticeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listNoticeActivityLinks, noticeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var activity_id uuid.UUID
		if err := rows.Scan(&activity_id); err != nil {
			return nil, err
		}
		items = append(items, activity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotices = `-- name: ListNotices :many
SELECT id, legal_entity_id, subject_type_id, notice_type, title, slug, document_id, status, current_version_id,
    owner_user_id, review_cycle_months, row_version, updated_at
FROM notice.notices
WHERE ($1::text IS NULL OR notice_type = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::timestamptz IS NULL
       OR (updated_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY updated_at DESC, id DESC
LIMIT $5
`

type ListNoticesParams struct {
	NoticeType *string            `db:"notice_type" json:"notice_type"`
	Status     *string            `db:"status" json:"status"`
	CursorAt   pgtype.Timestamptz `db:"cursor_at" json:"cursor_at"`
	CursorID   pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	Lim        int32              `db:"lim" json:"lim"`
}

type ListNoticesRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	LegalEntityID     uuid.UUID          `db:"legal_entity_id" json:"legal_entity_id"`
	SubjectTypeID     pgtype.UUID        `db:"subject_type_id" json:"subject_type_id"`
	NoticeType        string             `db:"notice_type" json:"notice_type"`
	Title             string             `db:"title" json:"title"`
	Slug              string             `db:"slug" json:"slug"`
	DocumentID        uuid.UUID          `db:"document_id" json:"document_id"`
	Status            string             `db:"status" json:"status"`
	CurrentVersionID  pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	OwnerUserID       pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	ReviewCycleMonths int16              `db:"review_cycle_months" json:"review_cycle_months"`
	RowVersion        int32              `db:"row_version" json:"row_version"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListNotices(ctx context.Context, arg ListNoticesParams) ([]ListNoticesRow, error) {
	rows, err := q.db.Query(ctx, listNotices,
		arg.NoticeType,
		arg.Status,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoticesRow
	for rows.Next() {
		var i ListNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.LegalEntityID,
			&i.SubjectTypeID,
			&i.NoticeType,
			&i.Title,
			&i.Slug,
			&i.DocumentID,
			&i.Status,
			&i.CurrentVersionID,
			&i.OwnerUserID,
			&i.ReviewCycleMonths,
			&i.RowVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
