-- +goose Up
-- global permission catalogue + 16 system roles (tenant_id NULL = template roles every tenant can see)
-- source: docs/security/permissions.yaml (plan sheet Roles_Permissions). x-permission in OpenAPI = iam.permissions.code
-- global rows need the table owner to bypass RLS inside this migration (FORCE is restored before commit)

INSERT INTO iam.permissions (code, module, resource, action, description, is_sensitive) VALUES
    ('admin.accessreview.create', 'admin', 'accessreview', 'C', 'ทบทวนสิทธิ์ — สร้าง', false),
    ('admin.accessreview.delete', 'admin', 'accessreview', 'D', 'ทบทวนสิทธิ์ — ลบ', false),
    ('admin.accessreview.execute', 'admin', 'accessreview', 'X', 'ทบทวนสิทธิ์ — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('admin.accessreview.read', 'admin', 'accessreview', 'R', 'ทบทวนสิทธิ์ — ดู', false),
    ('admin.accessreview.update', 'admin', 'accessreview', 'U', 'ทบทวนสิทธิ์ — แก้ไข', false),
    ('admin.apiclient.create', 'admin', 'apiclient', 'C', 'API client และ webhook — สร้าง', false),
    ('admin.apiclient.delete', 'admin', 'apiclient', 'D', 'API client และ webhook — ลบ', false),
    ('admin.apiclient.read', 'admin', 'apiclient', 'R', 'API client และ webhook — ดู', false),
    ('admin.apiclient.update', 'admin', 'apiclient', 'U', 'API client และ webhook — แก้ไข', false),
    ('admin.audit.export', 'admin', 'audit', 'E', 'Audit log — ส่งออก', true),
    ('admin.audit.read', 'admin', 'audit', 'R', 'Audit log — ดู', false),
    ('admin.breakglass.execute', 'admin', 'breakglass', 'X', 'ใช้สิทธิ์ฉุกเฉิน — ดำเนินการ / มอบหมาย / ทำรายการ', true),
    ('admin.group.create', 'admin', 'group', 'C', 'กลุ่มผู้ใช้ / ทีม — สร้าง', false),
    ('admin.group.delete', 'admin', 'group', 'D', 'กลุ่มผู้ใช้ / ทีม — ลบ', false),
    ('admin.group.read', 'admin', 'group', 'R', 'กลุ่มผู้ใช้ / ทีม — ดู', false),
    ('admin.group.update', 'admin', 'group', 'U', 'กลุ่มผู้ใช้ / ทีม — แก้ไข', false),
    ('admin.idp.create', 'admin', 'idp', 'C', 'SSO, IdP, นโยบายรหัสผ่านและ MFA — สร้าง', false),
    ('admin.idp.delete', 'admin', 'idp', 'D', 'SSO, IdP, นโยบายรหัสผ่านและ MFA — ลบ', false),
    ('admin.idp.read', 'admin', 'idp', 'R', 'SSO, IdP, นโยบายรหัสผ่านและ MFA — ดู', false),
    ('admin.idp.update', 'admin', 'idp', 'U', 'SSO, IdP, นโยบายรหัสผ่านและ MFA — แก้ไข', false),
    ('admin.notification.create', 'admin', 'notification', 'C', 'Template แจ้งเตือน — สร้าง', false),
    ('admin.notification.delete', 'admin', 'notification', 'D', 'Template แจ้งเตือน — ลบ', false),
    ('admin.notification.read', 'admin', 'notification', 'R', 'Template แจ้งเตือน — ดู', false),
    ('admin.notification.update', 'admin', 'notification', 'U', 'Template แจ้งเตือน — แก้ไข', false),
    ('admin.role.approve', 'admin', 'role', 'A', 'Role และ Permission — อนุมัติ', true),
    ('admin.role.create', 'admin', 'role', 'C', 'Role และ Permission — สร้าง', true),
    ('admin.role.delete', 'admin', 'role', 'D', 'Role และ Permission — ลบ', true),
    ('admin.role.read', 'admin', 'role', 'R', 'Role และ Permission — ดู', true),
    ('admin.role.update', 'admin', 'role', 'U', 'Role และ Permission — แก้ไข', true),
    ('admin.scope.create', 'admin', 'scope', 'C', 'ขอบเขตข้อมูลของผู้ใช้ — สร้าง', false),
    ('admin.scope.delete', 'admin', 'scope', 'D', 'ขอบเขตข้อมูลของผู้ใช้ — ลบ', false),
    ('admin.scope.read', 'admin', 'scope', 'R', 'ขอบเขตข้อมูลของผู้ใช้ — ดู', false),
    ('admin.scope.update', 'admin', 'scope', 'U', 'ขอบเขตข้อมูลของผู้ใช้ — แก้ไข', false),
    ('admin.tenant.create', 'admin', 'tenant', 'C', 'Tenant แพ็กเกจ และโมดูลที่เปิดใช้ — สร้าง', false),
    ('admin.tenant.delete', 'admin', 'tenant', 'D', 'Tenant แพ็กเกจ และโมดูลที่เปิดใช้ — ลบ', false),
    ('admin.tenant.read', 'admin', 'tenant', 'R', 'Tenant แพ็กเกจ และโมดูลที่เปิดใช้ — ดู', false),
    ('admin.tenant.update', 'admin', 'tenant', 'U', 'Tenant แพ็กเกจ และโมดูลที่เปิดใช้ — แก้ไข', false),
    ('admin.user.create', 'admin', 'user', 'C', 'ผู้ใช้ — สร้าง', false),
    ('admin.user.delete', 'admin', 'user', 'D', 'ผู้ใช้ — ลบ', false),
    ('admin.user.read', 'admin', 'user', 'R', 'ผู้ใช้ — ดู', false),
    ('admin.user.update', 'admin', 'user', 'U', 'ผู้ใช้ — แก้ไข', false),
    ('agreement.clause.create', 'agreement', 'clause', 'C', 'คลังข้อความสัญญา — สร้าง', false),
    ('agreement.clause.delete', 'agreement', 'clause', 'D', 'คลังข้อความสัญญา — ลบ', false),
    ('agreement.clause.publish', 'agreement', 'clause', 'P', 'คลังข้อความสัญญา — เผยแพร่ / เปิดใช้งาน', false),
    ('agreement.clause.read', 'agreement', 'clause', 'R', 'คลังข้อความสัญญา — ดู', false),
    ('agreement.clause.update', 'agreement', 'clause', 'U', 'คลังข้อความสัญญา — แก้ไข', false),
    ('agreement.dpa.approve', 'agreement', 'dpa', 'A', 'ข้อตกลงการประมวลผล (DPA) — อนุมัติ', false),
    ('agreement.dpa.create', 'agreement', 'dpa', 'C', 'ข้อตกลงการประมวลผล (DPA) — สร้าง', false),
    ('agreement.dpa.delete', 'agreement', 'dpa', 'D', 'ข้อตกลงการประมวลผล (DPA) — ลบ', false),
    ('agreement.dpa.publish', 'agreement', 'dpa', 'P', 'ข้อตกลงการประมวลผล (DPA) — เผยแพร่ / เปิดใช้งาน', false),
    ('agreement.dpa.read', 'agreement', 'dpa', 'R', 'ข้อตกลงการประมวลผล (DPA) — ดู', false),
    ('agreement.dpa.update', 'agreement', 'dpa', 'U', 'ข้อตกลงการประมวลผล (DPA) — แก้ไข', false),
    ('agreement.dsa.approve', 'agreement', 'dsa', 'A', 'ข้อตกลงการแบ่งปันข้อมูล (DSA) — อนุมัติ', false),
    ('agreement.dsa.create', 'agreement', 'dsa', 'C', 'ข้อตกลงการแบ่งปันข้อมูล (DSA) — สร้าง', false),
    ('agreement.dsa.delete', 'agreement', 'dsa', 'D', 'ข้อตกลงการแบ่งปันข้อมูล (DSA) — ลบ', false),
    ('agreement.dsa.publish', 'agreement', 'dsa', 'P', 'ข้อตกลงการแบ่งปันข้อมูล (DSA) — เผยแพร่ / เปิดใช้งาน', false),
    ('agreement.dsa.read', 'agreement', 'dsa', 'R', 'ข้อตกลงการแบ่งปันข้อมูล (DSA) — ดู', false),
    ('agreement.dsa.update', 'agreement', 'dsa', 'U', 'ข้อตกลงการแบ่งปันข้อมูล (DSA) — แก้ไข', false),
    ('assessment.dpia.approve', 'assessment', 'dpia', 'A', 'DPIA / LIA — อนุมัติ', false),
    ('assessment.dpia.create', 'assessment', 'dpia', 'C', 'DPIA / LIA — สร้าง', false),
    ('assessment.dpia.delete', 'assessment', 'dpia', 'D', 'DPIA / LIA — ลบ', false),
    ('assessment.dpia.read', 'assessment', 'dpia', 'R', 'DPIA / LIA — ดู', false),
    ('assessment.dpia.update', 'assessment', 'dpia', 'U', 'DPIA / LIA — แก้ไข', false),
    ('assessment.security.approve', 'assessment', 'security', 'A', 'ประเมินมาตรการความปลอดภัย — อนุมัติ', false),
    ('assessment.security.create', 'assessment', 'security', 'C', 'ประเมินมาตรการความปลอดภัย — สร้าง', false),
    ('assessment.security.delete', 'assessment', 'security', 'D', 'ประเมินมาตรการความปลอดภัย — ลบ', false),
    ('assessment.security.execute', 'assessment', 'security', 'X', 'ประเมินมาตรการความปลอดภัย — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('assessment.security.read', 'assessment', 'security', 'R', 'ประเมินมาตรการความปลอดภัย — ดู', false),
    ('assessment.security.update', 'assessment', 'security', 'U', 'ประเมินมาตรการความปลอดภัย — แก้ไข', false),
    ('assessment.template.create', 'assessment', 'template', 'C', 'Template แบบประเมิน — สร้าง', false),
    ('assessment.template.delete', 'assessment', 'template', 'D', 'Template แบบประเมิน — ลบ', false),
    ('assessment.template.publish', 'assessment', 'template', 'P', 'Template แบบประเมิน — เผยแพร่ / เปิดใช้งาน', false),
    ('assessment.template.read', 'assessment', 'template', 'R', 'Template แบบประเมิน — ดู', false),
    ('assessment.template.update', 'assessment', 'template', 'U', 'Template แบบประเมิน — แก้ไข', false),
    ('assessment.transfer.approve', 'assessment', 'transfer', 'A', 'ประเมินการโอนต่างประเทศ (TIA) — อนุมัติ', false),
    ('assessment.transfer.create', 'assessment', 'transfer', 'C', 'ประเมินการโอนต่างประเทศ (TIA) — สร้าง', false),
    ('assessment.transfer.delete', 'assessment', 'transfer', 'D', 'ประเมินการโอนต่างประเทศ (TIA) — ลบ', false),
    ('assessment.transfer.read', 'assessment', 'transfer', 'R', 'ประเมินการโอนต่างประเทศ (TIA) — ดู', false),
    ('assessment.transfer.update', 'assessment', 'transfer', 'U', 'ประเมินการโอนต่างประเทศ (TIA) — แก้ไข', false),
    ('breach.incident.approve', 'breach', 'incident', 'A', 'เหตุละเมิด — อนุมัติ', false),
    ('breach.incident.create', 'breach', 'incident', 'C', 'เหตุละเมิด — สร้าง', false),
    ('breach.incident.delete', 'breach', 'incident', 'D', 'เหตุละเมิด — ลบ', false),
    ('breach.incident.execute', 'breach', 'incident', 'X', 'เหตุละเมิด — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('breach.incident.read', 'breach', 'incident', 'R', 'เหตุละเมิด — ดู', false),
    ('breach.incident.update', 'breach', 'incident', 'U', 'เหตุละเมิด — แก้ไข', false),
    ('breach.notification.approve', 'breach', 'notification', 'A', 'แบบแจ้ง สคส. / แจ้งเจ้าของข้อมูล — อนุมัติ', false),
    ('breach.notification.create', 'breach', 'notification', 'C', 'แบบแจ้ง สคส. / แจ้งเจ้าของข้อมูล — สร้าง', false),
    ('breach.notification.publish', 'breach', 'notification', 'P', 'แบบแจ้ง สคส. / แจ้งเจ้าของข้อมูล — เผยแพร่ / เปิดใช้งาน', false),
    ('breach.notification.read', 'breach', 'notification', 'R', 'แบบแจ้ง สคส. / แจ้งเจ้าของข้อมูล — ดู', false),
    ('breach.notification.update', 'breach', 'notification', 'U', 'แบบแจ้ง สคส. / แจ้งเจ้าของข้อมูล — แก้ไข', false),
    ('consent.bulk.execute', 'consent', 'bulk', 'X', 'นำเข้า / ส่งออกความยินยอม — ดำเนินการ / มอบหมาย / ทำรายการ', true),
    ('consent.bulk.export', 'consent', 'bulk', 'E', 'นำเข้า / ส่งออกความยินยอม — ส่งออก', true),
    ('consent.campaign.approve', 'consent', 'campaign', 'A', 'แคมเปญขอความยินยอม — อนุมัติ', false),
    ('consent.campaign.create', 'consent', 'campaign', 'C', 'แคมเปญขอความยินยอม — สร้าง', false),
    ('consent.campaign.delete', 'consent', 'campaign', 'D', 'แคมเปญขอความยินยอม — ลบ', false),
    ('consent.campaign.execute', 'consent', 'campaign', 'X', 'แคมเปญขอความยินยอม — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('consent.campaign.read', 'consent', 'campaign', 'R', 'แคมเปญขอความยินยอม — ดู', false),
    ('consent.campaign.update', 'consent', 'campaign', 'U', 'แคมเปญขอความยินยอม — แก้ไข', false),
    ('consent.collectionpoint.approve', 'consent', 'collectionpoint', 'A', 'Collection Point / แบบฟอร์ม — อนุมัติ', false),
    ('consent.collectionpoint.create', 'consent', 'collectionpoint', 'C', 'Collection Point / แบบฟอร์ม — สร้าง', false),
    ('consent.collectionpoint.delete', 'consent', 'collectionpoint', 'D', 'Collection Point / แบบฟอร์ม — ลบ', false),
    ('consent.collectionpoint.publish', 'consent', 'collectionpoint', 'P', 'Collection Point / แบบฟอร์ม — เผยแพร่ / เปิดใช้งาน', false),
    ('consent.collectionpoint.read', 'consent', 'collectionpoint', 'R', 'Collection Point / แบบฟอร์ม — ดู', false),
    ('consent.collectionpoint.update', 'consent', 'collectionpoint', 'U', 'Collection Point / แบบฟอร์ม — แก้ไข', false),
    ('consent.onbehalf.create', 'consent', 'onbehalf', 'C', 'บันทึกความยินยอมแทนลูกค้า — สร้าง', false),
    ('consent.onbehalf.read', 'consent', 'onbehalf', 'R', 'บันทึกความยินยอมแทนลูกค้า — ดู', false),
    ('consent.purpose.approve', 'consent', 'purpose', 'A', 'Purpose / Data Element / Purpose Preference — อนุมัติ', false),
    ('consent.purpose.create', 'consent', 'purpose', 'C', 'Purpose / Data Element / Purpose Preference — สร้าง', false),
    ('consent.purpose.delete', 'consent', 'purpose', 'D', 'Purpose / Data Element / Purpose Preference — ลบ', false),
    ('consent.purpose.publish', 'consent', 'purpose', 'P', 'Purpose / Data Element / Purpose Preference — เผยแพร่ / เปิดใช้งาน', false),
    ('consent.purpose.read', 'consent', 'purpose', 'R', 'Purpose / Data Element / Purpose Preference — ดู', false),
    ('consent.purpose.update', 'consent', 'purpose', 'U', 'Purpose / Data Element / Purpose Preference — แก้ไข', false),
    ('consent.record.create', 'consent', 'record', 'C', 'ความยินยอมรายบุคคล / โปรไฟล์ — สร้าง', false),
    ('consent.record.export', 'consent', 'record', 'E', 'ความยินยอมรายบุคคล / โปรไฟล์ — ส่งออก', true),
    ('consent.record.read', 'consent', 'record', 'R', 'ความยินยอมรายบุคคล / โปรไฟล์ — ดู', false),
    ('cookie.banner.approve', 'cookie', 'banner', 'A', 'แบนเนอร์คุกกี้และโดเมน — อนุมัติ', false),
    ('cookie.banner.create', 'cookie', 'banner', 'C', 'แบนเนอร์คุกกี้และโดเมน — สร้าง', false),
    ('cookie.banner.delete', 'cookie', 'banner', 'D', 'แบนเนอร์คุกกี้และโดเมน — ลบ', false),
    ('cookie.banner.publish', 'cookie', 'banner', 'P', 'แบนเนอร์คุกกี้และโดเมน — เผยแพร่ / เปิดใช้งาน', false),
    ('cookie.banner.read', 'cookie', 'banner', 'R', 'แบนเนอร์คุกกี้และโดเมน — ดู', false),
    ('cookie.banner.update', 'cookie', 'banner', 'U', 'แบนเนอร์คุกกี้และโดเมน — แก้ไข', false),
    ('cookie.scan.create', 'cookie', 'scan', 'C', 'ผลสแกนคุกกี้ — สร้าง', false),
    ('cookie.scan.delete', 'cookie', 'scan', 'D', 'ผลสแกนคุกกี้ — ลบ', false),
    ('cookie.scan.execute', 'cookie', 'scan', 'X', 'ผลสแกนคุกกี้ — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('cookie.scan.read', 'cookie', 'scan', 'R', 'ผลสแกนคุกกี้ — ดู', false),
    ('cookie.scan.update', 'cookie', 'scan', 'U', 'ผลสแกนคุกกี้ — แก้ไข', false),
    ('dpo.advisory.create', 'dpo', 'advisory', 'C', 'คำปรึกษาถึง DPO — สร้าง', false),
    ('dpo.advisory.execute', 'dpo', 'advisory', 'X', 'คำปรึกษาถึง DPO — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dpo.advisory.read', 'dpo', 'advisory', 'R', 'คำปรึกษาถึง DPO — ดู', false),
    ('dpo.advisory.update', 'dpo', 'advisory', 'U', 'คำปรึกษาถึง DPO — แก้ไข', false),
    ('dpo.kb.create', 'dpo', 'kb', 'C', 'คลังเอกสารกฎหมายและ FAQ — สร้าง', false),
    ('dpo.kb.delete', 'dpo', 'kb', 'D', 'คลังเอกสารกฎหมายและ FAQ — ลบ', false),
    ('dpo.kb.publish', 'dpo', 'kb', 'P', 'คลังเอกสารกฎหมายและ FAQ — เผยแพร่ / เปิดใช้งาน', false),
    ('dpo.kb.read', 'dpo', 'kb', 'R', 'คลังเอกสารกฎหมายและ FAQ — ดู', false),
    ('dpo.kb.update', 'dpo', 'kb', 'U', 'คลังเอกสารกฎหมายและ FAQ — แก้ไข', false),
    ('dpo.profile.create', 'dpo', 'profile', 'C', 'ทะเบียน DPO — สร้าง', false),
    ('dpo.profile.read', 'dpo', 'profile', 'R', 'ทะเบียน DPO — ดู', false),
    ('dpo.profile.update', 'dpo', 'profile', 'U', 'ทะเบียน DPO — แก้ไข', false),
    ('dpo.report.export', 'dpo', 'report', 'E', 'Dashboard และรายงาน — ส่งออก', true),
    ('dpo.report.read', 'dpo', 'report', 'R', 'Dashboard และรายงาน — ดู', false),
    ('dpo.risk.approve', 'dpo', 'risk', 'A', 'ทะเบียนความเสี่ยง — อนุมัติ', false),
    ('dpo.risk.create', 'dpo', 'risk', 'C', 'ทะเบียนความเสี่ยง — สร้าง', false),
    ('dpo.risk.delete', 'dpo', 'risk', 'D', 'ทะเบียนความเสี่ยง — ลบ', false),
    ('dpo.risk.read', 'dpo', 'risk', 'R', 'ทะเบียนความเสี่ยง — ดู', false),
    ('dpo.risk.update', 'dpo', 'risk', 'U', 'ทะเบียนความเสี่ยง — แก้ไข', false),
    ('dpo.task.create', 'dpo', 'task', 'C', 'Tasks / Ticket — สร้าง', false),
    ('dpo.task.delete', 'dpo', 'task', 'D', 'Tasks / Ticket — ลบ', false),
    ('dpo.task.execute', 'dpo', 'task', 'X', 'Tasks / Ticket — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dpo.task.read', 'dpo', 'task', 'R', 'Tasks / Ticket — ดู', false),
    ('dpo.task.update', 'dpo', 'task', 'U', 'Tasks / Ticket — แก้ไข', false),
    ('dpx.ai.approve', 'dpx', 'ai', 'A', 'ทะเบียนระบบ AI และผู้ช่วย AI — อนุมัติ', false),
    ('dpx.ai.create', 'dpx', 'ai', 'C', 'ทะเบียนระบบ AI และผู้ช่วย AI — สร้าง', false),
    ('dpx.ai.delete', 'dpx', 'ai', 'D', 'ทะเบียนระบบ AI และผู้ช่วย AI — ลบ', false),
    ('dpx.ai.execute', 'dpx', 'ai', 'X', 'ทะเบียนระบบ AI และผู้ช่วย AI — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dpx.ai.read', 'dpx', 'ai', 'R', 'ทะเบียนระบบ AI และผู้ช่วย AI — ดู', false),
    ('dpx.ai.update', 'dpx', 'ai', 'U', 'ทะเบียนระบบ AI และผู้ช่วย AI — แก้ไข', false),
    ('dpx.audit.approve', 'dpx', 'audit', 'A', 'ตรวจประเมินความพร้อมและแผนแก้ไข — อนุมัติ', false),
    ('dpx.audit.create', 'dpx', 'audit', 'C', 'ตรวจประเมินความพร้อมและแผนแก้ไข — สร้าง', false),
    ('dpx.audit.delete', 'dpx', 'audit', 'D', 'ตรวจประเมินความพร้อมและแผนแก้ไข — ลบ', false),
    ('dpx.audit.export', 'dpx', 'audit', 'E', 'ตรวจประเมินความพร้อมและแผนแก้ไข — ส่งออก', true),
    ('dpx.audit.read', 'dpx', 'audit', 'R', 'ตรวจประเมินความพร้อมและแผนแก้ไข — ดู', false),
    ('dpx.audit.update', 'dpx', 'audit', 'U', 'ตรวจประเมินความพร้อมและแผนแก้ไข — แก้ไข', false),
    ('dpx.integration.create', 'dpx', 'integration', 'C', 'Connector HR / ITSM / SIEM — สร้าง', false),
    ('dpx.integration.delete', 'dpx', 'integration', 'D', 'Connector HR / ITSM / SIEM — ลบ', false),
    ('dpx.integration.read', 'dpx', 'integration', 'R', 'Connector HR / ITSM / SIEM — ดู', false),
    ('dpx.integration.update', 'dpx', 'integration', 'U', 'Connector HR / ITSM / SIEM — แก้ไข', false),
    ('dpx.policy.create', 'dpx', 'policy', 'C', 'รับทราบนโยบายภายใน — สร้าง', false),
    ('dpx.policy.delete', 'dpx', 'policy', 'D', 'รับทราบนโยบายภายใน — ลบ', false),
    ('dpx.policy.execute', 'dpx', 'policy', 'X', 'รับทราบนโยบายภายใน — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dpx.policy.publish', 'dpx', 'policy', 'P', 'รับทราบนโยบายภายใน — เผยแพร่ / เปิดใช้งาน', false),
    ('dpx.policy.read', 'dpx', 'policy', 'R', 'รับทราบนโยบายภายใน — ดู', false),
    ('dpx.policy.update', 'dpx', 'policy', 'U', 'รับทราบนโยบายภายใน — แก้ไข', false),
    ('dpx.regulator.create', 'dpx', 'regulator', 'C', 'ทะเบียนการติดต่อกับ สคส. — สร้าง', false),
    ('dpx.regulator.delete', 'dpx', 'regulator', 'D', 'ทะเบียนการติดต่อกับ สคส. — ลบ', false),
    ('dpx.regulator.read', 'dpx', 'regulator', 'R', 'ทะเบียนการติดต่อกับ สคส. — ดู', false),
    ('dpx.regulator.update', 'dpx', 'regulator', 'U', 'ทะเบียนการติดต่อกับ สคส. — แก้ไข', false),
    ('dpx.retention.approve', 'dpx', 'retention', 'A', 'Retention และการทำลายข้อมูล — อนุมัติ', false),
    ('dpx.retention.create', 'dpx', 'retention', 'C', 'Retention และการทำลายข้อมูล — สร้าง', false),
    ('dpx.retention.delete', 'dpx', 'retention', 'D', 'Retention และการทำลายข้อมูล — ลบ', false),
    ('dpx.retention.execute', 'dpx', 'retention', 'X', 'Retention และการทำลายข้อมูล — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dpx.retention.read', 'dpx', 'retention', 'R', 'Retention และการทำลายข้อมูล — ดู', false),
    ('dpx.retention.update', 'dpx', 'retention', 'U', 'Retention และการทำลายข้อมูล — แก้ไข', false),
    ('dpx.training.create', 'dpx', 'training', 'C', 'อบรมและทดสอบ — สร้าง', false),
    ('dpx.training.delete', 'dpx', 'training', 'D', 'อบรมและทดสอบ — ลบ', false),
    ('dpx.training.execute', 'dpx', 'training', 'X', 'อบรมและทดสอบ — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dpx.training.publish', 'dpx', 'training', 'P', 'อบรมและทดสอบ — เผยแพร่ / เปิดใช้งาน', false),
    ('dpx.training.read', 'dpx', 'training', 'R', 'อบรมและทดสอบ — ดู', false),
    ('dpx.training.update', 'dpx', 'training', 'U', 'อบรมและทดสอบ — แก้ไข', false),
    ('dsar.form.create', 'dsar', 'form', 'C', 'แบบฟอร์มคำขอใช้สิทธิ — สร้าง', false),
    ('dsar.form.delete', 'dsar', 'form', 'D', 'แบบฟอร์มคำขอใช้สิทธิ — ลบ', false),
    ('dsar.form.publish', 'dsar', 'form', 'P', 'แบบฟอร์มคำขอใช้สิทธิ — เผยแพร่ / เปิดใช้งาน', false),
    ('dsar.form.read', 'dsar', 'form', 'R', 'แบบฟอร์มคำขอใช้สิทธิ — ดู', false),
    ('dsar.form.update', 'dsar', 'form', 'U', 'แบบฟอร์มคำขอใช้สิทธิ — แก้ไข', false),
    ('dsar.package.approve', 'dsar', 'package', 'A', 'ข้อมูลที่ส่งคืนเจ้าของข้อมูล — อนุมัติ', false),
    ('dsar.package.create', 'dsar', 'package', 'C', 'ข้อมูลที่ส่งคืนเจ้าของข้อมูล — สร้าง', false),
    ('dsar.package.read', 'dsar', 'package', 'R', 'ข้อมูลที่ส่งคืนเจ้าของข้อมูล — ดู', false),
    ('dsar.package.update', 'dsar', 'package', 'U', 'ข้อมูลที่ส่งคืนเจ้าของข้อมูล — แก้ไข', false),
    ('dsar.request.approve', 'dsar', 'request', 'A', 'คำขอใช้สิทธิ — อนุมัติ', false),
    ('dsar.request.create', 'dsar', 'request', 'C', 'คำขอใช้สิทธิ — สร้าง', false),
    ('dsar.request.delete', 'dsar', 'request', 'D', 'คำขอใช้สิทธิ — ลบ', false),
    ('dsar.request.execute', 'dsar', 'request', 'X', 'คำขอใช้สิทธิ — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dsar.request.export', 'dsar', 'request', 'E', 'คำขอใช้สิทธิ — ส่งออก', true),
    ('dsar.request.read', 'dsar', 'request', 'R', 'คำขอใช้สิทธิ — ดู', false),
    ('dsar.request.update', 'dsar', 'request', 'U', 'คำขอใช้สิทธิ — แก้ไข', false),
    ('dsar.subtask.create', 'dsar', 'subtask', 'C', 'งานย่อยของคำขอ — สร้าง', false),
    ('dsar.subtask.delete', 'dsar', 'subtask', 'D', 'งานย่อยของคำขอ — ลบ', false),
    ('dsar.subtask.execute', 'dsar', 'subtask', 'X', 'งานย่อยของคำขอ — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('dsar.subtask.read', 'dsar', 'subtask', 'R', 'งานย่อยของคำขอ — ดู', false),
    ('dsar.subtask.update', 'dsar', 'subtask', 'U', 'งานย่อยของคำขอ — แก้ไข', false),
    ('notice.document.approve', 'notice', 'document', 'A', 'ประกาศความเป็นส่วนตัว — อนุมัติ', false),
    ('notice.document.create', 'notice', 'document', 'C', 'ประกาศความเป็นส่วนตัว — สร้าง', false),
    ('notice.document.delete', 'notice', 'document', 'D', 'ประกาศความเป็นส่วนตัว — ลบ', false),
    ('notice.document.publish', 'notice', 'document', 'P', 'ประกาศความเป็นส่วนตัว — เผยแพร่ / เปิดใช้งาน', false),
    ('notice.document.read', 'notice', 'document', 'R', 'ประกาศความเป็นส่วนตัว — ดู', false),
    ('notice.document.update', 'notice', 'document', 'U', 'ประกาศความเป็นส่วนตัว — แก้ไข', false),
    ('notice.indirect.create', 'notice', 'indirect', 'C', 'แจ้งกรณีได้ข้อมูลจากแหล่งอื่น (ม.25) — สร้าง', false),
    ('notice.indirect.delete', 'notice', 'indirect', 'D', 'แจ้งกรณีได้ข้อมูลจากแหล่งอื่น (ม.25) — ลบ', false),
    ('notice.indirect.read', 'notice', 'indirect', 'R', 'แจ้งกรณีได้ข้อมูลจากแหล่งอื่น (ม.25) — ดู', false),
    ('notice.indirect.update', 'notice', 'indirect', 'U', 'แจ้งกรณีได้ข้อมูลจากแหล่งอื่น (ม.25) — แก้ไข', false),
    ('notice.template.create', 'notice', 'template', 'C', 'Template ประกาศ — สร้าง', false),
    ('notice.template.delete', 'notice', 'template', 'D', 'Template ประกาศ — ลบ', false),
    ('notice.template.read', 'notice', 'template', 'R', 'Template ประกาศ — ดู', false),
    ('notice.template.update', 'notice', 'template', 'U', 'Template ประกาศ — แก้ไข', false),
    ('org.masterdata.create', 'org', 'masterdata', 'C', 'ข้อมูลตั้งต้น — สร้าง', false),
    ('org.masterdata.delete', 'org', 'masterdata', 'D', 'ข้อมูลตั้งต้น — ลบ', false),
    ('org.masterdata.read', 'org', 'masterdata', 'R', 'ข้อมูลตั้งต้น — ดู', false),
    ('org.masterdata.update', 'org', 'masterdata', 'U', 'ข้อมูลตั้งต้น — แก้ไข', false),
    ('org.party.create', 'org', 'party', 'C', 'ทะเบียนหน่วยงานภายนอก — สร้าง', false),
    ('org.party.delete', 'org', 'party', 'D', 'ทะเบียนหน่วยงานภายนอก — ลบ', false),
    ('org.party.read', 'org', 'party', 'R', 'ทะเบียนหน่วยงานภายนอก — ดู', false),
    ('org.party.update', 'org', 'party', 'U', 'ทะเบียนหน่วยงานภายนอก — แก้ไข', false),
    ('org.settings.create', 'org', 'settings', 'C', 'ตั้งค่าองค์กร แบรนด์ และปฏิทินวันทำการ — สร้าง', false),
    ('org.settings.delete', 'org', 'settings', 'D', 'ตั้งค่าองค์กร แบรนด์ และปฏิทินวันทำการ — ลบ', false),
    ('org.settings.read', 'org', 'settings', 'R', 'ตั้งค่าองค์กร แบรนด์ และปฏิทินวันทำการ — ดู', false),
    ('org.settings.update', 'org', 'settings', 'U', 'ตั้งค่าองค์กร แบรนด์ และปฏิทินวันทำการ — แก้ไข', false),
    ('org.structure.create', 'org', 'structure', 'C', 'นิติบุคคลและโครงสร้างหน่วยงาน — สร้าง', false),
    ('org.structure.delete', 'org', 'structure', 'D', 'นิติบุคคลและโครงสร้างหน่วยงาน — ลบ', false),
    ('org.structure.read', 'org', 'structure', 'R', 'นิติบุคคลและโครงสร้างหน่วยงาน — ดู', false),
    ('org.structure.update', 'org', 'structure', 'U', 'นิติบุคคลและโครงสร้างหน่วยงาน — แก้ไข', false),
    ('pii.unmask.execute', 'pii', 'unmask', 'X', 'เปิดดูข้อมูลส่วนบุคคลแบบไม่ปกปิด — ดำเนินการ / มอบหมาย / ทำรายการ', true),
    ('ropa.activity.approve', 'ropa', 'activity', 'A', 'กิจกรรมการประมวลผล (RoPA) — อนุมัติ', false),
    ('ropa.activity.create', 'ropa', 'activity', 'C', 'กิจกรรมการประมวลผล (RoPA) — สร้าง', false),
    ('ropa.activity.delete', 'ropa', 'activity', 'D', 'กิจกรรมการประมวลผล (RoPA) — ลบ', false),
    ('ropa.activity.export', 'ropa', 'activity', 'E', 'กิจกรรมการประมวลผล (RoPA) — ส่งออก', true),
    ('ropa.activity.read', 'ropa', 'activity', 'R', 'กิจกรรมการประมวลผล (RoPA) — ดู', false),
    ('ropa.activity.update', 'ropa', 'activity', 'U', 'กิจกรรมการประมวลผล (RoPA) — แก้ไข', false),
    ('ropa.dataflow.export', 'ropa', 'dataflow', 'E', 'แผนผังการไหลของข้อมูล — ส่งออก', true),
    ('ropa.dataflow.publish', 'ropa', 'dataflow', 'P', 'แผนผังการไหลของข้อมูล — เผยแพร่ / เปิดใช้งาน', false),
    ('ropa.dataflow.read', 'ropa', 'dataflow', 'R', 'แผนผังการไหลของข้อมูล — ดู', false),
    ('ropa.dataflow.update', 'ropa', 'dataflow', 'U', 'แผนผังการไหลของข้อมูล — แก้ไข', false),
    ('ropa.discovery.create', 'ropa', 'discovery', 'C', 'Data discovery และ connector — สร้าง', false),
    ('ropa.discovery.delete', 'ropa', 'discovery', 'D', 'Data discovery และ connector — ลบ', false),
    ('ropa.discovery.execute', 'ropa', 'discovery', 'X', 'Data discovery และ connector — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('ropa.discovery.read', 'ropa', 'discovery', 'R', 'Data discovery และ connector — ดู', false),
    ('ropa.discovery.update', 'ropa', 'discovery', 'U', 'Data discovery และ connector — แก้ไข', false),
    ('ropa.inventory.approve', 'ropa', 'inventory', 'A', 'ทะเบียนข้อมูลและ asset — อนุมัติ', false),
    ('ropa.inventory.create', 'ropa', 'inventory', 'C', 'ทะเบียนข้อมูลและ asset — สร้าง', false),
    ('ropa.inventory.delete', 'ropa', 'inventory', 'D', 'ทะเบียนข้อมูลและ asset — ลบ', false),
    ('ropa.inventory.read', 'ropa', 'inventory', 'R', 'ทะเบียนข้อมูลและ asset — ดู', false),
    ('ropa.inventory.update', 'ropa', 'inventory', 'U', 'ทะเบียนข้อมูลและ asset — แก้ไข', false),
    ('ropa.risk.approve', 'ropa', 'risk', 'A', 'ความเสี่ยงและช่องว่างรายกิจกรรม — อนุมัติ', false),
    ('ropa.risk.create', 'ropa', 'risk', 'C', 'ความเสี่ยงและช่องว่างรายกิจกรรม — สร้าง', false),
    ('ropa.risk.delete', 'ropa', 'risk', 'D', 'ความเสี่ยงและช่องว่างรายกิจกรรม — ลบ', false),
    ('ropa.risk.read', 'ropa', 'risk', 'R', 'ความเสี่ยงและช่องว่างรายกิจกรรม — ดู', false),
    ('ropa.risk.update', 'ropa', 'risk', 'U', 'ความเสี่ยงและช่องว่างรายกิจกรรม — แก้ไข', false),
    ('ropa.template.create', 'ropa', 'template', 'C', 'คลัง RoPA ฉบับมาตรฐาน — สร้าง', false),
    ('ropa.template.delete', 'ropa', 'template', 'D', 'คลัง RoPA ฉบับมาตรฐาน — ลบ', false),
    ('ropa.template.execute', 'ropa', 'template', 'X', 'คลัง RoPA ฉบับมาตรฐาน — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('ropa.template.publish', 'ropa', 'template', 'P', 'คลัง RoPA ฉบับมาตรฐาน — เผยแพร่ / เปิดใช้งาน', false),
    ('ropa.template.read', 'ropa', 'template', 'R', 'คลัง RoPA ฉบับมาตรฐาน — ดู', false),
    ('ropa.template.update', 'ropa', 'template', 'U', 'คลัง RoPA ฉบับมาตรฐาน — แก้ไข', false),
    ('vendor.assessment.approve', 'vendor', 'assessment', 'A', 'แบบประเมินคู่ค้า — อนุมัติ', false),
    ('vendor.assessment.create', 'vendor', 'assessment', 'C', 'แบบประเมินคู่ค้า — สร้าง', false),
    ('vendor.assessment.delete', 'vendor', 'assessment', 'D', 'แบบประเมินคู่ค้า — ลบ', false),
    ('vendor.assessment.execute', 'vendor', 'assessment', 'X', 'แบบประเมินคู่ค้า — ดำเนินการ / มอบหมาย / ทำรายการ', false),
    ('vendor.assessment.read', 'vendor', 'assessment', 'R', 'แบบประเมินคู่ค้า — ดู', false),
    ('vendor.assessment.update', 'vendor', 'assessment', 'U', 'แบบประเมินคู่ค้า — แก้ไข', false),
    ('vendor.vendor.approve', 'vendor', 'vendor', 'A', 'คู่ค้า / ผู้ประมวลผล — อนุมัติ', false),
    ('vendor.vendor.create', 'vendor', 'vendor', 'C', 'คู่ค้า / ผู้ประมวลผล — สร้าง', false),
    ('vendor.vendor.delete', 'vendor', 'vendor', 'D', 'คู่ค้า / ผู้ประมวลผล — ลบ', false),
    ('vendor.vendor.read', 'vendor', 'vendor', 'R', 'คู่ค้า / ผู้ประมวลผล — ดู', false),
    ('vendor.vendor.update', 'vendor', 'vendor', 'U', 'คู่ค้า / ผู้ประมวลผล — แก้ไข', false);

ALTER TABLE iam.roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.role_permissions NO FORCE ROW LEVEL SECURITY;

INSERT INTO iam.roles (tenant_id, code, name_th, name_en, description, is_system, requires_mfa) VALUES
    (NULL, 'SUPER', 'ผู้ดูแลแพลตฟอร์ม (Super Admin)', 'Platform Super Admin', 'ผู้ให้บริการแพลตฟอร์ม: tenant แพ็กเกจ และค่าระบบ ไม่เห็นข้อมูลธุรกิจของ tenant เว้นแต่ใช้ break-glass (IAM-07) · ขอบเขตเริ่มต้น: ทั้งแพลตฟอร์ม', true, true),
    (NULL, 'ORGADMIN', 'ผู้ดูแลระบบขององค์กร', 'Organization Admin', 'ผู้ดูแลระบบขององค์กร: ผู้ใช้ role โครงสร้างองค์กร SSO และการตั้งค่า · ขอบเขตเริ่มต้น: ทั้ง tenant', true, true),
    (NULL, 'DPO', 'เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล (DPO)', 'DPO', 'เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล ดูแลทุกโมดูลและเป็นผู้อนุมัติหลัก · ขอบเขตเริ่มต้น: tenant / บริษัทที่ได้รับมอบหมาย', true, true),
    (NULL, 'PRIVACY', 'ทีมงาน Privacy', 'Privacy Team', 'ทีมงาน DPO ปฏิบัติงานประจำ แต่ไม่อนุมัติขั้นสุดท้าย · ขอบเขตเริ่มต้น: บริษัทที่ได้รับมอบหมาย', true, true),
    (NULL, 'LEGAL', 'ฝ่ายกฎหมาย', 'Legal', 'ฝ่ายกฎหมาย: ประกาศ template สัญญา DPA/DSA · ขอบเขตเริ่มต้น: ทั้ง tenant', true, false),
    (NULL, 'OWNER', 'เจ้าของกระบวนการ / ผู้ประสานงาน PDPA', 'Process Owner / Champion', 'เจ้าของกระบวนการหรือผู้ประสานงาน PDPA ของแผนก ดูแล RoPA และตอบแบบสอบถาม · ขอบเขตเริ่มต้น: แผนกของตนเอง', true, false),
    (NULL, 'IT', 'เจ้าของระบบ / IT', 'System Owner / IT', 'เจ้าของระบบ/IT: asset, data discovery, งานย่อยของคำขอ, ติดตั้ง script, connector · ขอบเขตเริ่มต้น: ระบบ/แผนกที่ได้รับมอบหมาย', true, false),
    (NULL, 'MKT', 'การตลาด / ธุรกิจ', 'Marketing / Business', 'การตลาด/ธุรกิจ: Purpose, Collection Point และแคมเปญขอความยินยอม · ขอบเขตเริ่มต้น: แผนก/แบรนด์ของตนเอง', true, false),
    (NULL, 'FRONT', 'พนักงานหน้าร้าน / Call center', 'Front Staff', 'พนักงานหน้าร้าน/Call center: บันทึกความยินยอมแทนลูกค้าและรับคำขอใช้สิทธิ · ขอบเขตเริ่มต้น: สาขา/ทีมของตนเอง', true, false),
    (NULL, 'SEC', 'ทีม Security / Incident', 'Security / Incident', 'ทีมความปลอดภัย: เหตุละเมิดและประเมินมาตรการความปลอดภัย · ขอบเขตเริ่มต้น: ทั้ง tenant', true, true),
    (NULL, 'PROC', 'จัดซื้อ / ผู้ดูแลคู่ค้า', 'Procurement / Vendor Manager', 'จัดซื้อ/ผู้ดูแลคู่ค้า: ทะเบียนและการประเมินคู่ค้า · ขอบเขตเริ่มต้น: คู่ค้าที่ตนดูแล', true, false),
    (NULL, 'AUDIT', 'ผู้ตรวจสอบ', 'Auditor', 'ผู้ตรวจสอบภายใน/ภายนอก ดูและส่งออกได้อย่างเดียว · ขอบเขตเริ่มต้น: ทั้ง tenant (อ่านอย่างเดียว)', true, true),
    (NULL, 'EXEC', 'ผู้บริหาร', 'Executive', 'ผู้บริหาร: dashboard รายงาน และยอมรับความเสี่ยง · ขอบเขตเริ่มต้น: ทั้ง tenant (สรุป)', true, false),
    (NULL, 'EMP', 'พนักงานทั่วไป', 'Employee', 'พนักงานทั่วไป: แจ้งเหตุ อบรม รับทราบนโยบาย ขอคำปรึกษา · ขอบเขตเริ่มต้น: ข้อมูลของตนเอง', true, false),
    (NULL, 'GUEST', 'ผู้ใช้ภายนอก (guest link)', 'External Guest', 'คู่ค้า ผู้ประมวลผล หรือผู้ร่วมประเมินภายนอก เข้าผ่าน magic link (IAM-04) · ขอบเขตเริ่มต้น: เฉพาะงานที่ได้รับเชิญ', true, false),
    (NULL, 'API', 'บัญชีระบบ (API client)', 'API Client', 'บัญชีระบบสำหรับเชื่อมต่อ (CRM, POS, แอป) ใช้สิทธิ์ตาม scope · ขอบเขตเริ่มต้น: ระบบที่ผูกไว้', true, false);

INSERT INTO iam.role_permissions (role_id, tenant_id, permission_code)
SELECT r.id, NULL, v.permission_code
FROM (VALUES
    ('API', 'consent.collectionpoint.read'),
    ('API', 'consent.purpose.read'),
    ('API', 'consent.record.create'),
    ('API', 'consent.record.read'),
    ('API', 'dsar.request.create'),
    ('API', 'notice.document.read'),
    ('AUDIT', 'admin.accessreview.read'),
    ('AUDIT', 'admin.apiclient.read'),
    ('AUDIT', 'admin.audit.export'),
    ('AUDIT', 'admin.audit.read'),
    ('AUDIT', 'admin.group.read'),
    ('AUDIT', 'admin.idp.read'),
    ('AUDIT', 'admin.notification.read'),
    ('AUDIT', 'admin.role.read'),
    ('AUDIT', 'admin.scope.read'),
    ('AUDIT', 'admin.user.read'),
    ('AUDIT', 'agreement.clause.read'),
    ('AUDIT', 'agreement.dpa.read'),
    ('AUDIT', 'agreement.dsa.read'),
    ('AUDIT', 'assessment.dpia.read'),
    ('AUDIT', 'assessment.security.read'),
    ('AUDIT', 'assessment.template.read'),
    ('AUDIT', 'assessment.transfer.read'),
    ('AUDIT', 'breach.incident.read'),
    ('AUDIT', 'breach.notification.read'),
    ('AUDIT', 'consent.bulk.export'),
    ('AUDIT', 'consent.campaign.read'),
    ('AUDIT', 'consent.collectionpoint.read'),
    ('AUDIT', 'consent.onbehalf.read'),
    ('AUDIT', 'consent.purpose.read'),
    ('AUDIT', 'consent.record.export'),
    ('AUDIT', 'consent.record.read'),
    ('AUDIT', 'cookie.banner.read'),
    ('AUDIT', 'cookie.scan.read'),
    ('AUDIT', 'dpo.advisory.read'),
    ('AUDIT', 'dpo.kb.read'),
    ('AUDIT', 'dpo.profile.read'),
    ('AUDIT', 'dpo.report.export'),
    ('AUDIT', 'dpo.report.read'),
    ('AUDIT', 'dpo.risk.read'),
    ('AUDIT', 'dpo.task.read'),
    ('AUDIT', 'dpx.ai.read'),
    ('AUDIT', 'dpx.audit.export'),
    ('AUDIT', 'dpx.audit.read'),
    ('AUDIT', 'dpx.integration.read'),
    ('AUDIT', 'dpx.policy.read'),
    ('AUDIT', 'dpx.regulator.read'),
    ('AUDIT', 'dpx.retention.read'),
    ('AUDIT', 'dpx.training.read'),
    ('AUDIT', 'dsar.form.read'),
    ('AUDIT', 'dsar.package.read'),
    ('AUDIT', 'dsar.request.export'),
    ('AUDIT', 'dsar.request.read'),
    ('AUDIT', 'dsar.subtask.read'),
    ('AUDIT', 'notice.document.read'),
    ('AUDIT', 'notice.indirect.read'),
    ('AUDIT', 'notice.template.read'),
    ('AUDIT', 'org.masterdata.read'),
    ('AUDIT', 'org.party.read'),
    ('AUDIT', 'org.settings.read'),
    ('AUDIT', 'org.structure.read'),
    ('AUDIT', 'ropa.activity.export'),
    ('AUDIT', 'ropa.activity.read'),
    ('AUDIT', 'ropa.dataflow.export'),
    ('AUDIT', 'ropa.dataflow.read'),
    ('AUDIT', 'ropa.discovery.read'),
    ('AUDIT', 'ropa.inventory.read'),
    ('AUDIT', 'ropa.risk.read'),
    ('AUDIT', 'ropa.template.read'),
    ('AUDIT', 'vendor.assessment.read'),
    ('AUDIT', 'vendor.vendor.read'),
    ('DPO', 'admin.accessreview.read'),
    ('DPO', 'admin.apiclient.read'),
    ('DPO', 'admin.audit.export'),
    ('DPO', 'admin.audit.read'),
    ('DPO', 'admin.group.create'),
    ('DPO', 'admin.group.read'),
    ('DPO', 'admin.group.update'),
    ('DPO', 'admin.notification.create'),
    ('DPO', 'admin.notification.read'),
    ('DPO', 'admin.notification.update'),
    ('DPO', 'admin.role.read'),
    ('DPO', 'admin.scope.read'),
    ('DPO', 'admin.user.read'),
    ('DPO', 'agreement.clause.read'),
    ('DPO', 'agreement.dpa.approve'),
    ('DPO', 'agreement.dpa.read'),
    ('DPO', 'agreement.dsa.approve'),
    ('DPO', 'agreement.dsa.read'),
    ('DPO', 'assessment.dpia.approve'),
    ('DPO', 'assessment.dpia.create'),
    ('DPO', 'assessment.dpia.delete'),
    ('DPO', 'assessment.dpia.read'),
    ('DPO', 'assessment.dpia.update'),
    ('DPO', 'assessment.security.approve'),
    ('DPO', 'assessment.security.read'),
    ('DPO', 'assessment.template.create'),
    ('DPO', 'assessment.template.delete'),
    ('DPO', 'assessment.template.publish'),
    ('DPO', 'assessment.template.read'),
    ('DPO', 'assessment.template.update'),
    ('DPO', 'assessment.transfer.approve'),
    ('DPO', 'assessment.transfer.create'),
    ('DPO', 'assessment.transfer.delete'),
    ('DPO', 'assessment.transfer.read'),
    ('DPO', 'assessment.transfer.update'),
    ('DPO', 'breach.incident.approve'),
    ('DPO', 'breach.incident.create'),
    ('DPO', 'breach.incident.delete'),
    ('DPO', 'breach.incident.execute'),
    ('DPO', 'breach.incident.read'),
    ('DPO', 'breach.incident.update'),
    ('DPO', 'breach.notification.approve'),
    ('DPO', 'breach.notification.create'),
    ('DPO', 'breach.notification.publish'),
    ('DPO', 'breach.notification.read'),
    ('DPO', 'breach.notification.update'),
    ('DPO', 'consent.bulk.execute'),
    ('DPO', 'consent.bulk.export'),
    ('DPO', 'consent.campaign.approve'),
    ('DPO', 'consent.campaign.create'),
    ('DPO', 'consent.campaign.delete'),
    ('DPO', 'consent.campaign.read'),
    ('DPO', 'consent.campaign.update'),
    ('DPO', 'consent.collectionpoint.approve'),
    ('DPO', 'consent.collectionpoint.create'),
    ('DPO', 'consent.collectionpoint.delete'),
    ('DPO', 'consent.collectionpoint.publish'),
    ('DPO', 'consent.collectionpoint.read'),
    ('DPO', 'consent.collectionpoint.update'),
    ('DPO', 'consent.onbehalf.create'),
    ('DPO', 'consent.onbehalf.read'),
    ('DPO', 'consent.purpose.approve'),
    ('DPO', 'consent.purpose.create'),
    ('DPO', 'consent.purpose.delete'),
    ('DPO', 'consent.purpose.publish'),
    ('DPO', 'consent.purpose.read'),
    ('DPO', 'consent.purpose.update'),
    ('DPO', 'consent.record.export'),
    ('DPO', 'consent.record.read'),
    ('DPO', 'cookie.banner.approve'),
    ('DPO', 'cookie.banner.create'),
    ('DPO', 'cookie.banner.delete'),
    ('DPO', 'cookie.banner.publish'),
    ('DPO', 'cookie.banner.read'),
    ('DPO', 'cookie.banner.update'),
    ('DPO', 'cookie.scan.create'),
    ('DPO', 'cookie.scan.delete'),
    ('DPO', 'cookie.scan.execute'),
    ('DPO', 'cookie.scan.read'),
    ('DPO', 'cookie.scan.update'),
    ('DPO', 'dpo.advisory.execute'),
    ('DPO', 'dpo.advisory.read'),
    ('DPO', 'dpo.advisory.update'),
    ('DPO', 'dpo.kb.create'),
    ('DPO', 'dpo.kb.delete'),
    ('DPO', 'dpo.kb.publish'),
    ('DPO', 'dpo.kb.read'),
    ('DPO', 'dpo.kb.update'),
    ('DPO', 'dpo.profile.create'),
    ('DPO', 'dpo.profile.read'),
    ('DPO', 'dpo.profile.update'),
    ('DPO', 'dpo.report.export'),
    ('DPO', 'dpo.report.read'),
    ('DPO', 'dpo.risk.approve'),
    ('DPO', 'dpo.risk.create'),
    ('DPO', 'dpo.risk.delete'),
    ('DPO', 'dpo.risk.read'),
    ('DPO', 'dpo.risk.update'),
    ('DPO', 'dpo.task.create'),
    ('DPO', 'dpo.task.delete'),
    ('DPO', 'dpo.task.execute'),
    ('DPO', 'dpo.task.read'),
    ('DPO', 'dpo.task.update'),
    ('DPO', 'dpx.ai.approve'),
    ('DPO', 'dpx.ai.create'),
    ('DPO', 'dpx.ai.delete'),
    ('DPO', 'dpx.ai.execute'),
    ('DPO', 'dpx.ai.read'),
    ('DPO', 'dpx.ai.update'),
    ('DPO', 'dpx.audit.approve'),
    ('DPO', 'dpx.audit.create'),
    ('DPO', 'dpx.audit.delete'),
    ('DPO', 'dpx.audit.read'),
    ('DPO', 'dpx.audit.update'),
    ('DPO', 'dpx.integration.read'),
    ('DPO', 'dpx.policy.create'),
    ('DPO', 'dpx.policy.delete'),
    ('DPO', 'dpx.policy.publish'),
    ('DPO', 'dpx.policy.read'),
    ('DPO', 'dpx.policy.update'),
    ('DPO', 'dpx.regulator.create'),
    ('DPO', 'dpx.regulator.delete'),
    ('DPO', 'dpx.regulator.read'),
    ('DPO', 'dpx.regulator.update'),
    ('DPO', 'dpx.retention.approve'),
    ('DPO', 'dpx.retention.create'),
    ('DPO', 'dpx.retention.delete'),
    ('DPO', 'dpx.retention.read'),
    ('DPO', 'dpx.retention.update'),
    ('DPO', 'dpx.training.create'),
    ('DPO', 'dpx.training.delete'),
    ('DPO', 'dpx.training.publish'),
    ('DPO', 'dpx.training.read'),
    ('DPO', 'dpx.training.update'),
    ('DPO', 'dsar.form.create'),
    ('DPO', 'dsar.form.delete'),
    ('DPO', 'dsar.form.publish'),
    ('DPO', 'dsar.form.read'),
    ('DPO', 'dsar.form.update'),
    ('DPO', 'dsar.package.approve'),
    ('DPO', 'dsar.package.create'),
    ('DPO', 'dsar.package.read'),
    ('DPO', 'dsar.request.approve'),
    ('DPO', 'dsar.request.create'),
    ('DPO', 'dsar.request.delete'),
    ('DPO', 'dsar.request.execute'),
    ('DPO', 'dsar.request.export'),
    ('DPO', 'dsar.request.read'),
    ('DPO', 'dsar.request.update'),
    ('DPO', 'dsar.subtask.create'),
    ('DPO', 'dsar.subtask.delete'),
    ('DPO', 'dsar.subtask.execute'),
    ('DPO', 'dsar.subtask.read'),
    ('DPO', 'dsar.subtask.update'),
    ('DPO', 'notice.document.approve'),
    ('DPO', 'notice.document.create'),
    ('DPO', 'notice.document.delete'),
    ('DPO', 'notice.document.publish'),
    ('DPO', 'notice.document.read'),
    ('DPO', 'notice.document.update'),
    ('DPO', 'notice.indirect.create'),
    ('DPO', 'notice.indirect.delete'),
    ('DPO', 'notice.indirect.read'),
    ('DPO', 'notice.indirect.update'),
    ('DPO', 'notice.template.create'),
    ('DPO', 'notice.template.delete'),
    ('DPO', 'notice.template.read'),
    ('DPO', 'notice.template.update'),
    ('DPO', 'org.masterdata.create'),
    ('DPO', 'org.masterdata.delete'),
    ('DPO', 'org.masterdata.read'),
    ('DPO', 'org.masterdata.update'),
    ('DPO', 'org.party.create'),
    ('DPO', 'org.party.delete'),
    ('DPO', 'org.party.read'),
    ('DPO', 'org.party.update'),
    ('DPO', 'org.settings.read'),
    ('DPO', 'org.structure.read'),
    ('DPO', 'org.structure.update'),
    ('DPO', 'pii.unmask.execute'),
    ('DPO', 'ropa.activity.approve'),
    ('DPO', 'ropa.activity.create'),
    ('DPO', 'ropa.activity.delete'),
    ('DPO', 'ropa.activity.export'),
    ('DPO', 'ropa.activity.read'),
    ('DPO', 'ropa.activity.update'),
    ('DPO', 'ropa.dataflow.export'),
    ('DPO', 'ropa.dataflow.publish'),
    ('DPO', 'ropa.dataflow.read'),
    ('DPO', 'ropa.dataflow.update'),
    ('DPO', 'ropa.discovery.read'),
    ('DPO', 'ropa.inventory.approve'),
    ('DPO', 'ropa.inventory.create'),
    ('DPO', 'ropa.inventory.delete'),
    ('DPO', 'ropa.inventory.read'),
    ('DPO', 'ropa.inventory.update'),
    ('DPO', 'ropa.risk.approve'),
    ('DPO', 'ropa.risk.create'),
    ('DPO', 'ropa.risk.delete'),
    ('DPO', 'ropa.risk.read'),
    ('DPO', 'ropa.risk.update'),
    ('DPO', 'ropa.template.create'),
    ('DPO', 'ropa.template.delete'),
    ('DPO', 'ropa.template.publish'),
    ('DPO', 'ropa.template.read'),
    ('DPO', 'ropa.template.update'),
    ('DPO', 'vendor.assessment.approve'),
    ('DPO', 'vendor.assessment.create'),
    ('DPO', 'vendor.assessment.delete'),
    ('DPO', 'vendor.assessment.read'),
    ('DPO', 'vendor.assessment.update'),
    ('DPO', 'vendor.vendor.approve'),
    ('DPO', 'vendor.vendor.create'),
    ('DPO', 'vendor.vendor.delete'),
    ('DPO', 'vendor.vendor.read'),
    ('DPO', 'vendor.vendor.update'),
    ('EMP', 'breach.incident.create'),
    ('EMP', 'dpo.advisory.create'),
    ('EMP', 'dpo.advisory.read'),
    ('EMP', 'dpo.kb.read'),
    ('EMP', 'dpx.policy.execute'),
    ('EMP', 'dpx.training.execute'),
    ('EMP', 'notice.document.read'),
    ('EMP', 'org.structure.read'),
    ('EXEC', 'assessment.dpia.approve'),
    ('EXEC', 'assessment.dpia.read'),
    ('EXEC', 'breach.incident.read'),
    ('EXEC', 'breach.notification.read'),
    ('EXEC', 'dpo.kb.read'),
    ('EXEC', 'dpo.profile.read'),
    ('EXEC', 'dpo.report.export'),
    ('EXEC', 'dpo.report.read'),
    ('EXEC', 'dpo.risk.approve'),
    ('EXEC', 'dpo.risk.read'),
    ('EXEC', 'dpx.audit.read'),
    ('EXEC', 'dpx.policy.execute'),
    ('EXEC', 'dpx.regulator.read'),
    ('EXEC', 'dpx.training.execute'),
    ('EXEC', 'org.structure.read'),
    ('EXEC', 'ropa.activity.read'),
    ('EXEC', 'ropa.dataflow.read'),
    ('EXEC', 'ropa.risk.read'),
    ('FRONT', 'breach.incident.create'),
    ('FRONT', 'consent.onbehalf.create'),
    ('FRONT', 'consent.onbehalf.read'),
    ('FRONT', 'consent.record.read'),
    ('FRONT', 'dpo.kb.read'),
    ('FRONT', 'dpx.policy.execute'),
    ('FRONT', 'dpx.training.execute'),
    ('FRONT', 'dsar.request.create'),
    ('FRONT', 'dsar.request.read'),
    ('FRONT', 'org.structure.read'),
    ('GUEST', 'agreement.dpa.read'),
    ('GUEST', 'agreement.dsa.read'),
    ('GUEST', 'assessment.dpia.read'),
    ('GUEST', 'assessment.dpia.update'),
    ('GUEST', 'breach.incident.create'),
    ('GUEST', 'dsar.subtask.read'),
    ('GUEST', 'dsar.subtask.update'),
    ('GUEST', 'vendor.assessment.read'),
    ('GUEST', 'vendor.assessment.update'),
    ('IT', 'admin.accessreview.execute'),
    ('IT', 'admin.apiclient.create'),
    ('IT', 'admin.apiclient.read'),
    ('IT', 'admin.apiclient.update'),
    ('IT', 'admin.group.read'),
    ('IT', 'assessment.dpia.read'),
    ('IT', 'assessment.dpia.update'),
    ('IT', 'assessment.security.read'),
    ('IT', 'assessment.security.update'),
    ('IT', 'breach.incident.create'),
    ('IT', 'breach.incident.read'),
    ('IT', 'breach.incident.update'),
    ('IT', 'consent.bulk.execute'),
    ('IT', 'consent.collectionpoint.read'),
    ('IT', 'consent.collectionpoint.update'),
    ('IT', 'consent.record.read'),
    ('IT', 'cookie.banner.read'),
    ('IT', 'cookie.banner.update'),
    ('IT', 'cookie.scan.create'),
    ('IT', 'cookie.scan.execute'),
    ('IT', 'cookie.scan.read'),
    ('IT', 'cookie.scan.update'),
    ('IT', 'dpo.advisory.create'),
    ('IT', 'dpo.advisory.read'),
    ('IT', 'dpo.kb.read'),
    ('IT', 'dpo.task.read'),
    ('IT', 'dpo.task.update'),
    ('IT', 'dpx.ai.create'),
    ('IT', 'dpx.ai.read'),
    ('IT', 'dpx.ai.update'),
    ('IT', 'dpx.audit.read'),
    ('IT', 'dpx.audit.update'),
    ('IT', 'dpx.integration.create'),
    ('IT', 'dpx.integration.delete'),
    ('IT', 'dpx.integration.read'),
    ('IT', 'dpx.integration.update'),
    ('IT', 'dpx.policy.execute'),
    ('IT', 'dpx.retention.execute'),
    ('IT', 'dpx.retention.read'),
    ('IT', 'dpx.retention.update'),
    ('IT', 'dpx.training.execute'),
    ('IT', 'dsar.package.create'),
    ('IT', 'dsar.package.update'),
    ('IT', 'dsar.request.read'),
    ('IT', 'dsar.subtask.read'),
    ('IT', 'dsar.subtask.update'),
    ('IT', 'notice.document.read'),
    ('IT', 'org.masterdata.read'),
    ('IT', 'org.party.read'),
    ('IT', 'org.structure.read'),
    ('IT', 'ropa.activity.read'),
    ('IT', 'ropa.dataflow.read'),
    ('IT', 'ropa.discovery.create'),
    ('IT', 'ropa.discovery.delete'),
    ('IT', 'ropa.discovery.execute'),
    ('IT', 'ropa.discovery.read'),
    ('IT', 'ropa.discovery.update'),
    ('IT', 'ropa.inventory.create'),
    ('IT', 'ropa.inventory.read'),
    ('IT', 'ropa.inventory.update'),
    ('IT', 'vendor.vendor.read'),
    ('LEGAL', 'agreement.clause.create'),
    ('LEGAL', 'agreement.clause.delete'),
    ('LEGAL', 'agreement.clause.publish'),
    ('LEGAL', 'agreement.clause.read'),
    ('LEGAL', 'agreement.clause.update'),
    ('LEGAL', 'agreement.dpa.approve'),
    ('LEGAL', 'agreement.dpa.create'),
    ('LEGAL', 'agreement.dpa.delete'),
    ('LEGAL', 'agreement.dpa.publish'),
    ('LEGAL', 'agreement.dpa.read'),
    ('LEGAL', 'agreement.dpa.update'),
    ('LEGAL', 'agreement.dsa.approve'),
    ('LEGAL', 'agreement.dsa.create'),
    ('LEGAL', 'agreement.dsa.delete'),
    ('LEGAL', 'agreement.dsa.publish'),
    ('LEGAL', 'agreement.dsa.read'),
    ('LEGAL', 'agreement.dsa.update'),
    ('LEGAL', 'assessment.dpia.read'),
    ('LEGAL', 'assessment.dpia.update'),
    ('LEGAL', 'assessment.template.create'),
    ('LEGAL', 'assessment.template.read'),
    ('LEGAL', 'assessment.template.update'),
    ('LEGAL', 'assessment.transfer.read'),
    ('LEGAL', 'assessment.transfer.update'),
    ('LEGAL', 'breach.incident.read'),
    ('LEGAL', 'breach.incident.update'),
    ('LEGAL', 'breach.notification.read'),
    ('LEGAL', 'breach.notification.update'),
    ('LEGAL', 'consent.purpose.read'),
    ('LEGAL', 'consent.purpose.update'),
    ('LEGAL', 'cookie.banner.read'),
    ('LEGAL', 'dpo.advisory.read'),
    ('LEGAL', 'dpo.advisory.update'),
    ('LEGAL', 'dpo.kb.create'),
    ('LEGAL', 'dpo.kb.read'),
    ('LEGAL', 'dpo.kb.update'),
    ('LEGAL', 'dpo.profile.read'),
    ('LEGAL', 'dpo.report.read'),
    ('LEGAL', 'dpo.task.read'),
    ('LEGAL', 'dpo.task.update'),
    ('LEGAL', 'dpx.ai.execute'),
    ('LEGAL', 'dpx.policy.create'),
    ('LEGAL', 'dpx.policy.read'),
    ('LEGAL', 'dpx.policy.update'),
    ('LEGAL', 'dpx.regulator.create'),
    ('LEGAL', 'dpx.regulator.read'),
    ('LEGAL', 'dpx.regulator.update'),
    ('LEGAL', 'dpx.training.execute'),
    ('LEGAL', 'dsar.form.read'),
    ('LEGAL', 'dsar.form.update'),
    ('LEGAL', 'dsar.request.read'),
    ('LEGAL', 'dsar.request.update'),
    ('LEGAL', 'dsar.subtask.read'),
    ('LEGAL', 'dsar.subtask.update'),
    ('LEGAL', 'notice.document.approve'),
    ('LEGAL', 'notice.document.create'),
    ('LEGAL', 'notice.document.read'),
    ('LEGAL', 'notice.document.update'),
    ('LEGAL', 'notice.template.create'),
    ('LEGAL', 'notice.template.delete'),
    ('LEGAL', 'notice.template.read'),
    ('LEGAL', 'notice.template.update'),
    ('LEGAL', 'org.masterdata.read'),
    ('LEGAL', 'org.party.create'),
    ('LEGAL', 'org.party.read'),
    ('LEGAL', 'org.party.update'),
    ('LEGAL', 'org.structure.read'),
    ('LEGAL', 'ropa.activity.read'),
    ('LEGAL', 'ropa.dataflow.read'),
    ('LEGAL', 'ropa.inventory.read'),
    ('LEGAL', 'ropa.template.create'),
    ('LEGAL', 'ropa.template.read'),
    ('LEGAL', 'ropa.template.update'),
    ('LEGAL', 'vendor.vendor.read'),
    ('MKT', 'admin.notification.create'),
    ('MKT', 'admin.notification.read'),
    ('MKT', 'admin.notification.update'),
    ('MKT', 'breach.incident.create'),
    ('MKT', 'consent.bulk.export'),
    ('MKT', 'consent.campaign.create'),
    ('MKT', 'consent.campaign.execute'),
    ('MKT', 'consent.campaign.read'),
    ('MKT', 'consent.campaign.update'),
    ('MKT', 'consent.collectionpoint.create'),
    ('MKT', 'consent.collectionpoint.read'),
    ('MKT', 'consent.collectionpoint.update'),
    ('MKT', 'consent.purpose.create'),
    ('MKT', 'consent.purpose.read'),
    ('MKT', 'consent.purpose.update'),
    ('MKT', 'consent.record.read'),
    ('MKT', 'cookie.banner.read'),
    ('MKT', 'cookie.scan.read'),
    ('MKT', 'dpo.advisory.create'),
    ('MKT', 'dpo.advisory.read'),
    ('MKT', 'dpo.kb.read'),
    ('MKT', 'dpx.policy.execute'),
    ('MKT', 'dpx.training.execute'),
    ('MKT', 'notice.document.read'),
    ('MKT', 'notice.indirect.create'),
    ('MKT', 'notice.indirect.read'),
    ('MKT', 'notice.indirect.update'),
    ('MKT', 'org.masterdata.read'),
    ('MKT', 'org.structure.read'),
    ('MKT', 'ropa.activity.read'),
    ('ORGADMIN', 'admin.accessreview.create'),
    ('ORGADMIN', 'admin.accessreview.delete'),
    ('ORGADMIN', 'admin.accessreview.execute'),
    ('ORGADMIN', 'admin.accessreview.read'),
    ('ORGADMIN', 'admin.accessreview.update'),
    ('ORGADMIN', 'admin.apiclient.create'),
    ('ORGADMIN', 'admin.apiclient.delete'),
    ('ORGADMIN', 'admin.apiclient.read'),
    ('ORGADMIN', 'admin.apiclient.update'),
    ('ORGADMIN', 'admin.audit.export'),
    ('ORGADMIN', 'admin.audit.read'),
    ('ORGADMIN', 'admin.breakglass.execute'),
    ('ORGADMIN', 'admin.group.create'),
    ('ORGADMIN', 'admin.group.delete'),
    ('ORGADMIN', 'admin.group.read'),
    ('ORGADMIN', 'admin.group.update'),
    ('ORGADMIN', 'admin.idp.create'),
    ('ORGADMIN', 'admin.idp.delete'),
    ('ORGADMIN', 'admin.idp.read'),
    ('ORGADMIN', 'admin.idp.update'),
    ('ORGADMIN', 'admin.notification.create'),
    ('ORGADMIN', 'admin.notification.delete'),
    ('ORGADMIN', 'admin.notification.read'),
    ('ORGADMIN', 'admin.notification.update'),
    ('ORGADMIN', 'admin.role.approve'),
    ('ORGADMIN', 'admin.role.create'),
    ('ORGADMIN', 'admin.role.delete'),
    ('ORGADMIN', 'admin.role.read'),
    ('ORGADMIN', 'admin.role.update'),
    ('ORGADMIN', 'admin.scope.create'),
    ('ORGADMIN', 'admin.scope.delete'),
    ('ORGADMIN', 'admin.scope.read'),
    ('ORGADMIN', 'admin.scope.update'),
    ('ORGADMIN', 'admin.user.create'),
    ('ORGADMIN', 'admin.user.delete'),
    ('ORGADMIN', 'admin.user.read'),
    ('ORGADMIN', 'admin.user.update'),
    ('ORGADMIN', 'dpo.profile.read'),
    ('ORGADMIN', 'dpo.profile.update'),
    ('ORGADMIN', 'dpo.report.read'),
    ('ORGADMIN', 'dpx.integration.create'),
    ('ORGADMIN', 'dpx.integration.delete'),
    ('ORGADMIN', 'dpx.integration.read'),
    ('ORGADMIN', 'dpx.integration.update'),
    ('ORGADMIN', 'dpx.training.read'),
    ('ORGADMIN', 'org.masterdata.create'),
    ('ORGADMIN', 'org.masterdata.delete'),
    ('ORGADMIN', 'org.masterdata.read'),
    ('ORGADMIN', 'org.masterdata.update'),
    ('ORGADMIN', 'org.party.create'),
    ('ORGADMIN', 'org.party.delete'),
    ('ORGADMIN', 'org.party.read'),
    ('ORGADMIN', 'org.party.update'),
    ('ORGADMIN', 'org.settings.read'),
    ('ORGADMIN', 'org.settings.update'),
    ('ORGADMIN', 'org.structure.create'),
    ('ORGADMIN', 'org.structure.delete'),
    ('ORGADMIN', 'org.structure.read'),
    ('ORGADMIN', 'org.structure.update'),
    ('OWNER', 'admin.accessreview.execute'),
    ('OWNER', 'admin.group.read'),
    ('OWNER', 'agreement.dpa.read'),
    ('OWNER', 'agreement.dsa.read'),
    ('OWNER', 'assessment.dpia.read'),
    ('OWNER', 'assessment.dpia.update'),
    ('OWNER', 'breach.incident.create'),
    ('OWNER', 'dpo.advisory.create'),
    ('OWNER', 'dpo.advisory.read'),
    ('OWNER', 'dpo.kb.read'),
    ('OWNER', 'dpo.risk.read'),
    ('OWNER', 'dpo.task.read'),
    ('OWNER', 'dpo.task.update'),
    ('OWNER', 'dpx.audit.read'),
    ('OWNER', 'dpx.audit.update'),
    ('OWNER', 'dpx.policy.execute'),
    ('OWNER', 'dpx.retention.read'),
    ('OWNER', 'dpx.training.execute'),
    ('OWNER', 'dsar.request.read'),
    ('OWNER', 'dsar.subtask.read'),
    ('OWNER', 'dsar.subtask.update'),
    ('OWNER', 'notice.document.read'),
    ('OWNER', 'notice.indirect.create'),
    ('OWNER', 'notice.indirect.read'),
    ('OWNER', 'notice.indirect.update'),
    ('OWNER', 'org.masterdata.read'),
    ('OWNER', 'org.party.read'),
    ('OWNER', 'org.structure.read'),
    ('OWNER', 'ropa.activity.create'),
    ('OWNER', 'ropa.activity.read'),
    ('OWNER', 'ropa.activity.update'),
    ('OWNER', 'ropa.dataflow.read'),
    ('OWNER', 'ropa.inventory.create'),
    ('OWNER', 'ropa.inventory.read'),
    ('OWNER', 'ropa.inventory.update'),
    ('OWNER', 'ropa.risk.read'),
    ('OWNER', 'ropa.risk.update'),
    ('OWNER', 'ropa.template.execute'),
    ('OWNER', 'ropa.template.read'),
    ('OWNER', 'vendor.vendor.create'),
    ('OWNER', 'vendor.vendor.read'),
    ('PRIVACY', 'admin.group.read'),
    ('PRIVACY', 'admin.notification.create'),
    ('PRIVACY', 'admin.notification.read'),
    ('PRIVACY', 'admin.notification.update'),
    ('PRIVACY', 'agreement.dpa.read'),
    ('PRIVACY', 'agreement.dsa.read'),
    ('PRIVACY', 'assessment.dpia.create'),
    ('PRIVACY', 'assessment.dpia.read'),
    ('PRIVACY', 'assessment.dpia.update'),
    ('PRIVACY', 'assessment.security.read'),
    ('PRIVACY', 'assessment.template.create'),
    ('PRIVACY', 'assessment.template.read'),
    ('PRIVACY', 'assessment.template.update'),
    ('PRIVACY', 'assessment.transfer.create'),
    ('PRIVACY', 'assessment.transfer.read'),
    ('PRIVACY', 'assessment.transfer.update'),
    ('PRIVACY', 'breach.incident.create'),
    ('PRIVACY', 'breach.incident.execute'),
    ('PRIVACY', 'breach.incident.read'),
    ('PRIVACY', 'breach.incident.update'),
    ('PRIVACY', 'breach.notification.create'),
    ('PRIVACY', 'breach.notification.read'),
    ('PRIVACY', 'breach.notification.update'),
    ('PRIVACY', 'consent.bulk.execute'),
    ('PRIVACY', 'consent.bulk.export'),
    ('PRIVACY', 'consent.campaign.create'),
    ('PRIVACY', 'consent.campaign.read'),
    ('PRIVACY', 'consent.campaign.update'),
    ('PRIVACY', 'consent.collectionpoint.create'),
    ('PRIVACY', 'consent.collectionpoint.read'),
    ('PRIVACY', 'consent.collectionpoint.update'),
    ('PRIVACY', 'consent.onbehalf.create'),
    ('PRIVACY', 'consent.onbehalf.read'),
    ('PRIVACY', 'consent.purpose.create'),
    ('PRIVACY', 'consent.purpose.read'),
    ('PRIVACY', 'consent.purpose.update'),
    ('PRIVACY', 'consent.record.export'),
    ('PRIVACY', 'consent.record.read'),
    ('PRIVACY', 'cookie.banner.create'),
    ('PRIVACY', 'cookie.banner.read'),
    ('PRIVACY', 'cookie.banner.update'),
    ('PRIVACY', 'cookie.scan.create'),
    ('PRIVACY', 'cookie.scan.execute'),
    ('PRIVACY', 'cookie.scan.read'),
    ('PRIVACY', 'cookie.scan.update'),
    ('PRIVACY', 'dpo.advisory.execute'),
    ('PRIVACY', 'dpo.advisory.read'),
    ('PRIVACY', 'dpo.advisory.update'),
    ('PRIVACY', 'dpo.kb.create'),
    ('PRIVACY', 'dpo.kb.read'),
    ('PRIVACY', 'dpo.kb.update'),
    ('PRIVACY', 'dpo.report.export'),
    ('PRIVACY', 'dpo.report.read'),
    ('PRIVACY', 'dpo.risk.create'),
    ('PRIVACY', 'dpo.risk.read'),
    ('PRIVACY', 'dpo.risk.update'),
    ('PRIVACY', 'dpo.task.create'),
    ('PRIVACY', 'dpo.task.execute'),
    ('PRIVACY', 'dpo.task.read'),
    ('PRIVACY', 'dpo.task.update'),
    ('PRIVACY', 'dpx.ai.create'),
    ('PRIVACY', 'dpx.ai.execute'),
    ('PRIVACY', 'dpx.ai.read'),
    ('PRIVACY', 'dpx.ai.update'),
    ('PRIVACY', 'dpx.audit.create'),
    ('PRIVACY', 'dpx.audit.read'),
    ('PRIVACY', 'dpx.audit.update'),
    ('PRIVACY', 'dpx.regulator.read'),
    ('PRIVACY', 'dpx.retention.create'),
    ('PRIVACY', 'dpx.retention.read'),
    ('PRIVACY', 'dpx.retention.update'),
    ('PRIVACY', 'dpx.training.create'),
    ('PRIVACY', 'dpx.training.read'),
    ('PRIVACY', 'dpx.training.update'),
    ('PRIVACY', 'dsar.form.create'),
    ('PRIVACY', 'dsar.form.read'),
    ('PRIVACY', 'dsar.form.update'),
    ('PRIVACY', 'dsar.package.create'),
    ('PRIVACY', 'dsar.package.read'),
    ('PRIVACY', 'dsar.request.create'),
    ('PRIVACY', 'dsar.request.execute'),
    ('PRIVACY', 'dsar.request.read'),
    ('PRIVACY', 'dsar.request.update'),
    ('PRIVACY', 'dsar.subtask.create'),
    ('PRIVACY', 'dsar.subtask.execute'),
    ('PRIVACY', 'dsar.subtask.read'),
    ('PRIVACY', 'dsar.subtask.update'),
    ('PRIVACY', 'notice.document.create'),
    ('PRIVACY', 'notice.document.read'),
    ('PRIVACY', 'notice.document.update'),
    ('PRIVACY', 'notice.indirect.create'),
    ('PRIVACY', 'notice.indirect.read'),
    ('PRIVACY', 'notice.indirect.update'),
    ('PRIVACY', 'notice.template.read'),
    ('PRIVACY', 'org.masterdata.create'),
    ('PRIVACY', 'org.masterdata.read'),
    ('PRIVACY', 'org.masterdata.update'),
    ('PRIVACY', 'org.party.create'),
    ('PRIVACY', 'org.party.read'),
    ('PRIVACY', 'org.party.update'),
    ('PRIVACY', 'org.structure.read'),
    ('PRIVACY', 'pii.unmask.execute'),
    ('PRIVACY', 'ropa.activity.create'),
    ('PRIVACY', 'ropa.activity.export'),
    ('PRIVACY', 'ropa.activity.read'),
    ('PRIVACY', 'ropa.activity.update'),
    ('PRIVACY', 'ropa.dataflow.export'),
    ('PRIVACY', 'ropa.dataflow.read'),
    ('PRIVACY', 'ropa.dataflow.update'),
    ('PRIVACY', 'ropa.discovery.read'),
    ('PRIVACY', 'ropa.inventory.create'),
    ('PRIVACY', 'ropa.inventory.delete'),
    ('PRIVACY', 'ropa.inventory.read'),
    ('PRIVACY', 'ropa.inventory.update'),
    ('PRIVACY', 'ropa.risk.create'),
    ('PRIVACY', 'ropa.risk.read'),
    ('PRIVACY', 'ropa.risk.update'),
    ('PRIVACY', 'ropa.template.create'),
    ('PRIVACY', 'ropa.template.read'),
    ('PRIVACY', 'ropa.template.update'),
    ('PRIVACY', 'vendor.assessment.create'),
    ('PRIVACY', 'vendor.assessment.execute'),
    ('PRIVACY', 'vendor.assessment.read'),
    ('PRIVACY', 'vendor.assessment.update'),
    ('PRIVACY', 'vendor.vendor.create'),
    ('PRIVACY', 'vendor.vendor.read'),
    ('PRIVACY', 'vendor.vendor.update'),
    ('PROC', 'agreement.dpa.create'),
    ('PROC', 'agreement.dpa.read'),
    ('PROC', 'dpo.kb.read'),
    ('PROC', 'dpx.policy.execute'),
    ('PROC', 'dpx.training.execute'),
    ('PROC', 'org.party.create'),
    ('PROC', 'org.party.read'),
    ('PROC', 'org.party.update'),
    ('PROC', 'org.structure.read'),
    ('PROC', 'vendor.assessment.create'),
    ('PROC', 'vendor.assessment.execute'),
    ('PROC', 'vendor.assessment.read'),
    ('PROC', 'vendor.assessment.update'),
    ('PROC', 'vendor.vendor.create'),
    ('PROC', 'vendor.vendor.delete'),
    ('PROC', 'vendor.vendor.read'),
    ('PROC', 'vendor.vendor.update'),
    ('SEC', 'admin.audit.export'),
    ('SEC', 'admin.audit.read'),
    ('SEC', 'admin.group.read'),
    ('SEC', 'admin.idp.read'),
    ('SEC', 'assessment.dpia.read'),
    ('SEC', 'assessment.dpia.update'),
    ('SEC', 'assessment.security.create'),
    ('SEC', 'assessment.security.delete'),
    ('SEC', 'assessment.security.execute'),
    ('SEC', 'assessment.security.read'),
    ('SEC', 'assessment.security.update'),
    ('SEC', 'assessment.template.create'),
    ('SEC', 'assessment.template.read'),
    ('SEC', 'assessment.template.update'),
    ('SEC', 'breach.incident.create'),
    ('SEC', 'breach.incident.execute'),
    ('SEC', 'breach.incident.read'),
    ('SEC', 'breach.incident.update'),
    ('SEC', 'breach.notification.read'),
    ('SEC', 'dpo.kb.read'),
    ('SEC', 'dpo.report.read'),
    ('SEC', 'dpo.risk.create'),
    ('SEC', 'dpo.risk.read'),
    ('SEC', 'dpo.risk.update'),
    ('SEC', 'dpo.task.read'),
    ('SEC', 'dpo.task.update'),
    ('SEC', 'dpx.ai.read'),
    ('SEC', 'dpx.audit.read'),
    ('SEC', 'dpx.audit.update'),
    ('SEC', 'dpx.integration.read'),
    ('SEC', 'dpx.policy.execute'),
    ('SEC', 'dpx.training.execute'),
    ('SEC', 'org.masterdata.read'),
    ('SEC', 'org.structure.read'),
    ('SEC', 'pii.unmask.execute'),
    ('SEC', 'ropa.activity.read'),
    ('SEC', 'ropa.dataflow.read'),
    ('SEC', 'ropa.discovery.read'),
    ('SEC', 'ropa.inventory.read'),
    ('SEC', 'ropa.risk.read'),
    ('SEC', 'ropa.risk.update'),
    ('SEC', 'vendor.assessment.execute'),
    ('SEC', 'vendor.assessment.read'),
    ('SEC', 'vendor.assessment.update'),
    ('SEC', 'vendor.vendor.read'),
    ('SEC', 'vendor.vendor.update'),
    ('SUPER', 'admin.audit.export'),
    ('SUPER', 'admin.audit.read'),
    ('SUPER', 'admin.breakglass.execute'),
    ('SUPER', 'admin.tenant.create'),
    ('SUPER', 'admin.tenant.delete'),
    ('SUPER', 'admin.tenant.read'),
    ('SUPER', 'admin.tenant.update'),
    ('SUPER', 'admin.user.create'),
    ('SUPER', 'org.masterdata.create'),
    ('SUPER', 'org.masterdata.delete'),
    ('SUPER', 'org.masterdata.read'),
    ('SUPER', 'org.masterdata.update'),
    ('SUPER', 'org.settings.create'),
    ('SUPER', 'org.settings.delete'),
    ('SUPER', 'org.settings.read'),
    ('SUPER', 'org.settings.update'),
    ('SUPER', 'ropa.template.create'),
    ('SUPER', 'ropa.template.delete'),
    ('SUPER', 'ropa.template.read'),
    ('SUPER', 'ropa.template.update')
) AS v(role_code, permission_code)
JOIN iam.roles r ON r.tenant_id IS NULL AND r.code = v.role_code;

ALTER TABLE iam.roles FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.role_permissions FORCE ROW LEVEL SECURITY;

-- +goose Down
ALTER TABLE iam.roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.role_permissions NO FORCE ROW LEVEL SECURITY;
DELETE FROM iam.role_permissions WHERE tenant_id IS NULL AND role_id IN (SELECT id FROM iam.roles WHERE tenant_id IS NULL AND is_system);
DELETE FROM iam.roles WHERE tenant_id IS NULL AND is_system;
DELETE FROM iam.permissions;
ALTER TABLE iam.roles FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.role_permissions FORCE ROW LEVEL SECURITY;
