-- +goose Up
-- ORG-07: the default Thai master data every tenant sees (tenant_id NULL rows / global tables).
-- DRAFT pending legal review (docs/decisions.md Q-20): lawful bases paraphrase PDPA ss.19, 24 and 26; sensitive
-- categories follow s.26; countries are ISO 3166-1 with names from Unicode CLDR and adequacy_status 'unknown'
-- (no adequacy list has been adopted into this system). Global rows need RLS force lifted inside this migration,
-- as in 00019 (restored before commit); lawful_bases and countries have no RLS.
INSERT INTO org.lawful_bases (code, section_ref, name_th, name_en, for_sensitive, requires_consent, requires_lia) VALUES
    ('CONSENT', 'ม.19, ม.24', 'ความยินยอมของเจ้าของข้อมูล', 'Consent of the data subject', false, true, false),
    ('RESEARCH', 'ม.24(1)', 'การจัดทำเอกสารประวัติศาสตร์ จดหมายเหตุ การศึกษาวิจัย หรือสถิติ', 'Historical documents, archives, research or statistics', false, false, false),
    ('VITAL_INTEREST', 'ม.24(2)', 'ป้องกันหรือระงับอันตรายต่อชีวิต ร่างกาย หรือสุขภาพ', 'Preventing or suppressing a danger to life, body or health', false, false, false),
    ('CONTRACT', 'ม.24(3)', 'จำเป็นเพื่อปฏิบัติตามสัญญาหรือดำเนินการตามคำขอก่อนเข้าทำสัญญา', 'Necessary for a contract or pre-contract steps at the data subject''s request', false, false, false),
    ('PUBLIC_TASK', 'ม.24(4)', 'ภารกิจเพื่อประโยชน์สาธารณะหรือการใช้อำนาจรัฐ', 'Public-interest task or exercise of official authority', false, false, false),
    ('LEGITIMATE_INTEREST', 'ม.24(5)', 'ประโยชน์โดยชอบด้วยกฎหมายของผู้ควบคุมข้อมูลหรือบุคคลอื่น', 'Legitimate interests of the controller or another person', false, false, true),
    ('LEGAL_OBLIGATION', 'ม.24(6)', 'ปฏิบัติตามกฎหมายที่ผู้ควบคุมข้อมูลต้องปฏิบัติ', 'Compliance with a legal obligation of the controller', false, false, false),
    ('EXPLICIT_CONSENT', 'ม.26 วรรคหนึ่ง', 'ความยินยอมโดยชัดแจ้ง (ข้อมูลอ่อนไหว)', 'Explicit consent (sensitive data)', true, true, false),
    ('S26_VITAL', 'ม.26(1)', 'ป้องกันอันตรายต่อชีวิต ร่างกาย หรือสุขภาพ เมื่อเจ้าของข้อมูลไม่สามารถให้ความยินยอมได้', 'Danger to life, body or health when consent can''t be given', true, false, false),
    ('S26_NONPROFIT', 'ม.26(2)', 'กิจกรรมโดยชอบของมูลนิธิ สมาคม หรือองค์กรไม่แสวงหากำไร ต่อสมาชิก', 'Legitimate activities of a foundation, association or non-profit for its members', true, false, false),
    ('S26_PUBLIC', 'ม.26(3)', 'ข้อมูลที่เปิดเผยต่อสาธารณะด้วยความยินยอมโดยชัดแจ้งของเจ้าของข้อมูล', 'Data made public with the data subject''s explicit consent', true, false, false),
    ('S26_LEGAL_CLAIMS', 'ม.26(4)', 'การก่อตั้ง ใช้ หรือยกขึ้นต่อสู้ซึ่งสิทธิเรียกร้องตามกฎหมาย', 'Establishing, exercising or defending legal claims', true, false, false),
    ('S26_LAW', 'ม.26(5)', 'จำเป็นเพื่อปฏิบัติตามกฎหมายตามที่ ม.26(5)(ก)–(จ) กำหนด', 'Necessary for legal obligations listed in s.26(5)(a)–(e)', true, false, false);

INSERT INTO org.countries (code, name_th, name_en) VALUES
    ('AD', 'อันดอร์รา', 'Andorra'),
    ('AE', 'สหรัฐอาหรับเอมิเรตส์', 'United Arab Emirates'),
    ('AF', 'อัฟกานิสถาน', 'Afghanistan'),
    ('AG', 'แอนติกาและบาร์บูดา', 'Antigua & Barbuda'),
    ('AI', 'แองกวิลลา', 'Anguilla'),
    ('AL', 'แอลเบเนีย', 'Albania'),
    ('AM', 'อาร์เมเนีย', 'Armenia'),
    ('AO', 'แองโกลา', 'Angola'),
    ('AQ', 'แอนตาร์กติกา', 'Antarctica'),
    ('AR', 'อาร์เจนตินา', 'Argentina'),
    ('AS', 'อเมริกันซามัว', 'American Samoa'),
    ('AT', 'ออสเตรีย', 'Austria'),
    ('AU', 'ออสเตรเลีย', 'Australia'),
    ('AW', 'อารูบา', 'Aruba'),
    ('AX', 'หมู่เกาะโอลันด์', 'Åland Islands'),
    ('AZ', 'อาเซอร์ไบจาน', 'Azerbaijan'),
    ('BA', 'บอสเนียและเฮอร์เซโกวีนา', 'Bosnia & Herzegovina'),
    ('BB', 'บาร์เบโดส', 'Barbados'),
    ('BD', 'บังกลาเทศ', 'Bangladesh'),
    ('BE', 'เบลเยียม', 'Belgium'),
    ('BF', 'บูร์กินาฟาโซ', 'Burkina Faso'),
    ('BG', 'บัลแกเรีย', 'Bulgaria'),
    ('BH', 'บาห์เรน', 'Bahrain'),
    ('BI', 'บุรุนดี', 'Burundi'),
    ('BJ', 'เบนิน', 'Benin'),
    ('BL', 'เซนต์บาร์เธเลมี', 'St. Barthélemy'),
    ('BM', 'เบอร์มิวดา', 'Bermuda'),
    ('BN', 'บรูไน', 'Brunei'),
    ('BO', 'โบลิเวีย', 'Bolivia'),
    ('BQ', 'เนเธอร์แลนด์แคริบเบียน', 'Caribbean Netherlands'),
    ('BR', 'บราซิล', 'Brazil'),
    ('BS', 'บาฮามาส', 'Bahamas'),
    ('BT', 'ภูฏาน', 'Bhutan'),
    ('BV', 'เกาะบูเว', 'Bouvet Island'),
    ('BW', 'บอตสวานา', 'Botswana'),
    ('BY', 'เบลารุส', 'Belarus'),
    ('BZ', 'เบลีซ', 'Belize'),
    ('CA', 'แคนาดา', 'Canada'),
    ('CC', 'หมู่เกาะโคโคส (คีลิง)', 'Cocos (Keeling) Islands'),
    ('CD', 'คองโก - กินชาซา', 'Congo - Kinshasa'),
    ('CF', 'สาธารณรัฐแอฟริกากลาง', 'Central African Republic'),
    ('CG', 'คองโก - บราซซาวิล', 'Congo - Brazzaville'),
    ('CH', 'สวิตเซอร์แลนด์', 'Switzerland'),
    ('CI', 'โกตดิวัวร์', 'Côte d’Ivoire'),
    ('CK', 'หมู่เกาะคุก', 'Cook Islands'),
    ('CL', 'ชิลี', 'Chile'),
    ('CM', 'แคเมอรูน', 'Cameroon'),
    ('CN', 'จีน', 'China'),
    ('CO', 'โคลอมเบีย', 'Colombia'),
    ('CR', 'คอสตาริกา', 'Costa Rica'),
    ('CU', 'คิวบา', 'Cuba'),
    ('CV', 'เคปเวิร์ด', 'Cape Verde'),
    ('CW', 'คูราเซา', 'Curaçao'),
    ('CX', 'เกาะคริสต์มาส', 'Christmas Island'),
    ('CY', 'ไซปรัส', 'Cyprus'),
    ('CZ', 'เช็ก', 'Czechia'),
    ('DE', 'เยอรมนี', 'Germany'),
    ('DJ', 'จิบูตี', 'Djibouti'),
    ('DK', 'เดนมาร์ก', 'Denmark'),
    ('DM', 'โดมินิกา', 'Dominica'),
    ('DO', 'สาธารณรัฐโดมินิกัน', 'Dominican Republic'),
    ('DZ', 'แอลจีเรีย', 'Algeria'),
    ('EC', 'เอกวาดอร์', 'Ecuador'),
    ('EE', 'เอสโตเนีย', 'Estonia'),
    ('EG', 'อียิปต์', 'Egypt'),
    ('EH', 'ซาฮาราตะวันตก', 'Western Sahara'),
    ('ER', 'เอริเทรีย', 'Eritrea'),
    ('ES', 'สเปน', 'Spain'),
    ('ET', 'เอธิโอเปีย', 'Ethiopia'),
    ('FI', 'ฟินแลนด์', 'Finland'),
    ('FJ', 'ฟิจิ', 'Fiji'),
    ('FK', 'หมู่เกาะฟอล์กแลนด์', 'Falkland Islands'),
    ('FM', 'ไมโครนีเซีย', 'Micronesia'),
    ('FO', 'หมู่เกาะแฟโร', 'Faroe Islands'),
    ('FR', 'ฝรั่งเศส', 'France'),
    ('GA', 'กาบอง', 'Gabon'),
    ('GB', 'สหราชอาณาจักร', 'United Kingdom'),
    ('GD', 'เกรเนดา', 'Grenada'),
    ('GE', 'จอร์เจีย', 'Georgia'),
    ('GF', 'เฟรนช์เกียนา', 'French Guiana'),
    ('GG', 'เกิร์นซีย์', 'Guernsey'),
    ('GH', 'กานา', 'Ghana'),
    ('GI', 'ยิบรอลตาร์', 'Gibraltar'),
    ('GL', 'กรีนแลนด์', 'Greenland'),
    ('GM', 'แกมเบีย', 'Gambia'),
    ('GN', 'กินี', 'Guinea'),
    ('GP', 'กวาเดอลูป', 'Guadeloupe'),
    ('GQ', 'อิเควทอเรียลกินี', 'Equatorial Guinea'),
    ('GR', 'กรีซ', 'Greece'),
    ('GS', 'เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช', 'South Georgia & South Sandwich Islands'),
    ('GT', 'กัวเตมาลา', 'Guatemala'),
    ('GU', 'กวม', 'Guam'),
    ('GW', 'กินี-บิสเซา', 'Guinea-Bissau'),
    ('GY', 'กายอานา', 'Guyana'),
    ('HK', 'เขตปกครองพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน', 'Hong Kong SAR China'),
    ('HM', 'เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์', 'Heard & McDonald Islands'),
    ('HN', 'ฮอนดูรัส', 'Honduras'),
    ('HR', 'โครเอเชีย', 'Croatia'),
    ('HT', 'เฮติ', 'Haiti'),
    ('HU', 'ฮังการี', 'Hungary'),
    ('ID', 'อินโดนีเซีย', 'Indonesia'),
    ('IE', 'ไอร์แลนด์', 'Ireland'),
    ('IL', 'อิสราเอล', 'Israel'),
    ('IM', 'เกาะแมน', 'Isle of Man'),
    ('IN', 'อินเดีย', 'India'),
    ('IO', 'บริติชอินเดียนโอเชียนเทร์ริทอรี', 'British Indian Ocean Territory'),
    ('IQ', 'อิรัก', 'Iraq'),
    ('IR', 'อิหร่าน', 'Iran'),
    ('IS', 'ไอซ์แลนด์', 'Iceland'),
    ('IT', 'อิตาลี', 'Italy'),
    ('JE', 'เจอร์ซีย์', 'Jersey'),
    ('JM', 'จาเมกา', 'Jamaica'),
    ('JO', 'จอร์แดน', 'Jordan'),
    ('JP', 'ญี่ปุ่น', 'Japan'),
    ('KE', 'เคนยา', 'Kenya'),
    ('KG', 'คีร์กีซสถาน', 'Kyrgyzstan'),
    ('KH', 'กัมพูชา', 'Cambodia'),
    ('KI', 'คิริบาส', 'Kiribati'),
    ('KM', 'คอโมโรส', 'Comoros'),
    ('KN', 'เซนต์คิตส์และเนวิส', 'St. Kitts & Nevis'),
    ('KP', 'เกาหลีเหนือ', 'North Korea'),
    ('KR', 'เกาหลีใต้', 'South Korea'),
    ('KW', 'คูเวต', 'Kuwait'),
    ('KY', 'หมู่เกาะเคย์แมน', 'Cayman Islands'),
    ('KZ', 'คาซัคสถาน', 'Kazakhstan'),
    ('LA', 'ลาว', 'Laos'),
    ('LB', 'เลบานอน', 'Lebanon'),
    ('LC', 'เซนต์ลูเซีย', 'St. Lucia'),
    ('LI', 'ลิกเตนสไตน์', 'Liechtenstein'),
    ('LK', 'ศรีลังกา', 'Sri Lanka'),
    ('LR', 'ไลบีเรีย', 'Liberia'),
    ('LS', 'เลโซโท', 'Lesotho'),
    ('LT', 'ลิทัวเนีย', 'Lithuania'),
    ('LU', 'ลักเซมเบิร์ก', 'Luxembourg'),
    ('LV', 'ลัตเวีย', 'Latvia'),
    ('LY', 'ลิเบีย', 'Libya'),
    ('MA', 'โมร็อกโก', 'Morocco'),
    ('MC', 'โมนาโก', 'Monaco'),
    ('MD', 'มอลโดวา', 'Moldova'),
    ('ME', 'มอนเตเนโกร', 'Montenegro'),
    ('MF', 'เซนต์มาร์ติน', 'St. Martin'),
    ('MG', 'มาดากัสการ์', 'Madagascar'),
    ('MH', 'หมู่เกาะมาร์แชลล์', 'Marshall Islands'),
    ('MK', 'มาซิโดเนียเหนือ', 'North Macedonia'),
    ('ML', 'มาลี', 'Mali'),
    ('MM', 'เมียนมา (พม่า)', 'Myanmar (Burma)'),
    ('MN', 'มองโกเลีย', 'Mongolia'),
    ('MO', 'เขตปกครองพิเศษมาเก๊าแห่งสาธารณรัฐประชาชนจีน', 'Macao SAR China'),
    ('MP', 'หมู่เกาะนอร์เทิร์นมาเรียนา', 'Northern Mariana Islands'),
    ('MQ', 'มาร์ตินีก', 'Martinique'),
    ('MR', 'มอริเตเนีย', 'Mauritania'),
    ('MS', 'มอนต์เซอร์รัต', 'Montserrat'),
    ('MT', 'มอลตา', 'Malta'),
    ('MU', 'มอริเชียส', 'Mauritius'),
    ('MV', 'มัลดีฟส์', 'Maldives'),
    ('MW', 'มาลาวี', 'Malawi'),
    ('MX', 'เม็กซิโก', 'Mexico'),
    ('MY', 'มาเลเซีย', 'Malaysia'),
    ('MZ', 'โมซัมบิก', 'Mozambique'),
    ('NA', 'นามิเบีย', 'Namibia'),
    ('NC', 'นิวแคลิโดเนีย', 'New Caledonia'),
    ('NE', 'ไนเจอร์', 'Niger'),
    ('NF', 'เกาะนอร์ฟอล์ก', 'Norfolk Island'),
    ('NG', 'ไนจีเรีย', 'Nigeria'),
    ('NI', 'นิการากัว', 'Nicaragua'),
    ('NL', 'เนเธอร์แลนด์', 'Netherlands'),
    ('NO', 'นอร์เวย์', 'Norway'),
    ('NP', 'เนปาล', 'Nepal'),
    ('NR', 'นาอูรู', 'Nauru'),
    ('NU', 'นีอูเอ', 'Niue'),
    ('NZ', 'นิวซีแลนด์', 'New Zealand'),
    ('OM', 'โอมาน', 'Oman'),
    ('PA', 'ปานามา', 'Panama'),
    ('PE', 'เปรู', 'Peru'),
    ('PF', 'เฟรนช์โปลินีเซีย', 'French Polynesia'),
    ('PG', 'ปาปัวนิวกินี', 'Papua New Guinea'),
    ('PH', 'ฟิลิปปินส์', 'Philippines'),
    ('PK', 'ปากีสถาน', 'Pakistan'),
    ('PL', 'โปแลนด์', 'Poland'),
    ('PM', 'แซงปีแยร์และมีเกอลง', 'St. Pierre & Miquelon'),
    ('PN', 'หมู่เกาะพิตแคร์น', 'Pitcairn Islands'),
    ('PR', 'เปอร์โตริโก', 'Puerto Rico'),
    ('PS', 'ดินแดนปาเลสไตน์', 'Palestinian Territories'),
    ('PT', 'โปรตุเกส', 'Portugal'),
    ('PW', 'ปาเลา', 'Palau'),
    ('PY', 'ปารากวัย', 'Paraguay'),
    ('QA', 'กาตาร์', 'Qatar'),
    ('RE', 'เรอูนียง', 'Réunion'),
    ('RO', 'โรมาเนีย', 'Romania'),
    ('RS', 'เซอร์เบีย', 'Serbia'),
    ('RU', 'รัสเซีย', 'Russia'),
    ('RW', 'รวันดา', 'Rwanda'),
    ('SA', 'ซาอุดีอาระเบีย', 'Saudi Arabia'),
    ('SB', 'หมู่เกาะโซโลมอน', 'Solomon Islands'),
    ('SC', 'เซเชลส์', 'Seychelles'),
    ('SD', 'ซูดาน', 'Sudan'),
    ('SE', 'สวีเดน', 'Sweden'),
    ('SG', 'สิงคโปร์', 'Singapore'),
    ('SH', 'เซนต์เฮเลนา', 'St. Helena'),
    ('SI', 'สโลวีเนีย', 'Slovenia'),
    ('SJ', 'สฟาลบาร์และยานไมเอน', 'Svalbard & Jan Mayen'),
    ('SK', 'สโลวะเกีย', 'Slovakia'),
    ('SL', 'เซียร์ราลีโอน', 'Sierra Leone'),
    ('SM', 'ซานมาริโน', 'San Marino'),
    ('SN', 'เซเนกัล', 'Senegal'),
    ('SO', 'โซมาเลีย', 'Somalia'),
    ('SR', 'ซูรินาเม', 'Suriname'),
    ('SS', 'ซูดานใต้', 'South Sudan'),
    ('ST', 'เซาตูเมและปรินซิปี', 'São Tomé & Príncipe'),
    ('SV', 'เอลซัลวาดอร์', 'El Salvador'),
    ('SX', 'ซินต์มาร์เทน', 'Sint Maarten'),
    ('SY', 'ซีเรีย', 'Syria'),
    ('SZ', 'เอสวาตีนี', 'Eswatini'),
    ('TC', 'หมู่เกาะเติกส์และหมู่เกาะเคคอส', 'Turks & Caicos Islands'),
    ('TD', 'ชาด', 'Chad'),
    ('TF', 'เฟรนช์เซาเทิร์นเทร์ริทอรีส์', 'French Southern Territories'),
    ('TG', 'โตโก', 'Togo'),
    ('TH', 'ไทย', 'Thailand'),
    ('TJ', 'ทาจิกิสถาน', 'Tajikistan'),
    ('TK', 'โตเกเลา', 'Tokelau'),
    ('TL', 'ติมอร์-เลสเต', 'Timor-Leste'),
    ('TM', 'เติร์กเมนิสถาน', 'Turkmenistan'),
    ('TN', 'ตูนิเซีย', 'Tunisia'),
    ('TO', 'ตองกา', 'Tonga'),
    ('TR', 'ตุรกี', 'Türkiye'),
    ('TT', 'ตรินิแดดและโตเบโก', 'Trinidad & Tobago'),
    ('TV', 'ตูวาลู', 'Tuvalu'),
    ('TW', 'ไต้หวัน', 'Taiwan'),
    ('TZ', 'แทนซาเนีย', 'Tanzania'),
    ('UA', 'ยูเครน', 'Ukraine'),
    ('UG', 'ยูกันดา', 'Uganda'),
    ('UM', 'หมู่เกาะรอบนอกของสหรัฐอเมริกา', 'U.S. Outlying Islands'),
    ('US', 'สหรัฐอเมริกา', 'United States'),
    ('UY', 'อุรุกวัย', 'Uruguay'),
    ('UZ', 'อุซเบกิสถาน', 'Uzbekistan'),
    ('VA', 'นครวาติกัน', 'Vatican City'),
    ('VC', 'เซนต์วินเซนต์และเกรนาดีนส์', 'St. Vincent & Grenadines'),
    ('VE', 'เวเนซุเอลา', 'Venezuela'),
    ('VG', 'หมู่เกาะบริติชเวอร์จิน', 'British Virgin Islands'),
    ('VI', 'หมู่เกาะเวอร์จินของสหรัฐอเมริกา', 'U.S. Virgin Islands'),
    ('VN', 'เวียดนาม', 'Vietnam'),
    ('VU', 'วานูอาตู', 'Vanuatu'),
    ('WF', 'วาลลิสและฟุตูนา', 'Wallis & Futuna'),
    ('WS', 'ซามัว', 'Samoa'),
    ('YE', 'เยเมน', 'Yemen'),
    ('YT', 'มายอต', 'Mayotte'),
    ('ZA', 'แอฟริกาใต้', 'South Africa'),
    ('ZM', 'แซมเบีย', 'Zambia'),
    ('ZW', 'ซิมบับเว', 'Zimbabwe');

ALTER TABLE org.data_categories NO FORCE ROW LEVEL SECURITY;
ALTER TABLE org.data_subject_types NO FORCE ROW LEVEL SECURITY;
ALTER TABLE org.processing_purposes NO FORCE ROW LEVEL SECURITY;

INSERT INTO org.data_categories (tenant_id, code, name_th, name_en, is_sensitive, sensitive_type) VALUES
    (NULL, 'identity', 'ข้อมูลระบุตัวตน (ชื่อ นามสกุล วันเกิด)', 'Identity (name, date of birth)', false, NULL),
    (NULL, 'contact', 'ข้อมูลติดต่อ (ที่อยู่ อีเมล โทรศัพท์)', 'Contact details', false, NULL),
    (NULL, 'national_id', 'เลขประจำตัวประชาชน / หนังสือเดินทาง', 'National ID / passport number', false, NULL),
    (NULL, 'financial', 'ข้อมูลทางการเงิน', 'Financial data', false, NULL),
    (NULL, 'employment', 'ข้อมูลการจ้างงาน', 'Employment data', false, NULL),
    (NULL, 'education', 'ข้อมูลการศึกษา', 'Education data', false, NULL),
    (NULL, 'online_identifier', 'ตัวระบุออนไลน์ (IP, cookie ID)', 'Online identifiers (IP, cookie ID)', false, NULL),
    (NULL, 'location', 'ข้อมูลตำแหน่งที่อยู่', 'Location data', false, NULL),
    (NULL, 'image_voice', 'ภาพถ่าย ภาพเคลื่อนไหว และเสียง', 'Photos, video and voice', false, NULL),
    (NULL, 'race_ethnicity', 'เชื้อชาติ เผ่าพันธุ์', 'Racial or ethnic origin', true, 'race'),
    (NULL, 'political_opinion', 'ความคิดเห็นทางการเมือง', 'Political opinions', true, 'political'),
    (NULL, 'religion_belief', 'ความเชื่อในลัทธิ ศาสนา หรือปรัชญา', 'Religious or philosophical beliefs', true, 'religion'),
    (NULL, 'sexual_behaviour', 'พฤติกรรมทางเพศ', 'Sexual behaviour', true, 'sexual'),
    (NULL, 'criminal_record', 'ประวัติอาชญากรรม', 'Criminal records', true, 'criminal'),
    (NULL, 'health', 'ข้อมูลสุขภาพ', 'Health data', true, 'health'),
    (NULL, 'disability', 'ความพิการ', 'Disability', true, 'disability'),
    (NULL, 'trade_union', 'ข้อมูลสหภาพแรงงาน', 'Trade union membership', true, 'trade_union'),
    (NULL, 'genetic', 'ข้อมูลพันธุกรรม', 'Genetic data', true, 'genetic'),
    (NULL, 'biometric', 'ข้อมูลชีวภาพ', 'Biometric data', true, 'biometric');

INSERT INTO org.data_subject_types (tenant_id, code, name_th, name_en, is_vulnerable) VALUES
    (NULL, 'customer', 'ลูกค้า', 'Customers', false),
    (NULL, 'prospect', 'ลูกค้าเป้าหมาย', 'Prospects', false),
    (NULL, 'employee', 'พนักงาน', 'Employees', false),
    (NULL, 'job_applicant', 'ผู้สมัครงาน', 'Job applicants', false),
    (NULL, 'vendor_contact', 'ผู้ติดต่อของคู่ค้า', 'Vendor contacts', false),
    (NULL, 'visitor', 'ผู้มาติดต่อ / ผู้เข้าอาคาร', 'Visitors', false),
    (NULL, 'website_user', 'ผู้ใช้เว็บไซต์และแอป', 'Website and app users', false),
    (NULL, 'shareholder', 'ผู้ถือหุ้น', 'Shareholders', false),
    (NULL, 'minor', 'ผู้เยาว์', 'Minors', true);

INSERT INTO org.processing_purposes (tenant_id, code, name_th, name_en, category) VALUES
    (NULL, 'contract_service', 'ให้บริการและปฏิบัติตามสัญญา', 'Providing services and performing contracts', 'operations'),
    (NULL, 'customer_support', 'บริการลูกค้าและตอบคำถาม', 'Customer support', 'operations'),
    (NULL, 'marketing', 'การตลาดและส่งข่าวสาร', 'Marketing and newsletters', 'marketing'),
    (NULL, 'analytics', 'วิเคราะห์และปรับปรุงบริการ', 'Analytics and service improvement', 'analytics'),
    (NULL, 'hr_management', 'บริหารงานบุคคล', 'Human resources management', 'hr'),
    (NULL, 'recruitment', 'สรรหาพนักงาน', 'Recruitment', 'hr'),
    (NULL, 'legal_compliance', 'ปฏิบัติตามกฎหมาย', 'Legal compliance', 'legal'),
    (NULL, 'security_cctv', 'รักษาความปลอดภัยและกล้องวงจรปิด', 'Security and CCTV', 'security'),
    (NULL, 'fraud_prevention', 'ป้องกันการทุจริต', 'Fraud prevention', 'security'),
    (NULL, 'accounting', 'บัญชีและภาษี', 'Accounting and tax', 'finance');

ALTER TABLE org.data_categories FORCE ROW LEVEL SECURITY;
ALTER TABLE org.data_subject_types FORCE ROW LEVEL SECURITY;
ALTER TABLE org.processing_purposes FORCE ROW LEVEL SECURITY;

-- +goose Down
ALTER TABLE org.data_categories NO FORCE ROW LEVEL SECURITY;
ALTER TABLE org.data_subject_types NO FORCE ROW LEVEL SECURITY;
ALTER TABLE org.processing_purposes NO FORCE ROW LEVEL SECURITY;
DELETE FROM org.processing_purposes WHERE tenant_id IS NULL;
DELETE FROM org.data_subject_types WHERE tenant_id IS NULL;
DELETE FROM org.data_categories WHERE tenant_id IS NULL;
ALTER TABLE org.data_categories FORCE ROW LEVEL SECURITY;
ALTER TABLE org.data_subject_types FORCE ROW LEVEL SECURITY;
ALTER TABLE org.processing_purposes FORCE ROW LEVEL SECURITY;
DELETE FROM org.countries;
DELETE FROM org.lawful_bases;
