// Package orghttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package orghttp

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AcceptLanguage.
const (
	AcceptLanguageEn AcceptLanguage = "en"
	AcceptLanguageTh AcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the AcceptLanguage enum.
func (e AcceptLanguage) Valid() bool {
	switch e {
	case AcceptLanguageEn:
		return true
	case AcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for OrgListCalendarsParamsAcceptLanguage.
const (
	OrgListCalendarsParamsAcceptLanguageEn OrgListCalendarsParamsAcceptLanguage = "en"
	OrgListCalendarsParamsAcceptLanguageTh OrgListCalendarsParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the OrgListCalendarsParamsAcceptLanguage enum.
func (e OrgListCalendarsParamsAcceptLanguage) Valid() bool {
	switch e {
	case OrgListCalendarsParamsAcceptLanguageEn:
		return true
	case OrgListCalendarsParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for OrgCreateCalendarParamsAcceptLanguage.
const (
	OrgCreateCalendarParamsAcceptLanguageEn OrgCreateCalendarParamsAcceptLanguage = "en"
	OrgCreateCalendarParamsAcceptLanguageTh OrgCreateCalendarParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the OrgCreateCalendarParamsAcceptLanguage enum.
func (e OrgCreateCalendarParamsAcceptLanguage) Valid() bool {
	switch e {
	case OrgCreateCalendarParamsAcceptLanguageEn:
		return true
	case OrgCreateCalendarParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for OrgUpdateCalendarParamsAcceptLanguage.
const (
	OrgUpdateCalendarParamsAcceptLanguageEn OrgUpdateCalendarParamsAcceptLanguage = "en"
	OrgUpdateCalendarParamsAcceptLanguageTh OrgUpdateCalendarParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the OrgUpdateCalendarParamsAcceptLanguage enum.
func (e OrgUpdateCalendarParamsAcceptLanguage) Valid() bool {
	switch e {
	case OrgUpdateCalendarParamsAcceptLanguageEn:
		return true
	case OrgUpdateCalendarParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for OrgListHolidaysParamsAcceptLanguage.
const (
	OrgListHolidaysParamsAcceptLanguageEn OrgListHolidaysParamsAcceptLanguage = "en"
	OrgListHolidaysParamsAcceptLanguageTh OrgListHolidaysParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the OrgListHolidaysParamsAcceptLanguage enum.
func (e OrgListHolidaysParamsAcceptLanguage) Valid() bool {
	switch e {
	case OrgListHolidaysParamsAcceptLanguageEn:
		return true
	case OrgListHolidaysParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for OrgDeleteHolidayParamsAcceptLanguage.
const (
	OrgDeleteHolidayParamsAcceptLanguageEn OrgDeleteHolidayParamsAcceptLanguage = "en"
	OrgDeleteHolidayParamsAcceptLanguageTh OrgDeleteHolidayParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the OrgDeleteHolidayParamsAcceptLanguage enum.
func (e OrgDeleteHolidayParamsAcceptLanguage) Valid() bool {
	switch e {
	case OrgDeleteHolidayParamsAcceptLanguageEn:
		return true
	case OrgDeleteHolidayParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for OrgPutHolidayParamsAcceptLanguage.
const (
	OrgPutHolidayParamsAcceptLanguageEn OrgPutHolidayParamsAcceptLanguage = "en"
	OrgPutHolidayParamsAcceptLanguageTh OrgPutHolidayParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the OrgPutHolidayParamsAcceptLanguage enum.
func (e OrgPutHolidayParamsAcceptLanguage) Valid() bool {
	switch e {
	case OrgPutHolidayParamsAcceptLanguageEn:
		return true
	case OrgPutHolidayParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// BusinessCalendar defines model for BusinessCalendar.
type BusinessCalendar struct {
	// Id UUIDv7 generated by the API
	Id         Uuid   `json:"id"`
	IsDefault  bool   `json:"is_default"`
	Name       string `json:"name"`
	RowVersion int    `json:"row_version"`
	Timezone   string `json:"timezone"`

	// UpdatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	UpdatedAt Timestamp `json:"updated_at"`
	Workdays  []int     `json:"workdays"`
}

// BusinessCalendarInput defines model for BusinessCalendarInput.
type BusinessCalendarInput struct {
	// IsDefault Make this the tenant's default calendar (true only — the default moves, it is never cleared)
	IsDefault *bool  `json:"is_default,omitempty"`
	Name      string `json:"name"`

	// Timezone IANA time zone the calendar's days are counted in
	Timezone string `json:"timezone"`

	// Workdays ISO weekdays that are working days (1 = Monday … 7 = Sunday)
	Workdays []int `json:"workdays"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string  `json:"code"`
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
}

// Holiday defines model for Holiday.
type Holiday struct {
	Date openapi_types.Date `json:"date"`
	Name string             `json:"name"`
}

// Problem RFC 9457 problem details with a stable machine-readable `code`
type Problem struct {
	Code      string        `json:"code"`
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// Timestamp RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
type Timestamp = time.Time

// Uuid UUIDv7 generated by the API
type Uuid = openapi_types.UUID

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage string

// IfMatch defines model for IfMatch.
type IfMatch = string

// BadRequest RFC 9457 problem details with a stable machine-readable `code`
type BadRequest = Problem

// Forbidden RFC 9457 problem details with a stable machine-readable `code`
type Forbidden = Problem

// NotFound RFC 9457 problem details with a stable machine-readable `code`
type NotFound = Problem

// PreconditionFailed RFC 9457 problem details with a stable machine-readable `code`
type PreconditionFailed = Problem

// PreconditionRequired RFC 9457 problem details with a stable machine-readable `code`
type PreconditionRequired = Problem

// Unauthorized RFC 9457 problem details with a stable machine-readable `code`
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 problem details with a stable machine-readable `code`
type UnprocessableEntity = Problem

// OrgListCalendarsParams defines parameters for OrgListCalendars.
type OrgListCalendarsParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *OrgListCalendarsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// OrgListCalendarsParamsAcceptLanguage defines parameters for OrgListCalendars.
type OrgListCalendarsParamsAcceptLanguage string

// OrgCreateCalendarParams defines parameters for OrgCreateCalendar.
type OrgCreateCalendarParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *OrgCreateCalendarParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// OrgCreateCalendarParamsAcceptLanguage defines parameters for OrgCreateCalendar.
type OrgCreateCalendarParamsAcceptLanguage string

// OrgUpdateCalendarParams defines parameters for OrgUpdateCalendar.
type OrgUpdateCalendarParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *OrgUpdateCalendarParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// OrgUpdateCalendarParamsAcceptLanguage defines parameters for OrgUpdateCalendar.
type OrgUpdateCalendarParamsAcceptLanguage string

// OrgListHolidaysParams defines parameters for OrgListHolidays.
type OrgListHolidaysParams struct {
	Year *int `form:"year,omitempty" json:"year,omitempty"`

	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *OrgListHolidaysParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// OrgListHolidaysParamsAcceptLanguage defines parameters for OrgListHolidays.
type OrgListHolidaysParamsAcceptLanguage string

// OrgDeleteHolidayParams defines parameters for OrgDeleteHoliday.
type OrgDeleteHolidayParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *OrgDeleteHolidayParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// OrgDeleteHolidayParamsAcceptLanguage defines parameters for OrgDeleteHoliday.
type OrgDeleteHolidayParamsAcceptLanguage string

// OrgPutHolidayJSONBody defines parameters for OrgPutHoliday.
type OrgPutHolidayJSONBody struct {
	Name string `json:"name"`
}

// OrgPutHolidayParams defines parameters for OrgPutHoliday.
type OrgPutHolidayParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *OrgPutHolidayParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// OrgPutHolidayParamsAcceptLanguage defines parameters for OrgPutHoliday.
type OrgPutHolidayParamsAcceptLanguage string

// OrgCreateCalendarJSONRequestBody defines body for OrgCreateCalendar for application/json ContentType.
type OrgCreateCalendarJSONRequestBody = BusinessCalendarInput

// OrgUpdateCalendarJSONRequestBody defines body for OrgUpdateCalendar for application/json ContentType.
type OrgUpdateCalendarJSONRequestBody = BusinessCalendarInput

// OrgPutHolidayJSONRequestBody defines body for OrgPutHoliday for application/json ContentType.
type OrgPutHolidayJSONRequestBody OrgPutHolidayJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// OrgListCalendars The tenant's business calendars (workdays and time zone used to count SLAs)
	// (GET /admin/v1/org/calendars)
	OrgListCalendars(w http.ResponseWriter, r *http.Request, params OrgListCalendarsParams)
	// OrgCreateCalendar Add a calendar (the tenant's first calendar becomes its default)
	// (POST /admin/v1/org/calendars)
	OrgCreateCalendar(w http.ResponseWriter, r *http.Request, params OrgCreateCalendarParams)
	// OrgUpdateCalendar Change a calendar's name, time zone or workdays, or make it the default
	// (PATCH /admin/v1/org/calendars/{id})
	OrgUpdateCalendar(w http.ResponseWriter, r *http.Request, id Uuid, params OrgUpdateCalendarParams)
	// OrgListHolidays Holidays of a calendar, optionally of one year (Gregorian)
	// (GET /admin/v1/org/calendars/{id}/holidays)
	OrgListHolidays(w http.ResponseWriter, r *http.Request, id Uuid, params OrgListHolidaysParams)
	// OrgDeleteHoliday Remove a holiday
	// (DELETE /admin/v1/org/calendars/{id}/holidays/{date})
	OrgDeleteHoliday(w http.ResponseWriter, r *http.Request, id Uuid, date openapi_types.Date, params OrgDeleteHolidayParams)
	// OrgPutHoliday Add a holiday, or rename the holiday on that date
	// (PUT /admin/v1/org/calendars/{id}/holidays/{date})
	OrgPutHoliday(w http.ResponseWriter, r *http.Request, id Uuid, date openapi_types.Date, params OrgPutHolidayParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// OrgListCalendars The tenant's business calendars (workdays and time zone used to count SLAs)
// (GET /admin/v1/org/calendars)
func (_ Unimplemented) OrgListCalendars(w http.ResponseWriter, r *http.Request, params OrgListCalendarsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OrgCreateCalendar Add a calendar (the tenant's first calendar becomes its default)
// (POST /admin/v1/org/calendars)
func (_ Unimplemented) OrgCreateCalendar(w http.ResponseWriter, r *http.Request, params OrgCreateCalendarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OrgUpdateCalendar Change a calendar's name, time zone or workdays, or make it the default
// (PATCH /admin/v1/org/calendars/{id})
func (_ Unimplemented) OrgUpdateCalendar(w http.ResponseWriter, r *http.Request, id Uuid, params OrgUpdateCalendarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OrgListHolidays Holidays of a calendar, optionally of one year (Gregorian)
// (GET /admin/v1/org/calendars/{id}/holidays)
func (_ Unimplemented) OrgListHolidays(w http.ResponseWriter, r *http.Request, id Uuid, params OrgListHolidaysParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OrgDeleteHoliday Remove a holiday
// (DELETE /admin/v1/org/calendars/{id}/holidays/{date})
func (_ Unimplemented) OrgDeleteHoliday(w http.ResponseWriter, r *http.Request, id Uuid, date openapi_types.Date, params OrgDeleteHolidayParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OrgPutHoliday Add a holiday, or rename the holiday on that date
// (PUT /admin/v1/org/calendars/{id}/holidays/{date})
func (_ Unimplemented) OrgPutHoliday(w http.ResponseWriter, r *http.Request, id Uuid, date openapi_types.Date, params OrgPutHolidayParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// OrgListCalendars operation middleware
func (siw *ServerInterfaceWrapper) OrgListCalendars(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgListCalendarsParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage OrgListCalendarsParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgListCalendars(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgCreateCalendar operation middleware
func (siw *ServerInterfaceWrapper) OrgCreateCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgCreateCalendarParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage OrgCreateCalendarParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgCreateCalendar(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgUpdateCalendar operation middleware
func (siw *ServerInterfaceWrapper) OrgUpdateCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgUpdateCalendarParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage OrgUpdateCalendarParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgUpdateCalendar(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgListHolidays operation middleware
func (siw *ServerInterfaceWrapper) OrgListHolidays(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgListHolidaysParams

	// ------------- Optional query parameter "year" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year", r.URL.Query(), &params.Year, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage OrgListHolidaysParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgListHolidays(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgDeleteHoliday operation middleware
func (siw *ServerInterfaceWrapper) OrgDeleteHoliday(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgDeleteHolidayParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage OrgDeleteHolidayParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgDeleteHoliday(w, r, id, date, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgPutHoliday operation middleware
func (siw *ServerInterfaceWrapper) OrgPutHoliday(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgPutHolidayParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage OrgPutHolidayParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgPutHoliday(w, r, id, date, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/org/calendars", wrapper.OrgListCalendars)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/org/calendars", wrapper.OrgCreateCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/v1/org/calendars/{id}", wrapper.OrgUpdateCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/org/calendars/{id}/holidays", wrapper.OrgListHolidays)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/v1/org/calendars/{id}/holidays/{date}", wrapper.OrgDeleteHoliday)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/v1/org/calendars/{id}/holidays/{date}", wrapper.OrgPutHoliday)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type PreconditionFailedApplicationProblemPlusJSONResponse Problem

type PreconditionRequiredApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type OrgListCalendarsRequestObject struct {
	Params OrgListCalendarsParams
}

type OrgListCalendarsResponseObject interface {
	VisitOrgListCalendarsResponse(w http.ResponseWriter) error
}

type OrgListCalendars200JSONResponse struct {
	Data []BusinessCalendar `json:"data"`
}

func (response OrgListCalendars200JSONResponse) VisitOrgListCalendarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrgListCalendars401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response OrgListCalendars401ApplicationProblemPlusJSONResponse) VisitOrgListCalendarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrgListCalendars403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response OrgListCalendars403ApplicationProblemPlusJSONResponse) VisitOrgListCalendarsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrgCreateCalendarRequestObject struct {
	Params OrgCreateCalendarParams
	Body   *OrgCreateCalendarJSONRequestBody
}

type OrgCreateCalendarResponseObject interface {
	VisitOrgCreateCalendarResponse(w http.ResponseWriter) error
}

type OrgCreateCalendar201ResponseHeaders struct {
	ETag *string
}

type OrgCreateCalendar201JSONResponse struct {
	Body    BusinessCalendar
	Headers OrgCreateCalendar201ResponseHeaders
}

func (response OrgCreateCalendar201JSONResponse) VisitOrgCreateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type OrgCreateCalendar400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response OrgCreateCalendar400ApplicationProblemPlusJSONResponse) VisitOrgCreateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OrgCreateCalendar401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response OrgCreateCalendar401ApplicationProblemPlusJSONResponse) VisitOrgCreateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrgCreateCalendar403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response OrgCreateCalendar403ApplicationProblemPlusJSONResponse) VisitOrgCreateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrgCreateCalendar422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response OrgCreateCalendar422ApplicationProblemPlusJSONResponse) VisitOrgCreateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendarRequestObject struct {
	Id     Uuid `json:"id"`
	Params OrgUpdateCalendarParams
	Body   *OrgUpdateCalendarJSONRequestBody
}

type OrgUpdateCalendarResponseObject interface {
	VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error
}

type OrgUpdateCalendar200ResponseHeaders struct {
	ETag *string
}

type OrgUpdateCalendar200JSONResponse struct {
	Body    BusinessCalendar
	Headers OrgUpdateCalendar200ResponseHeaders
}

func (response OrgUpdateCalendar200JSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendar400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response OrgUpdateCalendar400ApplicationProblemPlusJSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendar401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response OrgUpdateCalendar401ApplicationProblemPlusJSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendar403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response OrgUpdateCalendar403ApplicationProblemPlusJSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendar404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response OrgUpdateCalendar404ApplicationProblemPlusJSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendar412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response OrgUpdateCalendar412ApplicationProblemPlusJSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendar422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response OrgUpdateCalendar422ApplicationProblemPlusJSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type OrgUpdateCalendar428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response OrgUpdateCalendar428ApplicationProblemPlusJSONResponse) VisitOrgUpdateCalendarResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type OrgListHolidaysRequestObject struct {
	Id     Uuid `json:"id"`
	Params OrgListHolidaysParams
}

type OrgListHolidaysResponseObject interface {
	VisitOrgListHolidaysResponse(w http.ResponseWriter) error
}

type OrgListHolidays200JSONResponse struct {
	Data []Holiday `json:"data"`
}

func (response OrgListHolidays200JSONResponse) VisitOrgListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrgListHolidays400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response OrgListHolidays400ApplicationProblemPlusJSONResponse) VisitOrgListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OrgListHolidays401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response OrgListHolidays401ApplicationProblemPlusJSONResponse) VisitOrgListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrgListHolidays403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response OrgListHolidays403ApplicationProblemPlusJSONResponse) VisitOrgListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrgListHolidays404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response OrgListHolidays404ApplicationProblemPlusJSONResponse) VisitOrgListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type OrgDeleteHolidayRequestObject struct {
	Id     Uuid               `json:"id"`
	Date   openapi_types.Date `json:"date"`
	Params OrgDeleteHolidayParams
}

type OrgDeleteHolidayResponseObject interface {
	VisitOrgDeleteHolidayResponse(w http.ResponseWriter) error
}

type OrgDeleteHoliday204Response struct {
}

func (response OrgDeleteHoliday204Response) VisitOrgDeleteHolidayResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OrgDeleteHoliday401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response OrgDeleteHoliday401ApplicationProblemPlusJSONResponse) VisitOrgDeleteHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrgDeleteHoliday403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response OrgDeleteHoliday403ApplicationProblemPlusJSONResponse) VisitOrgDeleteHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrgDeleteHoliday404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response OrgDeleteHoliday404ApplicationProblemPlusJSONResponse) VisitOrgDeleteHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type OrgPutHolidayRequestObject struct {
	Id     Uuid               `json:"id"`
	Date   openapi_types.Date `json:"date"`
	Params OrgPutHolidayParams
	Body   *OrgPutHolidayJSONRequestBody
}

type OrgPutHolidayResponseObject interface {
	VisitOrgPutHolidayResponse(w http.ResponseWriter) error
}

type OrgPutHoliday200JSONResponse Holiday

func (response OrgPutHoliday200JSONResponse) VisitOrgPutHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrgPutHoliday400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response OrgPutHoliday400ApplicationProblemPlusJSONResponse) VisitOrgPutHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OrgPutHoliday401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response OrgPutHoliday401ApplicationProblemPlusJSONResponse) VisitOrgPutHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrgPutHoliday403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response OrgPutHoliday403ApplicationProblemPlusJSONResponse) VisitOrgPutHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrgPutHoliday404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response OrgPutHoliday404ApplicationProblemPlusJSONResponse) VisitOrgPutHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type OrgPutHoliday422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response OrgPutHoliday422ApplicationProblemPlusJSONResponse) VisitOrgPutHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// OrgListCalendars The tenant's business calendars (workdays and time zone used to count SLAs)
	// (GET /admin/v1/org/calendars)
	OrgListCalendars(ctx context.Context, request OrgListCalendarsRequestObject) (OrgListCalendarsResponseObject, error)
	// OrgCreateCalendar Add a calendar (the tenant's first calendar becomes its default)
	// (POST /admin/v1/org/calendars)
	OrgCreateCalendar(ctx context.Context, request OrgCreateCalendarRequestObject) (OrgCreateCalendarResponseObject, error)
	// OrgUpdateCalendar Change a calendar's name, time zone or workdays, or make it the default
	// (PATCH /admin/v1/org/calendars/{id})
	OrgUpdateCalendar(ctx context.Context, request OrgUpdateCalendarRequestObject) (OrgUpdateCalendarResponseObject, error)
	// OrgListHolidays Holidays of a calendar, optionally of one year (Gregorian)
	// (GET /admin/v1/org/calendars/{id}/holidays)
	OrgListHolidays(ctx context.Context, request OrgListHolidaysRequestObject) (OrgListHolidaysResponseObject, error)
	// OrgDeleteHoliday Remove a holiday
	// (DELETE /admin/v1/org/calendars/{id}/holidays/{date})
	OrgDeleteHoliday(ctx context.Context, request OrgDeleteHolidayRequestObject) (OrgDeleteHolidayResponseObject, error)
	// OrgPutHoliday Add a holiday, or rename the holiday on that date
	// (PUT /admin/v1/org/calendars/{id}/holidays/{date})
	OrgPutHoliday(ctx context.Context, request OrgPutHolidayRequestObject) (OrgPutHolidayResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// OrgListCalendars operation middleware
func (sh *strictHandler) OrgListCalendars(w http.ResponseWriter, r *http.Request, params OrgListCalendarsParams) {
	var request OrgListCalendarsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OrgListCalendars(ctx, request.(OrgListCalendarsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrgListCalendars")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OrgListCalendarsResponseObject); ok {
		if err := validResponse.VisitOrgListCalendarsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OrgCreateCalendar operation middleware
func (sh *strictHandler) OrgCreateCalendar(w http.ResponseWriter, r *http.Request, params OrgCreateCalendarParams) {
	var request OrgCreateCalendarRequestObject

	request.Params = params

	var body OrgCreateCalendarJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OrgCreateCalendar(ctx, request.(OrgCreateCalendarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrgCreateCalendar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OrgCreateCalendarResponseObject); ok {
		if err := validResponse.VisitOrgCreateCalendarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OrgUpdateCalendar operation middleware
func (sh *strictHandler) OrgUpdateCalendar(w http.ResponseWriter, r *http.Request, id Uuid, params OrgUpdateCalendarParams) {
	var request OrgUpdateCalendarRequestObject

	request.Id = id
	request.Params = params

	var body OrgUpdateCalendarJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OrgUpdateCalendar(ctx, request.(OrgUpdateCalendarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrgUpdateCalendar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OrgUpdateCalendarResponseObject); ok {
		if err := validResponse.VisitOrgUpdateCalendarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OrgListHolidays operation middleware
func (sh *strictHandler) OrgListHolidays(w http.ResponseWriter, r *http.Request, id Uuid, params OrgListHolidaysParams) {
	var request OrgListHolidaysRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OrgListHolidays(ctx, request.(OrgListHolidaysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrgListHolidays")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OrgListHolidaysResponseObject); ok {
		if err := validResponse.VisitOrgListHolidaysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OrgDeleteHoliday operation middleware
func (sh *strictHandler) OrgDeleteHoliday(w http.ResponseWriter, r *http.Request, id Uuid, date openapi_types.Date, params OrgDeleteHolidayParams) {
	var request OrgDeleteHolidayRequestObject

	request.Id = id
	request.Date = date
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OrgDeleteHoliday(ctx, request.(OrgDeleteHolidayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrgDeleteHoliday")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OrgDeleteHolidayResponseObject); ok {
		if err := validResponse.VisitOrgDeleteHolidayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OrgPutHoliday operation middleware
func (sh *strictHandler) OrgPutHoliday(w http.ResponseWriter, r *http.Request, id Uuid, date openapi_types.Date, params OrgPutHolidayParams) {
	var request OrgPutHolidayRequestObject

	request.Id = id
	request.Date = date
	request.Params = params

	var body OrgPutHolidayJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OrgPutHoliday(ctx, request.(OrgPutHolidayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrgPutHoliday")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OrgPutHolidayResponseObject); ok {
		if err := validResponse.VisitOrgPutHolidayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
