// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versioning.sql

package versioningstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideApproval = `-- name: DecideApproval :exec
UPDATE platform.approvals
SET decision = $2, reason = $3, approver_user_id = $4, decided_at = $5, row_version = row_version + 1,
    updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $1
`

type DecideApprovalParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Decision       string             `db:"decision" json:"decision"`
	Reason         *string            `db:"reason" json:"reason"`
	ApproverUserID pgtype.UUID        `db:"approver_user_id" json:"approver_user_id"`
	DecidedAt      pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) error {
	_, err := q.db.Exec(ctx, decideApproval,
		arg.ID,
		arg.Decision,
		arg.Reason,
		arg.ApproverUserID,
		arg.DecidedAt,
	)
	return err
}

const dropPendingApprovals = `-- name: DropPendingApprovals :exec
DELETE FROM platform.approvals WHERE record_version_id = $1 AND decision = 'pending'
`

// A version sent back for changes: its undecided later steps no longer apply (a resubmission starts a new round).
func (q *Queries) DropPendingApprovals(ctx context.Context, recordVersionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, dropPendingApprovals, recordVersionID)
	return err
}

const getVersion = `-- name: GetVersion :one
SELECT id, entity_type, entity_id, version_no, snapshot, diff, status, created_by, created_at, updated_at, row_version
FROM platform.record_versions WHERE id = $1
`

type GetVersionRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	VersionNo  int32              `db:"version_no" json:"version_no"`
	Snapshot   []byte             `db:"snapshot" json:"snapshot"`
	Diff       []byte             `db:"diff" json:"diff"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RowVersion int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) GetVersion(ctx context.Context, id uuid.UUID) (GetVersionRow, error) {
	row := q.db.QueryRow(ctx, getVersion, id)
	var i GetVersionRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNo,
		&i.Snapshot,
		&i.Diff,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :one
INSERT INTO platform.approvals (id, tenant_id, entity_type, entity_id, record_version_id, step_no, requested_by, approver_role, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, $5, $6, $7,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id
`

type InsertApprovalParams struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	EntityType      string      `db:"entity_type" json:"entity_type"`
	EntityID        uuid.UUID   `db:"entity_id" json:"entity_id"`
	RecordVersionID pgtype.UUID `db:"record_version_id" json:"record_version_id"`
	StepNo          int32       `db:"step_no" json:"step_no"`
	RequestedBy     uuid.UUID   `db:"requested_by" json:"requested_by"`
	ApproverRole    *string     `db:"approver_role" json:"approver_role"`
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertApproval,
		arg.ID,
		arg.EntityType,
		arg.EntityID,
		arg.RecordVersionID,
		arg.StepNo,
		arg.RequestedBy,
		arg.ApproverRole,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertVersion = `-- name: InsertVersion :one
INSERT INTO platform.record_versions (id, tenant_id, entity_type, entity_id, version_no, snapshot, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, $5,
        NULLIF(current_setting('app.user_id', true), '')::uuid, NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, entity_type, entity_id, version_no, snapshot, diff, status, created_by, created_at, updated_at, row_version
`

type InsertVersionParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
	VersionNo  int32     `db:"version_no" json:"version_no"`
	Snapshot   []byte    `db:"snapshot" json:"snapshot"`
}

type InsertVersionRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	VersionNo  int32              `db:"version_no" json:"version_no"`
	Snapshot   []byte             `db:"snapshot" json:"snapshot"`
	Diff       []byte             `db:"diff" json:"diff"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RowVersion int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) (InsertVersionRow, error) {
	row := q.db.QueryRow(ctx, insertVersion,
		arg.ID,
		arg.EntityType,
		arg.EntityID,
		arg.VersionNo,
		arg.Snapshot,
	)
	var i InsertVersionRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNo,
		&i.Snapshot,
		&i.Diff,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const listApprovals = `-- name: ListApprovals :many
SELECT id, record_version_id, step_no, requested_by, approver_user_id, approver_role, decision, reason, decided_at, created_at, row_version
FROM platform.approvals WHERE record_version_id = $1
ORDER BY created_at, step_no
`

type ListApprovalsRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	RecordVersionID pgtype.UUID        `db:"record_version_id" json:"record_version_id"`
	StepNo          int32              `db:"step_no" json:"step_no"`
	RequestedBy     uuid.UUID          `db:"requested_by" json:"requested_by"`
	ApproverUserID  pgtype.UUID        `db:"approver_user_id" json:"approver_user_id"`
	ApproverRole    *string            `db:"approver_role" json:"approver_role"`
	Decision        string             `db:"decision" json:"decision"`
	Reason          *string            `db:"reason" json:"reason"`
	DecidedAt       pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) ListApprovals(ctx context.Context, recordVersionID pgtype.UUID) ([]ListApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listApprovals, recordVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovalsRow
	for rows.Next() {
		var i ListApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordVersionID,
			&i.StepNo,
			&i.RequestedBy,
			&i.ApproverUserID,
			&i.ApproverRole,
			&i.Decision,
			&i.Reason,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many

SELECT id, entity_type, entity_id, version_no, snapshot, diff, status, created_by, created_at, updated_at, row_version
FROM platform.record_versions WHERE entity_type = $1 AND entity_id = $2
ORDER BY version_no DESC
`

type ListVersionsParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

type ListVersionsRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	VersionNo  int32              `db:"version_no" json:"version_no"`
	Snapshot   []byte             `db:"snapshot" json:"snapshot"`
	Diff       []byte             `db:"diff" json:"diff"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RowVersion int32              `db:"row_version" json:"row_version"`
}

// PLT-08 versioning & approval.
func (q *Queries) ListVersions(ctx context.Context, arg ListVersionsParams) ([]ListVersionsRow, error) {
	rows, err := q.db.Query(ctx, listVersions, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionsRow
	for rows.Next() {
		var i ListVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.VersionNo,
			&i.Snapshot,
			&i.Diff,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApproval = `-- name: LockApproval :one
SELECT id, entity_type, entity_id, record_version_id, step_no, requested_by, approver_user_id, approver_role, decision, reason, decided_at, created_at, row_version
FROM platform.approvals WHERE id = $1 FOR UPDATE
`

type LockApprovalRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	EntityType      string             `db:"entity_type" json:"entity_type"`
	EntityID        uuid.UUID          `db:"entity_id" json:"entity_id"`
	RecordVersionID pgtype.UUID        `db:"record_version_id" json:"record_version_id"`
	StepNo          int32              `db:"step_no" json:"step_no"`
	RequestedBy     uuid.UUID          `db:"requested_by" json:"requested_by"`
	ApproverUserID  pgtype.UUID        `db:"approver_user_id" json:"approver_user_id"`
	ApproverRole    *string            `db:"approver_role" json:"approver_role"`
	Decision        string             `db:"decision" json:"decision"`
	Reason          *string            `db:"reason" json:"reason"`
	DecidedAt       pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) LockApproval(ctx context.Context, id uuid.UUID) (LockApprovalRow, error) {
	row := q.db.QueryRow(ctx, lockApproval, id)
	var i LockApprovalRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.RecordVersionID,
		&i.StepNo,
		&i.RequestedBy,
		&i.ApproverUserID,
		&i.ApproverRole,
		&i.Decision,
		&i.Reason,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.RowVersion,
	)
	return i, err
}

const lockVersion = `-- name: LockVersion :one
SELECT id, entity_type, entity_id, version_no, snapshot, diff, status, created_by, created_at, updated_at, row_version
FROM platform.record_versions WHERE id = $1 FOR UPDATE
`

type LockVersionRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	VersionNo  int32              `db:"version_no" json:"version_no"`
	Snapshot   []byte             `db:"snapshot" json:"snapshot"`
	Diff       []byte             `db:"diff" json:"diff"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RowVersion int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) LockVersion(ctx context.Context, id uuid.UUID) (LockVersionRow, error) {
	row := q.db.QueryRow(ctx, lockVersion, id)
	var i LockVersionRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNo,
		&i.Snapshot,
		&i.Diff,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const myPendingApprovals = `-- name: MyPendingApprovals :many
SELECT a.id, a.entity_type, a.entity_id, a.record_version_id, a.step_no, a.requested_by, a.approver_role, a.created_at, a.row_version,
       v.version_no, v.created_by AS author
FROM platform.approvals a
JOIN platform.record_versions v ON v.id = a.record_version_id AND v.status = 'in_review'
WHERE a.decision = 'pending' AND a.approver_role = ANY ($1::text[])
  AND a.requested_by <> $2::uuid AND v.created_by IS DISTINCT FROM $2::uuid
  AND NOT EXISTS (SELECT 1 FROM platform.approvals e WHERE e.record_version_id = a.record_version_id AND e.decision = 'pending' AND e.step_no < a.step_no)
  AND NOT EXISTS (SELECT 1 FROM platform.approvals d WHERE d.record_version_id = a.record_version_id AND d.approver_user_id = $2::uuid AND d.decision = 'approved')
ORDER BY a.created_at
LIMIT 200
`

type MyPendingApprovalsParams struct {
	Roles  []string  `db:"roles" json:"roles"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type MyPendingApprovalsRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	EntityType      string             `db:"entity_type" json:"entity_type"`
	EntityID        uuid.UUID          `db:"entity_id" json:"entity_id"`
	RecordVersionID pgtype.UUID        `db:"record_version_id" json:"record_version_id"`
	StepNo          int32              `db:"step_no" json:"step_no"`
	RequestedBy     uuid.UUID          `db:"requested_by" json:"requested_by"`
	ApproverRole    *string            `db:"approver_role" json:"approver_role"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RowVersion      int32              `db:"row_version" json:"row_version"`
	VersionNo       int32              `db:"version_no" json:"version_no"`
	Author          pgtype.UUID        `db:"author" json:"author"`
}

// Approvals waiting on one of these roles: the lowest pending step of a version under review, which the
// caller neither wrote nor submitted, nor already approved at an earlier step (maker-checker).
func (q *Queries) MyPendingApprovals(ctx context.Context, arg MyPendingApprovalsParams) ([]MyPendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, myPendingApprovals, arg.Roles, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MyPendingApprovalsRow
	for rows.Next() {
		var i MyPendingApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.RecordVersionID,
			&i.StepNo,
			&i.RequestedBy,
			&i.ApproverRole,
			&i.CreatedAt,
			&i.RowVersion,
			&i.VersionNo,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextVersionNo = `-- name: NextVersionNo :one
SELECT (COALESCE(max(version_no), 0) + 1)::int FROM platform.record_versions WHERE entity_type = $1 AND entity_id = $2
`

type NextVersionNoParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

func (q *Queries) NextVersionNo(ctx context.Context, arg NextVersionNoParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextVersionNo, arg.EntityType, arg.EntityID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const openVersion = `-- name: OpenVersion :one
SELECT id, entity_type, entity_id, version_no, snapshot, diff, status, created_by, created_at, updated_at, row_version
FROM platform.record_versions WHERE entity_type = $1 AND entity_id = $2 AND status IN ('draft', 'in_review', 'approved')
FOR UPDATE
`

type OpenVersionParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

type OpenVersionRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	VersionNo  int32              `db:"version_no" json:"version_no"`
	Snapshot   []byte             `db:"snapshot" json:"snapshot"`
	Diff       []byte             `db:"diff" json:"diff"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RowVersion int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) OpenVersion(ctx context.Context, arg OpenVersionParams) (OpenVersionRow, error) {
	row := q.db.QueryRow(ctx, openVersion, arg.EntityType, arg.EntityID)
	var i OpenVersionRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNo,
		&i.Snapshot,
		&i.Diff,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const publishedVersion = `-- name: PublishedVersion :one
SELECT id, entity_type, entity_id, version_no, snapshot, diff, status, created_by, created_at, updated_at, row_version
FROM platform.record_versions WHERE entity_type = $1 AND entity_id = $2 AND status = 'published'
`

type PublishedVersionParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

type PublishedVersionRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	VersionNo  int32              `db:"version_no" json:"version_no"`
	Snapshot   []byte             `db:"snapshot" json:"snapshot"`
	Diff       []byte             `db:"diff" json:"diff"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RowVersion int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) PublishedVersion(ctx context.Context, arg PublishedVersionParams) (PublishedVersionRow, error) {
	row := q.db.QueryRow(ctx, publishedVersion, arg.EntityType, arg.EntityID)
	var i PublishedVersionRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNo,
		&i.Snapshot,
		&i.Diff,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const updateVersion = `-- name: UpdateVersion :one
UPDATE platform.record_versions
SET snapshot = $2, diff = $3, status = $4, row_version = row_version + 1,
    updated_by = NULLIF(current_setting('app.user_id', true), '')::uuid
WHERE id = $1
RETURNING id, entity_type, entity_id, version_no, snapshot, diff, status, created_by, created_at, updated_at, row_version
`

type UpdateVersionParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Snapshot []byte    `db:"snapshot" json:"snapshot"`
	Diff     []byte    `db:"diff" json:"diff"`
	Status   string    `db:"status" json:"status"`
}

type UpdateVersionRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	VersionNo  int32              `db:"version_no" json:"version_no"`
	Snapshot   []byte             `db:"snapshot" json:"snapshot"`
	Diff       []byte             `db:"diff" json:"diff"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RowVersion int32              `db:"row_version" json:"row_version"`
}

func (q *Queries) UpdateVersion(ctx context.Context, arg UpdateVersionParams) (UpdateVersionRow, error) {
	row := q.db.QueryRow(ctx, updateVersion,
		arg.ID,
		arg.Snapshot,
		arg.Diff,
		arg.Status,
	)
	var i UpdateVersionRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNo,
		&i.Snapshot,
		&i.Diff,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}
