// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookup.sql

package iamstore

import (
	"context"

	"github.com/google/uuid"
)

const activeUserNames = `-- name: ActiveUserNames :many
SELECT id, display_name FROM iam.users WHERE id = ANY ($1::uuid[]) AND status = 'active'
`

type ActiveUserNamesRow struct {
	ID          uuid.UUID `db:"id" json:"id"`
	DisplayName string    `db:"display_name" json:"display_name"`
}

func (q *Queries) ActiveUserNames(ctx context.Context, ids []uuid.UUID) ([]ActiveUserNamesRow, error) {
	rows, err := q.db.Query(ctx, activeUserNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveUserNamesRow
	for rows.Next() {
		var i ActiveUserNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActiveUsers = `-- name: SearchActiveUsers :many
SELECT id, display_name FROM iam.users
WHERE status = 'active' AND display_name ILIKE $1 || '%'
ORDER BY display_name
LIMIT 10
`

type SearchActiveUsersRow struct {
	ID          uuid.UUID `db:"id" json:"id"`
	DisplayName string    `db:"display_name" json:"display_name"`
}

// @mention picker: active users whose name starts with the query (case-insensitive). Names only — no e-mail.
func (q *Queries) SearchActiveUsers(ctx context.Context, prefix *string) ([]SearchActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, searchActiveUsers, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchActiveUsersRow
	for rows.Next() {
		var i SearchActiveUsersRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
