// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessments.sql

package vendorstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVendorAssessment = `-- name: GetVendorAssessment :one
SELECT id, vendor_id, assessment_id, cycle_no, sent_at, due_at, submitted_at, score, residual_level, decision,
    decided_by, decided_at, row_version, created_at
FROM vendor.vendor_assessments
WHERE id = $1
`

type GetVendorAssessmentRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	VendorID      uuid.UUID          `db:"vendor_id" json:"vendor_id"`
	AssessmentID  uuid.UUID          `db:"assessment_id" json:"assessment_id"`
	CycleNo       int16              `db:"cycle_no" json:"cycle_no"`
	SentAt        pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	DueAt         pgtype.Date        `db:"due_at" json:"due_at"`
	SubmittedAt   pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	Score         pgtype.Numeric     `db:"score" json:"score"`
	ResidualLevel *string            `db:"residual_level" json:"residual_level"`
	Decision      *string            `db:"decision" json:"decision"`
	DecidedBy     pgtype.UUID        `db:"decided_by" json:"decided_by"`
	DecidedAt     pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	RowVersion    int32              `db:"row_version" json:"row_version"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetVendorAssessment(ctx context.Context, id uuid.UUID) (GetVendorAssessmentRow, error) {
	row := q.db.QueryRow(ctx, getVendorAssessment, id)
	var i GetVendorAssessmentRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.AssessmentID,
		&i.CycleNo,
		&i.SentAt,
		&i.DueAt,
		&i.SubmittedAt,
		&i.Score,
		&i.ResidualLevel,
		&i.Decision,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.RowVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertVendorAssessment = `-- name: InsertVendorAssessment :one
INSERT INTO vendor.vendor_assessments (id, tenant_id, vendor_id, assessment_id, cycle_no, submitted_at, score,
    residual_level, created_by, updated_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, now(), $5,
    $6, NULLIF(current_setting('app.user_id', true), '')::uuid,
    NULLIF(current_setting('app.user_id', true), '')::uuid)
RETURNING id, vendor_id, assessment_id, cycle_no, sent_at, due_at, submitted_at, score, residual_level, decision,
    decided_by, decided_at, row_version, created_at
`

type InsertVendorAssessmentParams struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	VendorID      uuid.UUID      `db:"vendor_id" json:"vendor_id"`
	AssessmentID  uuid.UUID      `db:"assessment_id" json:"assessment_id"`
	CycleNo       int16          `db:"cycle_no" json:"cycle_no"`
	Score         pgtype.Numeric `db:"score" json:"score"`
	ResidualLevel *string        `db:"residual_level" json:"residual_level"`
}

type InsertVendorAssessmentRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	VendorID      uuid.UUID          `db:"vendor_id" json:"vendor_id"`
	AssessmentID  uuid.UUID          `db:"assessment_id" json:"assessment_id"`
	CycleNo       int16              `db:"cycle_no" json:"cycle_no"`
	SentAt        pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	DueAt         pgtype.Date        `db:"due_at" json:"due_at"`
	SubmittedAt   pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	Score         pgtype.Numeric     `db:"score" json:"score"`
	ResidualLevel *string            `db:"residual_level" json:"residual_level"`
	Decision      *string            `db:"decision" json:"decision"`
	DecidedBy     pgtype.UUID        `db:"decided_by" json:"decided_by"`
	DecidedAt     pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	RowVersion    int32              `db:"row_version" json:"row_version"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertVendorAssessment(ctx context.Context, arg InsertVendorAssessmentParams) (InsertVendorAssessmentRow, error) {
	row := q.db.QueryRow(ctx, insertVendorAssessment,
		arg.ID,
		arg.VendorID,
		arg.AssessmentID,
		arg.CycleNo,
		arg.Score,
		arg.ResidualLevel,
	)
	var i InsertVendorAssessmentRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.AssessmentID,
		&i.CycleNo,
		&i.SentAt,
		&i.DueAt,
		&i.SubmittedAt,
		&i.Score,
		&i.ResidualLevel,
		&i.Decision,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.RowVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listVendorAssessments = `-- name: ListVendorAssessments :many
SELECT id, vendor_id, assessment_id, cycle_no, sent_at, due_at, submitted_at, score, residual_level, decision,
    decided_by, decided_at, row_version, created_at
FROM vendor.vendor_assessments
WHERE vendor_id = $1
ORDER BY cycle_no DESC
`

type ListVendorAssessmentsRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	VendorID      uuid.UUID          `db:"vendor_id" json:"vendor_id"`
	AssessmentID  uuid.UUID          `db:"assessment_id" json:"assessment_id"`
	CycleNo       int16              `db:"cycle_no" json:"cycle_no"`
	SentAt        pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	DueAt         pgtype.Date        `db:"due_at" json:"due_at"`
	SubmittedAt   pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	Score         pgtype.Numeric     `db:"score" json:"score"`
	ResidualLevel *string            `db:"residual_level" json:"residual_level"`
	Decision      *string            `db:"decision" json:"decision"`
	DecidedBy     pgtype.UUID        `db:"decided_by" json:"decided_by"`
	DecidedAt     pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	RowVersion    int32              `db:"row_version" json:"row_version"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Newest cycle first.
func (q *Queries) ListVendorAssessments(ctx context.Context, vendorID uuid.UUID) ([]ListVendorAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listVendorAssessments, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVendorAssessmentsRow
	for rows.Next() {
		var i ListVendorAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.AssessmentID,
			&i.CycleNo,
			&i.SentAt,
			&i.DueAt,
			&i.SubmittedAt,
			&i.Score,
			&i.ResidualLevel,
			&i.Decision,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.RowVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextVendorAssessmentCycle = `-- name: NextVendorAssessmentCycle :one

SELECT COALESCE(MAX(cycle_no), 0)::int + 1 FROM vendor.vendor_assessments WHERE vendor_id = $1
`

// VEN-07 vendor assessment cycles (vendor.vendor_assessments — already fully specified in the baseline
// migrations, including the review/decision columns VEN-08 will write to).
func (q *Queries) NextVendorAssessmentCycle(ctx context.Context, vendorID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextVendorAssessmentCycle, vendorID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
