// Package notifyhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package notifyhttp

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FormConditionOp.
const (
	Answered    FormConditionOp = "answered"
	Eq          FormConditionOp = "eq"
	Gt          FormConditionOp = "gt"
	Gte         FormConditionOp = "gte"
	In          FormConditionOp = "in"
	Lt          FormConditionOp = "lt"
	Lte         FormConditionOp = "lte"
	Neq         FormConditionOp = "neq"
	NotAnswered FormConditionOp = "not_answered"
	NotIn       FormConditionOp = "not_in"
)

// Valid indicates whether the value is a known member of the FormConditionOp enum.
func (e FormConditionOp) Valid() bool {
	switch e {
	case Answered:
		return true
	case Eq:
		return true
	case Gt:
		return true
	case Gte:
		return true
	case In:
		return true
	case Lt:
		return true
	case Lte:
		return true
	case Neq:
		return true
	case NotAnswered:
		return true
	case NotIn:
		return true
	default:
		return false
	}
}

// Defines values for NotificationChannel.
const (
	Email NotificationChannel = "email"
	InApp NotificationChannel = "in_app"
	Line  NotificationChannel = "line"
	Sms   NotificationChannel = "sms"
)

// Valid indicates whether the value is a known member of the NotificationChannel enum.
func (e NotificationChannel) Valid() bool {
	switch e {
	case Email:
		return true
	case InApp:
		return true
	case Line:
		return true
	case Sms:
		return true
	default:
		return false
	}
}

// Defines values for NotificationStatus.
const (
	Cancelled NotificationStatus = "cancelled"
	Delivered NotificationStatus = "delivered"
	Failed    NotificationStatus = "failed"
	Queued    NotificationStatus = "queued"
	Sent      NotificationStatus = "sent"
)

// Valid indicates whether the value is a known member of the NotificationStatus enum.
func (e NotificationStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Delivered:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Sent:
		return true
	default:
		return false
	}
}

// Defines values for NotificationTemplateInputLanguage.
const (
	NotificationTemplateInputLanguageEn NotificationTemplateInputLanguage = "en"
	NotificationTemplateInputLanguageTh NotificationTemplateInputLanguage = "th"
)

// Valid indicates whether the value is a known member of the NotificationTemplateInputLanguage enum.
func (e NotificationTemplateInputLanguage) Valid() bool {
	switch e {
	case NotificationTemplateInputLanguageEn:
		return true
	case NotificationTemplateInputLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for AcceptLanguage.
const (
	AcceptLanguageEn AcceptLanguage = "en"
	AcceptLanguageTh AcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the AcceptLanguage enum.
func (e AcceptLanguage) Valid() bool {
	switch e {
	case AcceptLanguageEn:
		return true
	case AcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformGetInboxParamsAcceptLanguage.
const (
	PlatformGetInboxParamsAcceptLanguageEn PlatformGetInboxParamsAcceptLanguage = "en"
	PlatformGetInboxParamsAcceptLanguageTh PlatformGetInboxParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformGetInboxParamsAcceptLanguage enum.
func (e PlatformGetInboxParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformGetInboxParamsAcceptLanguageEn:
		return true
	case PlatformGetInboxParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformMarkInboxReadParamsAcceptLanguage.
const (
	PlatformMarkInboxReadParamsAcceptLanguageEn PlatformMarkInboxReadParamsAcceptLanguage = "en"
	PlatformMarkInboxReadParamsAcceptLanguageTh PlatformMarkInboxReadParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformMarkInboxReadParamsAcceptLanguage enum.
func (e PlatformMarkInboxReadParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformMarkInboxReadParamsAcceptLanguageEn:
		return true
	case PlatformMarkInboxReadParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformListNotificationTemplatesParamsAcceptLanguage.
const (
	PlatformListNotificationTemplatesParamsAcceptLanguageEn PlatformListNotificationTemplatesParamsAcceptLanguage = "en"
	PlatformListNotificationTemplatesParamsAcceptLanguageTh PlatformListNotificationTemplatesParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformListNotificationTemplatesParamsAcceptLanguage enum.
func (e PlatformListNotificationTemplatesParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformListNotificationTemplatesParamsAcceptLanguageEn:
		return true
	case PlatformListNotificationTemplatesParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformCreateNotificationTemplateParamsAcceptLanguage.
const (
	PlatformCreateNotificationTemplateParamsAcceptLanguageEn PlatformCreateNotificationTemplateParamsAcceptLanguage = "en"
	PlatformCreateNotificationTemplateParamsAcceptLanguageTh PlatformCreateNotificationTemplateParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformCreateNotificationTemplateParamsAcceptLanguage enum.
func (e PlatformCreateNotificationTemplateParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformCreateNotificationTemplateParamsAcceptLanguageEn:
		return true
	case PlatformCreateNotificationTemplateParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformPreviewNotificationTemplateParamsAcceptLanguage.
const (
	PlatformPreviewNotificationTemplateParamsAcceptLanguageEn PlatformPreviewNotificationTemplateParamsAcceptLanguage = "en"
	PlatformPreviewNotificationTemplateParamsAcceptLanguageTh PlatformPreviewNotificationTemplateParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformPreviewNotificationTemplateParamsAcceptLanguage enum.
func (e PlatformPreviewNotificationTemplateParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformPreviewNotificationTemplateParamsAcceptLanguageEn:
		return true
	case PlatformPreviewNotificationTemplateParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformDeleteNotificationTemplateParamsAcceptLanguage.
const (
	PlatformDeleteNotificationTemplateParamsAcceptLanguageEn PlatformDeleteNotificationTemplateParamsAcceptLanguage = "en"
	PlatformDeleteNotificationTemplateParamsAcceptLanguageTh PlatformDeleteNotificationTemplateParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformDeleteNotificationTemplateParamsAcceptLanguage enum.
func (e PlatformDeleteNotificationTemplateParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformDeleteNotificationTemplateParamsAcceptLanguageEn:
		return true
	case PlatformDeleteNotificationTemplateParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformGetNotificationTemplateParamsAcceptLanguage.
const (
	PlatformGetNotificationTemplateParamsAcceptLanguageEn PlatformGetNotificationTemplateParamsAcceptLanguage = "en"
	PlatformGetNotificationTemplateParamsAcceptLanguageTh PlatformGetNotificationTemplateParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformGetNotificationTemplateParamsAcceptLanguage enum.
func (e PlatformGetNotificationTemplateParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformGetNotificationTemplateParamsAcceptLanguageEn:
		return true
	case PlatformGetNotificationTemplateParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformUpdateNotificationTemplateParamsAcceptLanguage.
const (
	PlatformUpdateNotificationTemplateParamsAcceptLanguageEn PlatformUpdateNotificationTemplateParamsAcceptLanguage = "en"
	PlatformUpdateNotificationTemplateParamsAcceptLanguageTh PlatformUpdateNotificationTemplateParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformUpdateNotificationTemplateParamsAcceptLanguage enum.
func (e PlatformUpdateNotificationTemplateParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformUpdateNotificationTemplateParamsAcceptLanguageEn:
		return true
	case PlatformUpdateNotificationTemplateParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformListNotificationsParamsAcceptLanguage.
const (
	PlatformListNotificationsParamsAcceptLanguageEn PlatformListNotificationsParamsAcceptLanguage = "en"
	PlatformListNotificationsParamsAcceptLanguageTh PlatformListNotificationsParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformListNotificationsParamsAcceptLanguage enum.
func (e PlatformListNotificationsParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformListNotificationsParamsAcceptLanguageEn:
		return true
	case PlatformListNotificationsParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// Defines values for PlatformGetNotificationParamsAcceptLanguage.
const (
	PlatformGetNotificationParamsAcceptLanguageEn PlatformGetNotificationParamsAcceptLanguage = "en"
	PlatformGetNotificationParamsAcceptLanguageTh PlatformGetNotificationParamsAcceptLanguage = "th"
)

// Valid indicates whether the value is a known member of the PlatformGetNotificationParamsAcceptLanguage enum.
func (e PlatformGetNotificationParamsAcceptLanguage) Valid() bool {
	switch e {
	case PlatformGetNotificationParamsAcceptLanguageEn:
		return true
	case PlatformGetNotificationParamsAcceptLanguageTh:
		return true
	default:
		return false
	}
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string  `json:"code"`
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
}

// FormCondition Show when an earlier question's answer compares true (question + op + value), or all/any of nested conditions
type FormCondition struct {
	All      *[]FormCondition `json:"all,omitempty"`
	Any      *[]FormCondition `json:"any,omitempty"`
	Op       *FormConditionOp `json:"op,omitempty"`
	Question *string          `json:"question,omitempty"`
	Value    interface{}      `json:"value,omitempty"`
}

// FormConditionOp defines model for FormCondition.Op.
type FormConditionOp string

// Inbox defines model for Inbox.
type Inbox struct {
	Items []struct {
		Body string `json:"body"`

		// CreatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
		CreatedAt Timestamp `json:"created_at"`

		// Id UUIDv7 generated by the API
		Id    Uuid   `json:"id"`
		Read  bool   `json:"read"`
		Title string `json:"title"`
	} `json:"items"`
	Unread int `json:"unread"`
}

// NotificationChannel defines model for NotificationChannel.
type NotificationChannel string

// NotificationDelivery defines model for NotificationDelivery.
type NotificationDelivery struct {
	Attempts int                 `json:"attempts"`
	Channel  NotificationChannel `json:"channel"`

	// CreatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	CreatedAt  Timestamp `json:"created_at"`
	EntityId   *Uuid     `json:"entity_id,omitempty"`
	EntityType *string   `json:"entity_type,omitempty"`

	// Error Last failure, with addresses and numbers removed
	Error *string `json:"error,omitempty"`

	// Id UUIDv7 generated by the API
	Id                Uuid    `json:"id"`
	ProviderMessageId *string `json:"provider_message_id,omitempty"`

	// RecipientMasked Masked address, e.g. so****@example.co.th (empty for user recipients)
	RecipientMasked *string            `json:"recipient_masked,omitempty"`
	RecipientUserId *Uuid              `json:"recipient_user_id,omitempty"`
	SentAt          *Timestamp         `json:"sent_at,omitempty"`
	Status          NotificationStatus `json:"status"`
	TemplateCode    *string            `json:"template_code,omitempty"`

	// UpdatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	UpdatedAt Timestamp `json:"updated_at"`
}

// NotificationStatus defines model for NotificationStatus.
type NotificationStatus string

// NotificationTemplate defines model for NotificationTemplate.
type NotificationTemplate struct {
	Body    string              `json:"body"`
	Channel NotificationChannel `json:"channel"`
	Code    string              `json:"code"`

	// Global A platform template (read-only for tenants; override it by creating your own)
	Global bool `json:"global"`

	// Id UUIDv7 generated by the API
	Id         Uuid    `json:"id"`
	Language   string  `json:"language"`
	RowVersion int     `json:"row_version"`
	Subject    *string `json:"subject,omitempty"`

	// UpdatedAt RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
	UpdatedAt Timestamp `json:"updated_at"`
	Variables []string  `json:"variables"`
}

// NotificationTemplateInput defines model for NotificationTemplateInput.
type NotificationTemplateInput struct {
	// Body text/template syntax, e.g. {{.request_no}}; every variable used must be declared
	Body      string                            `json:"body"`
	Channel   NotificationChannel               `json:"channel"`
	Code      string                            `json:"code"`
	Language  NotificationTemplateInputLanguage `json:"language"`
	Subject   *string                           `json:"subject,omitempty"`
	Variables *[]string                         `json:"variables,omitempty"`
}

// NotificationTemplateInputLanguage defines model for NotificationTemplateInput.Language.
type NotificationTemplateInputLanguage string

// Problem RFC 9457 problem details with a stable machine-readable `code`
type Problem struct {
	Code      string        `json:"code"`
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// Timestamp RFC 3339 in UTC, e.g. 2026-09-25T03:15:00Z
type Timestamp = time.Time

// Uuid UUIDv7 generated by the API
type Uuid = openapi_types.UUID

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage string

// Cursor defines model for Cursor.
type Cursor = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// BadRequest RFC 9457 problem details with a stable machine-readable `code`
type BadRequest = Problem

// Conflict RFC 9457 problem details with a stable machine-readable `code`
type Conflict = Problem

// Forbidden RFC 9457 problem details with a stable machine-readable `code`
type Forbidden = Problem

// NotFound RFC 9457 problem details with a stable machine-readable `code`
type NotFound = Problem

// PreconditionFailed RFC 9457 problem details with a stable machine-readable `code`
type PreconditionFailed = Problem

// PreconditionRequired RFC 9457 problem details with a stable machine-readable `code`
type PreconditionRequired = Problem

// Unauthorized RFC 9457 problem details with a stable machine-readable `code`
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 problem details with a stable machine-readable `code`
type UnprocessableEntity = Problem

// PlatformGetInboxParams defines parameters for PlatformGetInbox.
type PlatformGetInboxParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformGetInboxParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformGetInboxParamsAcceptLanguage defines parameters for PlatformGetInbox.
type PlatformGetInboxParamsAcceptLanguage string

// PlatformMarkInboxReadParams defines parameters for PlatformMarkInboxRead.
type PlatformMarkInboxReadParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformMarkInboxReadParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformMarkInboxReadParamsAcceptLanguage defines parameters for PlatformMarkInboxRead.
type PlatformMarkInboxReadParamsAcceptLanguage string

// PlatformListNotificationTemplatesParams defines parameters for PlatformListNotificationTemplates.
type PlatformListNotificationTemplatesParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformListNotificationTemplatesParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformListNotificationTemplatesParamsAcceptLanguage defines parameters for PlatformListNotificationTemplates.
type PlatformListNotificationTemplatesParamsAcceptLanguage string

// PlatformCreateNotificationTemplateParams defines parameters for PlatformCreateNotificationTemplate.
type PlatformCreateNotificationTemplateParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformCreateNotificationTemplateParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformCreateNotificationTemplateParamsAcceptLanguage defines parameters for PlatformCreateNotificationTemplate.
type PlatformCreateNotificationTemplateParamsAcceptLanguage string

// PlatformPreviewNotificationTemplateJSONBody defines parameters for PlatformPreviewNotificationTemplate.
type PlatformPreviewNotificationTemplateJSONBody struct {
	Body      string             `json:"body"`
	Subject   *string            `json:"subject,omitempty"`
	Values    *map[string]string `json:"values,omitempty"`
	Variables *[]string          `json:"variables,omitempty"`
}

// PlatformPreviewNotificationTemplateParams defines parameters for PlatformPreviewNotificationTemplate.
type PlatformPreviewNotificationTemplateParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformPreviewNotificationTemplateParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformPreviewNotificationTemplateParamsAcceptLanguage defines parameters for PlatformPreviewNotificationTemplate.
type PlatformPreviewNotificationTemplateParamsAcceptLanguage string

// PlatformDeleteNotificationTemplateParams defines parameters for PlatformDeleteNotificationTemplate.
type PlatformDeleteNotificationTemplateParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformDeleteNotificationTemplateParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// PlatformDeleteNotificationTemplateParamsAcceptLanguage defines parameters for PlatformDeleteNotificationTemplate.
type PlatformDeleteNotificationTemplateParamsAcceptLanguage string

// PlatformGetNotificationTemplateParams defines parameters for PlatformGetNotificationTemplate.
type PlatformGetNotificationTemplateParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformGetNotificationTemplateParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformGetNotificationTemplateParamsAcceptLanguage defines parameters for PlatformGetNotificationTemplate.
type PlatformGetNotificationTemplateParamsAcceptLanguage string

// PlatformUpdateNotificationTemplateJSONBody defines parameters for PlatformUpdateNotificationTemplate.
type PlatformUpdateNotificationTemplateJSONBody struct {
	Body      string    `json:"body"`
	Subject   *string   `json:"subject,omitempty"`
	Variables *[]string `json:"variables,omitempty"`
}

// PlatformUpdateNotificationTemplateParams defines parameters for PlatformUpdateNotificationTemplate.
type PlatformUpdateNotificationTemplateParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformUpdateNotificationTemplateParamsAcceptLanguage `json:"Accept-Language,omitempty"`

	// IfMatch ETag (row_version) of the resource being modified. Mismatch → 412, missing → 428.
	IfMatch IfMatch `json:"If-Match"`
}

// PlatformUpdateNotificationTemplateParamsAcceptLanguage defines parameters for PlatformUpdateNotificationTemplate.
type PlatformUpdateNotificationTemplateParamsAcceptLanguage string

// PlatformListNotificationsParams defines parameters for PlatformListNotifications.
type PlatformListNotificationsParams struct {
	// Cursor Opaque cursor from `next_cursor` of the previous page
	Cursor  *Cursor              `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit   *Limit               `form:"limit,omitempty" json:"limit,omitempty"`
	Status  *NotificationStatus  `form:"status,omitempty" json:"status,omitempty"`
	Channel *NotificationChannel `form:"channel,omitempty" json:"channel,omitempty"`

	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformListNotificationsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformListNotificationsParamsAcceptLanguage defines parameters for PlatformListNotifications.
type PlatformListNotificationsParamsAcceptLanguage string

// PlatformGetNotificationParams defines parameters for PlatformGetNotification.
type PlatformGetNotificationParams struct {
	// AcceptLanguage Language of messages and localized fields (default th)
	AcceptLanguage *PlatformGetNotificationParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PlatformGetNotificationParamsAcceptLanguage defines parameters for PlatformGetNotification.
type PlatformGetNotificationParamsAcceptLanguage string

// PlatformCreateNotificationTemplateJSONRequestBody defines body for PlatformCreateNotificationTemplate for application/json ContentType.
type PlatformCreateNotificationTemplateJSONRequestBody = NotificationTemplateInput

// PlatformPreviewNotificationTemplateJSONRequestBody defines body for PlatformPreviewNotificationTemplate for application/json ContentType.
type PlatformPreviewNotificationTemplateJSONRequestBody PlatformPreviewNotificationTemplateJSONBody

// PlatformUpdateNotificationTemplateJSONRequestBody defines body for PlatformUpdateNotificationTemplate for application/json ContentType.
type PlatformUpdateNotificationTemplateJSONRequestBody PlatformUpdateNotificationTemplateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PlatformGetInbox The signed-in user's in-app notifications and unread count (the bell)
	// (GET /admin/v1/platform/inbox)
	PlatformGetInbox(w http.ResponseWriter, r *http.Request, params PlatformGetInboxParams)
	// PlatformMarkInboxRead Mark one of the user's own in-app notifications read
	// (POST /admin/v1/platform/inbox/{id}/read)
	PlatformMarkInboxRead(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformMarkInboxReadParams)
	// PlatformListNotificationTemplates Notification templates visible to the tenant (its own and the platform's global ones)
	// (GET /admin/v1/platform/notification-templates)
	PlatformListNotificationTemplates(w http.ResponseWriter, r *http.Request, params PlatformListNotificationTemplatesParams)
	// PlatformCreateNotificationTemplate Create a tenant template (or override a global one with the same code, channel and language)
	// (POST /admin/v1/platform/notification-templates)
	PlatformCreateNotificationTemplate(w http.ResponseWriter, r *http.Request, params PlatformCreateNotificationTemplateParams)
	// PlatformPreviewNotificationTemplate Render a template with sample values (declared variables not given show as {name})
	// (POST /admin/v1/platform/notification-templates/preview)
	PlatformPreviewNotificationTemplate(w http.ResponseWriter, r *http.Request, params PlatformPreviewNotificationTemplateParams)
	// PlatformDeleteNotificationTemplate Delete a tenant template
	// (DELETE /admin/v1/platform/notification-templates/{id})
	PlatformDeleteNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformDeleteNotificationTemplateParams)
	// PlatformGetNotificationTemplate One template
	// (GET /admin/v1/platform/notification-templates/{id})
	PlatformGetNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetNotificationTemplateParams)
	// PlatformUpdateNotificationTemplate Change subject, body and variables of a tenant template (global templates are read-only)
	// (PATCH /admin/v1/platform/notification-templates/{id})
	PlatformUpdateNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformUpdateNotificationTemplateParams)
	// PlatformListNotifications Delivery log — status of every message, newest first (PLT-04)
	// (GET /admin/v1/platform/notifications)
	PlatformListNotifications(w http.ResponseWriter, r *http.Request, params PlatformListNotificationsParams)
	// PlatformGetNotification Delivery status of one message
	// (GET /admin/v1/platform/notifications/{id})
	PlatformGetNotification(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetNotificationParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// PlatformGetInbox The signed-in user's in-app notifications and unread count (the bell)
// (GET /admin/v1/platform/inbox)
func (_ Unimplemented) PlatformGetInbox(w http.ResponseWriter, r *http.Request, params PlatformGetInboxParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformMarkInboxRead Mark one of the user's own in-app notifications read
// (POST /admin/v1/platform/inbox/{id}/read)
func (_ Unimplemented) PlatformMarkInboxRead(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformMarkInboxReadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformListNotificationTemplates Notification templates visible to the tenant (its own and the platform's global ones)
// (GET /admin/v1/platform/notification-templates)
func (_ Unimplemented) PlatformListNotificationTemplates(w http.ResponseWriter, r *http.Request, params PlatformListNotificationTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformCreateNotificationTemplate Create a tenant template (or override a global one with the same code, channel and language)
// (POST /admin/v1/platform/notification-templates)
func (_ Unimplemented) PlatformCreateNotificationTemplate(w http.ResponseWriter, r *http.Request, params PlatformCreateNotificationTemplateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformPreviewNotificationTemplate Render a template with sample values (declared variables not given show as {name})
// (POST /admin/v1/platform/notification-templates/preview)
func (_ Unimplemented) PlatformPreviewNotificationTemplate(w http.ResponseWriter, r *http.Request, params PlatformPreviewNotificationTemplateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformDeleteNotificationTemplate Delete a tenant template
// (DELETE /admin/v1/platform/notification-templates/{id})
func (_ Unimplemented) PlatformDeleteNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformDeleteNotificationTemplateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformGetNotificationTemplate One template
// (GET /admin/v1/platform/notification-templates/{id})
func (_ Unimplemented) PlatformGetNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetNotificationTemplateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformUpdateNotificationTemplate Change subject, body and variables of a tenant template (global templates are read-only)
// (PATCH /admin/v1/platform/notification-templates/{id})
func (_ Unimplemented) PlatformUpdateNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformUpdateNotificationTemplateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformListNotifications Delivery log — status of every message, newest first (PLT-04)
// (GET /admin/v1/platform/notifications)
func (_ Unimplemented) PlatformListNotifications(w http.ResponseWriter, r *http.Request, params PlatformListNotificationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlatformGetNotification Delivery status of one message
// (GET /admin/v1/platform/notifications/{id})
func (_ Unimplemented) PlatformGetNotification(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetNotificationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PlatformGetInbox operation middleware
func (siw *ServerInterfaceWrapper) PlatformGetInbox(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformGetInboxParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformGetInboxParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformGetInbox(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformMarkInboxRead operation middleware
func (siw *ServerInterfaceWrapper) PlatformMarkInboxRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformMarkInboxReadParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformMarkInboxReadParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformMarkInboxRead(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformListNotificationTemplates operation middleware
func (siw *ServerInterfaceWrapper) PlatformListNotificationTemplates(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformListNotificationTemplatesParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformListNotificationTemplatesParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformListNotificationTemplates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformCreateNotificationTemplate operation middleware
func (siw *ServerInterfaceWrapper) PlatformCreateNotificationTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformCreateNotificationTemplateParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformCreateNotificationTemplateParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformCreateNotificationTemplate(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformPreviewNotificationTemplate operation middleware
func (siw *ServerInterfaceWrapper) PlatformPreviewNotificationTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformPreviewNotificationTemplateParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformPreviewNotificationTemplateParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformPreviewNotificationTemplate(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformDeleteNotificationTemplate operation middleware
func (siw *ServerInterfaceWrapper) PlatformDeleteNotificationTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformDeleteNotificationTemplateParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformDeleteNotificationTemplateParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformDeleteNotificationTemplate(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformGetNotificationTemplate operation middleware
func (siw *ServerInterfaceWrapper) PlatformGetNotificationTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformGetNotificationTemplateParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformGetNotificationTemplateParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformGetNotificationTemplate(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformUpdateNotificationTemplate operation middleware
func (siw *ServerInterfaceWrapper) PlatformUpdateNotificationTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformUpdateNotificationTemplateParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformUpdateNotificationTemplateParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformUpdateNotificationTemplate(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformListNotifications operation middleware
func (siw *ServerInterfaceWrapper) PlatformListNotifications(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformListNotificationsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channel", r.URL.Query(), &params.Channel, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channel"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformListNotificationsParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformListNotifications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlatformGetNotification operation middleware
func (siw *ServerInterfaceWrapper) PlatformGetNotification(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PlatformGetNotificationParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage PlatformGetNotificationParamsAcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlatformGetNotification(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/notification-templates", wrapper.PlatformListNotificationTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/platform/notification-templates", wrapper.PlatformCreateNotificationTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/platform/notification-templates/preview", wrapper.PlatformPreviewNotificationTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/v1/platform/notification-templates/{id}", wrapper.PlatformDeleteNotificationTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/notification-templates/{id}", wrapper.PlatformGetNotificationTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/v1/platform/notification-templates/{id}", wrapper.PlatformUpdateNotificationTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/notifications", wrapper.PlatformListNotifications)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/notifications/{id}", wrapper.PlatformGetNotification)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/platform/inbox", wrapper.PlatformGetInbox)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/platform/inbox/{id}/read", wrapper.PlatformMarkInboxRead)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type PreconditionFailedApplicationProblemPlusJSONResponse Problem

type PreconditionRequiredApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type PlatformGetInboxRequestObject struct {
	Params PlatformGetInboxParams
}

type PlatformGetInboxResponseObject interface {
	VisitPlatformGetInboxResponse(w http.ResponseWriter) error
}

type PlatformGetInbox200JSONResponse Inbox

func (response PlatformGetInbox200JSONResponse) VisitPlatformGetInboxResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetInbox401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformGetInbox401ApplicationProblemPlusJSONResponse) VisitPlatformGetInboxResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformMarkInboxReadRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformMarkInboxReadParams
}

type PlatformMarkInboxReadResponseObject interface {
	VisitPlatformMarkInboxReadResponse(w http.ResponseWriter) error
}

type PlatformMarkInboxRead204Response struct {
}

func (response PlatformMarkInboxRead204Response) VisitPlatformMarkInboxReadResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PlatformMarkInboxRead401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformMarkInboxRead401ApplicationProblemPlusJSONResponse) VisitPlatformMarkInboxReadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformMarkInboxRead404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformMarkInboxRead404ApplicationProblemPlusJSONResponse) VisitPlatformMarkInboxReadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListNotificationTemplatesRequestObject struct {
	Params PlatformListNotificationTemplatesParams
}

type PlatformListNotificationTemplatesResponseObject interface {
	VisitPlatformListNotificationTemplatesResponse(w http.ResponseWriter) error
}

type PlatformListNotificationTemplates200JSONResponse struct {
	Data []NotificationTemplate `json:"data"`
}

func (response PlatformListNotificationTemplates200JSONResponse) VisitPlatformListNotificationTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListNotificationTemplates401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformListNotificationTemplates401ApplicationProblemPlusJSONResponse) VisitPlatformListNotificationTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListNotificationTemplates403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformListNotificationTemplates403ApplicationProblemPlusJSONResponse) VisitPlatformListNotificationTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCreateNotificationTemplateRequestObject struct {
	Params PlatformCreateNotificationTemplateParams
	Body   *PlatformCreateNotificationTemplateJSONRequestBody
}

type PlatformCreateNotificationTemplateResponseObject interface {
	VisitPlatformCreateNotificationTemplateResponse(w http.ResponseWriter) error
}

type PlatformCreateNotificationTemplate201ResponseHeaders struct {
	ETag *string
}

type PlatformCreateNotificationTemplate201JSONResponse struct {
	Body    NotificationTemplate
	Headers PlatformCreateNotificationTemplate201ResponseHeaders
}

func (response PlatformCreateNotificationTemplate201JSONResponse) VisitPlatformCreateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCreateNotificationTemplate400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PlatformCreateNotificationTemplate400ApplicationProblemPlusJSONResponse) VisitPlatformCreateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCreateNotificationTemplate401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformCreateNotificationTemplate401ApplicationProblemPlusJSONResponse) VisitPlatformCreateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCreateNotificationTemplate403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformCreateNotificationTemplate403ApplicationProblemPlusJSONResponse) VisitPlatformCreateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCreateNotificationTemplate409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response PlatformCreateNotificationTemplate409ApplicationProblemPlusJSONResponse) VisitPlatformCreateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformCreateNotificationTemplate422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response PlatformCreateNotificationTemplate422ApplicationProblemPlusJSONResponse) VisitPlatformCreateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPreviewNotificationTemplateRequestObject struct {
	Params PlatformPreviewNotificationTemplateParams
	Body   *PlatformPreviewNotificationTemplateJSONRequestBody
}

type PlatformPreviewNotificationTemplateResponseObject interface {
	VisitPlatformPreviewNotificationTemplateResponse(w http.ResponseWriter) error
}

type PlatformPreviewNotificationTemplate200JSONResponse struct {
	Body    string  `json:"body"`
	Subject *string `json:"subject,omitempty"`
}

func (response PlatformPreviewNotificationTemplate200JSONResponse) VisitPlatformPreviewNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPreviewNotificationTemplate401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformPreviewNotificationTemplate401ApplicationProblemPlusJSONResponse) VisitPlatformPreviewNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPreviewNotificationTemplate403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformPreviewNotificationTemplate403ApplicationProblemPlusJSONResponse) VisitPlatformPreviewNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformPreviewNotificationTemplate422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response PlatformPreviewNotificationTemplate422ApplicationProblemPlusJSONResponse) VisitPlatformPreviewNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDeleteNotificationTemplateRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformDeleteNotificationTemplateParams
}

type PlatformDeleteNotificationTemplateResponseObject interface {
	VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error
}

type PlatformDeleteNotificationTemplate204Response struct {
}

func (response PlatformDeleteNotificationTemplate204Response) VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PlatformDeleteNotificationTemplate401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformDeleteNotificationTemplate401ApplicationProblemPlusJSONResponse) VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDeleteNotificationTemplate403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformDeleteNotificationTemplate403ApplicationProblemPlusJSONResponse) VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDeleteNotificationTemplate404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformDeleteNotificationTemplate404ApplicationProblemPlusJSONResponse) VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDeleteNotificationTemplate412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response PlatformDeleteNotificationTemplate412ApplicationProblemPlusJSONResponse) VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDeleteNotificationTemplate422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response PlatformDeleteNotificationTemplate422ApplicationProblemPlusJSONResponse) VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformDeleteNotificationTemplate428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response PlatformDeleteNotificationTemplate428ApplicationProblemPlusJSONResponse) VisitPlatformDeleteNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotificationTemplateRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformGetNotificationTemplateParams
}

type PlatformGetNotificationTemplateResponseObject interface {
	VisitPlatformGetNotificationTemplateResponse(w http.ResponseWriter) error
}

type PlatformGetNotificationTemplate200ResponseHeaders struct {
	ETag *string
}

type PlatformGetNotificationTemplate200JSONResponse struct {
	Body    NotificationTemplate
	Headers PlatformGetNotificationTemplate200ResponseHeaders
}

func (response PlatformGetNotificationTemplate200JSONResponse) VisitPlatformGetNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotificationTemplate401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformGetNotificationTemplate401ApplicationProblemPlusJSONResponse) VisitPlatformGetNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotificationTemplate403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformGetNotificationTemplate403ApplicationProblemPlusJSONResponse) VisitPlatformGetNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotificationTemplate404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformGetNotificationTemplate404ApplicationProblemPlusJSONResponse) VisitPlatformGetNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformUpdateNotificationTemplateRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformUpdateNotificationTemplateParams
	Body   *PlatformUpdateNotificationTemplateJSONRequestBody
}

type PlatformUpdateNotificationTemplateResponseObject interface {
	VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error
}

type PlatformUpdateNotificationTemplate200ResponseHeaders struct {
	ETag *string
}

type PlatformUpdateNotificationTemplate200JSONResponse struct {
	Body    NotificationTemplate
	Headers PlatformUpdateNotificationTemplate200ResponseHeaders
}

func (response PlatformUpdateNotificationTemplate200JSONResponse) VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformUpdateNotificationTemplate401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformUpdateNotificationTemplate401ApplicationProblemPlusJSONResponse) VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformUpdateNotificationTemplate403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformUpdateNotificationTemplate403ApplicationProblemPlusJSONResponse) VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformUpdateNotificationTemplate404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformUpdateNotificationTemplate404ApplicationProblemPlusJSONResponse) VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformUpdateNotificationTemplate412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response PlatformUpdateNotificationTemplate412ApplicationProblemPlusJSONResponse) VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformUpdateNotificationTemplate422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response PlatformUpdateNotificationTemplate422ApplicationProblemPlusJSONResponse) VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformUpdateNotificationTemplate428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response PlatformUpdateNotificationTemplate428ApplicationProblemPlusJSONResponse) VisitPlatformUpdateNotificationTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListNotificationsRequestObject struct {
	Params PlatformListNotificationsParams
}

type PlatformListNotificationsResponseObject interface {
	VisitPlatformListNotificationsResponse(w http.ResponseWriter) error
}

type PlatformListNotifications200JSONResponse struct {
	Data       []NotificationDelivery `json:"data"`
	NextCursor *string                `json:"next_cursor"`
}

func (response PlatformListNotifications200JSONResponse) VisitPlatformListNotificationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListNotifications400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PlatformListNotifications400ApplicationProblemPlusJSONResponse) VisitPlatformListNotificationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListNotifications401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformListNotifications401ApplicationProblemPlusJSONResponse) VisitPlatformListNotificationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformListNotifications403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformListNotifications403ApplicationProblemPlusJSONResponse) VisitPlatformListNotificationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotificationRequestObject struct {
	Id     Uuid `json:"id"`
	Params PlatformGetNotificationParams
}

type PlatformGetNotificationResponseObject interface {
	VisitPlatformGetNotificationResponse(w http.ResponseWriter) error
}

type PlatformGetNotification200JSONResponse NotificationDelivery

func (response PlatformGetNotification200JSONResponse) VisitPlatformGetNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotification401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PlatformGetNotification401ApplicationProblemPlusJSONResponse) VisitPlatformGetNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotification403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PlatformGetNotification403ApplicationProblemPlusJSONResponse) VisitPlatformGetNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformGetNotification404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PlatformGetNotification404ApplicationProblemPlusJSONResponse) VisitPlatformGetNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// PlatformGetInbox The signed-in user's in-app notifications and unread count (the bell)
	// (GET /admin/v1/platform/inbox)
	PlatformGetInbox(ctx context.Context, request PlatformGetInboxRequestObject) (PlatformGetInboxResponseObject, error)
	// PlatformMarkInboxRead Mark one of the user's own in-app notifications read
	// (POST /admin/v1/platform/inbox/{id}/read)
	PlatformMarkInboxRead(ctx context.Context, request PlatformMarkInboxReadRequestObject) (PlatformMarkInboxReadResponseObject, error)
	// PlatformListNotificationTemplates Notification templates visible to the tenant (its own and the platform's global ones)
	// (GET /admin/v1/platform/notification-templates)
	PlatformListNotificationTemplates(ctx context.Context, request PlatformListNotificationTemplatesRequestObject) (PlatformListNotificationTemplatesResponseObject, error)
	// PlatformCreateNotificationTemplate Create a tenant template (or override a global one with the same code, channel and language)
	// (POST /admin/v1/platform/notification-templates)
	PlatformCreateNotificationTemplate(ctx context.Context, request PlatformCreateNotificationTemplateRequestObject) (PlatformCreateNotificationTemplateResponseObject, error)
	// PlatformPreviewNotificationTemplate Render a template with sample values (declared variables not given show as {name})
	// (POST /admin/v1/platform/notification-templates/preview)
	PlatformPreviewNotificationTemplate(ctx context.Context, request PlatformPreviewNotificationTemplateRequestObject) (PlatformPreviewNotificationTemplateResponseObject, error)
	// PlatformDeleteNotificationTemplate Delete a tenant template
	// (DELETE /admin/v1/platform/notification-templates/{id})
	PlatformDeleteNotificationTemplate(ctx context.Context, request PlatformDeleteNotificationTemplateRequestObject) (PlatformDeleteNotificationTemplateResponseObject, error)
	// PlatformGetNotificationTemplate One template
	// (GET /admin/v1/platform/notification-templates/{id})
	PlatformGetNotificationTemplate(ctx context.Context, request PlatformGetNotificationTemplateRequestObject) (PlatformGetNotificationTemplateResponseObject, error)
	// PlatformUpdateNotificationTemplate Change subject, body and variables of a tenant template (global templates are read-only)
	// (PATCH /admin/v1/platform/notification-templates/{id})
	PlatformUpdateNotificationTemplate(ctx context.Context, request PlatformUpdateNotificationTemplateRequestObject) (PlatformUpdateNotificationTemplateResponseObject, error)
	// PlatformListNotifications Delivery log — status of every message, newest first (PLT-04)
	// (GET /admin/v1/platform/notifications)
	PlatformListNotifications(ctx context.Context, request PlatformListNotificationsRequestObject) (PlatformListNotificationsResponseObject, error)
	// PlatformGetNotification Delivery status of one message
	// (GET /admin/v1/platform/notifications/{id})
	PlatformGetNotification(ctx context.Context, request PlatformGetNotificationRequestObject) (PlatformGetNotificationResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PlatformGetInbox operation middleware
func (sh *strictHandler) PlatformGetInbox(w http.ResponseWriter, r *http.Request, params PlatformGetInboxParams) {
	var request PlatformGetInboxRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformGetInbox(ctx, request.(PlatformGetInboxRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformGetInbox")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformGetInboxResponseObject); ok {
		if err := validResponse.VisitPlatformGetInboxResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformMarkInboxRead operation middleware
func (sh *strictHandler) PlatformMarkInboxRead(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformMarkInboxReadParams) {
	var request PlatformMarkInboxReadRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformMarkInboxRead(ctx, request.(PlatformMarkInboxReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformMarkInboxRead")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformMarkInboxReadResponseObject); ok {
		if err := validResponse.VisitPlatformMarkInboxReadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformListNotificationTemplates operation middleware
func (sh *strictHandler) PlatformListNotificationTemplates(w http.ResponseWriter, r *http.Request, params PlatformListNotificationTemplatesParams) {
	var request PlatformListNotificationTemplatesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformListNotificationTemplates(ctx, request.(PlatformListNotificationTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformListNotificationTemplates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformListNotificationTemplatesResponseObject); ok {
		if err := validResponse.VisitPlatformListNotificationTemplatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformCreateNotificationTemplate operation middleware
func (sh *strictHandler) PlatformCreateNotificationTemplate(w http.ResponseWriter, r *http.Request, params PlatformCreateNotificationTemplateParams) {
	var request PlatformCreateNotificationTemplateRequestObject

	request.Params = params

	var body PlatformCreateNotificationTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformCreateNotificationTemplate(ctx, request.(PlatformCreateNotificationTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformCreateNotificationTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformCreateNotificationTemplateResponseObject); ok {
		if err := validResponse.VisitPlatformCreateNotificationTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformPreviewNotificationTemplate operation middleware
func (sh *strictHandler) PlatformPreviewNotificationTemplate(w http.ResponseWriter, r *http.Request, params PlatformPreviewNotificationTemplateParams) {
	var request PlatformPreviewNotificationTemplateRequestObject

	request.Params = params

	var body PlatformPreviewNotificationTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformPreviewNotificationTemplate(ctx, request.(PlatformPreviewNotificationTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformPreviewNotificationTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformPreviewNotificationTemplateResponseObject); ok {
		if err := validResponse.VisitPlatformPreviewNotificationTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformDeleteNotificationTemplate operation middleware
func (sh *strictHandler) PlatformDeleteNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformDeleteNotificationTemplateParams) {
	var request PlatformDeleteNotificationTemplateRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformDeleteNotificationTemplate(ctx, request.(PlatformDeleteNotificationTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformDeleteNotificationTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformDeleteNotificationTemplateResponseObject); ok {
		if err := validResponse.VisitPlatformDeleteNotificationTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformGetNotificationTemplate operation middleware
func (sh *strictHandler) PlatformGetNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetNotificationTemplateParams) {
	var request PlatformGetNotificationTemplateRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformGetNotificationTemplate(ctx, request.(PlatformGetNotificationTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformGetNotificationTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformGetNotificationTemplateResponseObject); ok {
		if err := validResponse.VisitPlatformGetNotificationTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformUpdateNotificationTemplate operation middleware
func (sh *strictHandler) PlatformUpdateNotificationTemplate(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformUpdateNotificationTemplateParams) {
	var request PlatformUpdateNotificationTemplateRequestObject

	request.Id = id
	request.Params = params

	var body PlatformUpdateNotificationTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformUpdateNotificationTemplate(ctx, request.(PlatformUpdateNotificationTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformUpdateNotificationTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformUpdateNotificationTemplateResponseObject); ok {
		if err := validResponse.VisitPlatformUpdateNotificationTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformListNotifications operation middleware
func (sh *strictHandler) PlatformListNotifications(w http.ResponseWriter, r *http.Request, params PlatformListNotificationsParams) {
	var request PlatformListNotificationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformListNotifications(ctx, request.(PlatformListNotificationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformListNotifications")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformListNotificationsResponseObject); ok {
		if err := validResponse.VisitPlatformListNotificationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlatformGetNotification operation middleware
func (sh *strictHandler) PlatformGetNotification(w http.ResponseWriter, r *http.Request, id Uuid, params PlatformGetNotificationParams) {
	var request PlatformGetNotificationRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformGetNotification(ctx, request.(PlatformGetNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformGetNotification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlatformGetNotificationResponseObject); ok {
		if err := validResponse.VisitPlatformGetNotificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
